// ---------------------------------------------------------------------------
// HTTP header name constants for Sonalit v4
// All custom headers follow the X- prefix convention.
// ---------------------------------------------------------------------------
/** Bearer token issued to a Guardian device after enrollment. */
export const HEADER_DEVICE_TOKEN = 'X-Device-Token';
/**
 * Client-supplied idempotency key.
 * Must be unique per (method, path, request body) triplet.
 * Honoured for POST and PATCH requests.
 */
export const HEADER_IDEMPOTENCY_KEY = 'Idempotency-Key';
/** Organisation identifier — validated against the JWT org claim. */
export const HEADER_ORG_ID = 'X-Org-Id';
/** Unique request identifier generated by the API gateway or client. */
export const HEADER_REQUEST_ID = 'X-Request-Id';
/** OpenTelemetry / distributed tracing propagation header. */
export const HEADER_TRACE_ID = 'X-Trace-Id';
/** Forwarded client IP — set by reverse proxy / CDN. */
export const HEADER_FORWARDED_FOR = 'X-Forwarded-For';
/** Webhook signature: HMAC-SHA256 of the request body. Format: "sha256=<hex>". */
export const HEADER_WEBHOOK_SIGNATURE = 'X-Sonalit-Signature';
/** Webhook event type — mirrors WebhookEvent enum values. */
export const HEADER_WEBHOOK_EVENT = 'X-Sonalit-Event';
/** API version negotiation — e.g. "2024-01-01". */
export const HEADER_API_VERSION = 'X-Api-Version';
/** CSRF double-submit token — must match the value of the __Host-csrf cookie. */
export const HEADER_CSRF_TOKEN = 'X-CSRF-Token';
