// ---------------------------------------------------------------------------
// HTTP header name constants for Sonalit v4
// All custom headers follow the X- prefix convention.
// ---------------------------------------------------------------------------

/** Bearer token issued to a Guardian device after enrollment. */
export const HEADER_DEVICE_TOKEN = 'X-Device-Token' as const;

/**
 * Client-supplied idempotency key.
 * Must be unique per (method, path, request body) triplet.
 * Honoured for POST and PATCH requests.
 */
export const HEADER_IDEMPOTENCY_KEY = 'Idempotency-Key' as const;

/** Organisation identifier — validated against the JWT org claim. */
export const HEADER_ORG_ID = 'X-Org-Id' as const;

/** Unique request identifier generated by the API gateway or client. */
export const HEADER_REQUEST_ID = 'X-Request-Id' as const;

/** OpenTelemetry / distributed tracing propagation header. */
export const HEADER_TRACE_ID = 'X-Trace-Id' as const;

/** Forwarded client IP — set by reverse proxy / CDN. */
export const HEADER_FORWARDED_FOR = 'X-Forwarded-For' as const;

/** Webhook signature: HMAC-SHA256 of the request body. Format: "sha256=<hex>". */
export const HEADER_WEBHOOK_SIGNATURE = 'X-Sonalit-Signature' as const;

/** Webhook event type — mirrors WebhookEvent enum values. */
export const HEADER_WEBHOOK_EVENT = 'X-Sonalit-Event' as const;

/** API version negotiation — e.g. "2024-01-01". */
export const HEADER_API_VERSION = 'X-Api-Version' as const;

/** CSRF double-submit token — must match the value of the __Host-csrf cookie. */
export const HEADER_CSRF_TOKEN = 'X-CSRF-Token' as const;

// ---------------------------------------------------------------------------
// Type map for header values (for use with typed fetch wrappers)
// ---------------------------------------------------------------------------

export type SonalitRequestHeaders = {
  [HEADER_DEVICE_TOKEN]?: string;
  [HEADER_IDEMPOTENCY_KEY]?: string;
  [HEADER_ORG_ID]?: string;
  [HEADER_REQUEST_ID]?: string;
  [HEADER_TRACE_ID]?: string;
  [HEADER_CSRF_TOKEN]?: string;
  Authorization?: string;
  'Content-Type'?: string;
  Accept?: string;
};

export type SonalitWebhookHeaders = {
  [HEADER_WEBHOOK_SIGNATURE]: string;
  [HEADER_WEBHOOK_EVENT]: string;
  [HEADER_REQUEST_ID]?: string;
  'Content-Type': 'application/json';
};
