apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: guardian-cpu-stress
  namespace: sonalit-prod
spec:
  mode: all
  selector:
    namespaces: [sonalit-prod]
    labelSelectors:
      app.kubernetes.io/name: guardian-svc
  stressors:
    cpu:
      workers: 4
      load: 200
  duration: 60s
  scheduler:
    cron: "@every 2h"
