apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: nats-node-kill
  namespace: sonalit-prod
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces: [sonalit-prod]
    labelSelectors:
      app.kubernetes.io/name: nats
  scheduler:
    cron: "@every 60m"
