packages:
  - 'apps/web'
  - 'apps/container-delivery-system'
  - 'backend'
  - 'services/*'
  - 'packages/*'

overrides:
  form-data: 4.0.6
  websocket-driver: 0.7.5
  proxy-addr: 2.0.8
  ws: 8.21.0
  protobufjs: 7.6.1
  brace-expansion: 2.1.6
  'minimatch@10.2.5>brace-expansion': 5.0.12
  socket.io-parser: 4.2.7
  ip-address: 10.3.1
  engine.io: 6.6.10
  '@grpc/grpc-js': 1.14.5
  '@fastify/busboy': 3.2.1

allowBuilds:
  '@firebase/util': true
  '@vaadin/vaadin-usage-statistics': true
  bufferutil: true
  cpu-features: true
  es5-ext: true
  esbuild: true
  msgpackr-extract: true
  protobufjs: true
  ssh2: true
  tesseract.js: true
  unrs-resolver: true
  utf-8-validate: true
