FROM node:20-alpine

WORKDIR /app

COPY package.json ./
RUN npm install --omit=dev --ignore-scripts

COPY src ./src
COPY migrations ./migrations
COPY scripts ./scripts

ENV NODE_ENV=production

CMD ["node", "src/workers/worker.notification.js"]
