const {evaluateConvoySnapshot}=require('../src/services/convoyOperationalResilience');
const route=[{lat:0,lng:0},{lat:0,lng:1},{lat:0,lng:2}];
const truck=(id,lng,extra={})=>({truck_id:id,vehicle_id:'v-'+id,lat:0,lng,speed_kmh:60,last_fix_at:'2026-10-03T06:20:00Z',cfo_user_id:'cfo-'+id,cfo_lat:0,cfo_lng:lng,cfo_last_seen_at:'2026-10-03T06:20:00Z',...extra});
describe('convoy operational resilience',()=>{
 test('detects lagging truck without inventing breakdown',()=>{const r=evaluateConvoySnapshot({now:'2026-10-03T06:20:00Z',convoy:{id:'c1',status:'active'},route,trucks:[truck('t1',.2),truck('t2',.85),truck('t3',.9)]});expect(r.exceptions.some(x=>x.exception_type==='truck_lagging'&&x.convoy_truck_id==='t1')).toBe(true);expect(r.exceptions.some(x=>x.exception_type==='vehicle_breakdown')).toBe(false);});
 test('detects explicit breakdown and exposes recovery/MRT/static options',()=>{const r=evaluateConvoySnapshot({now:'2026-10-03T06:20:00Z',convoy:{id:'c2',status:'active'},route,trucks:[truck('t1',.5),truck('t2',.7,{speed_kmh:0,breakdown_signal:true})],response_resources:[{type:'recovery',status:'standby',active:true},{type:'mobile_response',status:'standby',active:true},{type:'static_guard',status:'standby',active:true}]});const e=r.exceptions.find(x=>x.exception_type==='vehicle_breakdown');expect(e).toBeTruthy();expect(e.recommended_actions.find(x=>x.type==='dispatch_recovery').available).toBe(true);expect(e.recommended_actions.find(x=>x.type==='dispatch_mobile_response').available).toBe(true);expect(e.recommended_actions.find(x=>x.type==='deploy_static_guard').available).toBe(true);});
 test('detects shared CFO coverage conflict',()=>{const r=evaluateConvoySnapshot({now:'2026-10-03T06:20:00Z',convoy:{id:'c3',status:'active'},route,trucks:[truck('t1',.1,{cfo_user_id:'shared',cfo_lng:.1}),truck('t2',.95,{cfo_user_id:'shared',cfo_lng:.1})]});const e=r.exceptions.find(x=>x.exception_type==='cfo_coverage_gap'&&x.convoy_truck_id==='t2');expect(e).toBeTruthy();expect(e.context.shared_cfo_conflict).toBe(true);});
 test('stale telemetry is not a breakdown',()=>{const r=evaluateConvoySnapshot({now:'2026-10-03T06:20:00Z',convoy:{id:'c4',status:'active'},route,trucks:[truck('t1',.5,{last_fix_at:'2026-10-03T05:50:00Z'}),truck('t2',.55)]});expect(r.exceptions.some(x=>x.exception_type==='telemetry_gap'&&x.convoy_truck_id==='t1')).toBe(true);expect(r.exceptions.some(x=>x.exception_type==='vehicle_breakdown'&&x.convoy_truck_id==='t1')).toBe(false);});
 test('resource shortage is surfaced, not auto-dispatched',()=>{const r=evaluateConvoySnapshot({now:'2026-10-03T06:20:00Z',convoy:{id:'c5',status:'active'},route,trucks:[truck('t1',.4,{breakdown_signal:true})],response_resources:[]});expect(r.resource_conflicts.some(x=>x.resource_type==='recovery')).toBe(true);expect(r.exceptions.every(e=>(e.recommended_actions||[]).every(a=>a.requires_authorization===true))).toBe(true);});
 test('operator road blockage is retained',()=>{const r=evaluateConvoySnapshot({now:'2026-10-03T06:20:00Z',convoy:{id:'c6',status:'active'},route,trucks:[truck('t1',.4)],manual_signals:[{id:'s1',fingerprint:'manual:road_blockage:convoy',type:'road_blockage',severity:'high',title:'Road blocked',detail:'Blocked by incident.'}]});expect(r.exceptions.some(x=>x.exception_type==='road_blockage')).toBe(true);});
});