-- Spatial alert identity hardening.
-- Prevents concurrent workers from emitting duplicate open operational alerts
-- for the same semantic spatial condition/occurrence.
-- Spatial alerts carry metadata.source = 'sonalit-spatial' and a stable
-- metadata.spatialAlertKey generated by spatialEvents.js.

DELETE FROM alerts a
USING alerts b
WHERE a.id <> b.id
  AND a.org_id = b.org_id
  AND a.deleted_at IS NULL
  AND b.deleted_at IS NULL
  AND a.resolved_at IS NULL
  AND b.resolved_at IS NULL
  AND a.metadata->>'source' = 'sonalit-spatial'
  AND b.metadata->>'source' = 'sonalit-spatial'
  AND a.metadata->>'spatialAlertKey' IS NOT NULL
  AND a.metadata->>'spatialAlertKey' = b.metadata->>'spatialAlertKey'
  AND (a.created_at > b.created_at OR (a.created_at = b.created_at AND a.id::text > b.id::text));

CREATE UNIQUE INDEX IF NOT EXISTS alerts_open_spatial_identity
  ON alerts(org_id, (metadata->>'spatialAlertKey'))
  WHERE deleted_at IS NULL
    AND resolved_at IS NULL
    AND metadata->>'source' = 'sonalit-spatial'
    AND metadata->>'spatialAlertKey' IS NOT NULL;
