-- Notification Authority & Asset Ownership
-- Ownership is the authoritative boundary for external notification fan-out.
-- Super admins retain global visibility; client recipients only receive events
-- generated by assets explicitly assigned to their client.

ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS client_id UUID REFERENCES cargo_clients(id);
CREATE INDEX IF NOT EXISTS idx_vehicles_org_client ON vehicles (org_id, client_id) WHERE deleted_at IS NULL;

ALTER TABLE guardian_devices ADD COLUMN IF NOT EXISTS org_id UUID;
ALTER TABLE guardian_devices ADD COLUMN IF NOT EXISTS client_id UUID REFERENCES cargo_clients(id);
CREATE INDEX IF NOT EXISTS idx_guardian_devices_org_client ON guardian_devices (org_id, client_id) WHERE deleted_at IS NULL;

ALTER TABLE client_email_recipients ADD COLUMN IF NOT EXISTS client_id UUID REFERENCES cargo_clients(id);
CREATE INDEX IF NOT EXISTS idx_client_email_recipients_client
  ON client_email_recipients (org_id, client_id, enabled) WHERE deleted_at IS NULL;

ALTER TABLE communication_enrollments ADD COLUMN IF NOT EXISTS client_id UUID REFERENCES cargo_clients(id);
DROP INDEX IF EXISTS uq_communication_enrollment_scope;
CREATE UNIQUE INDEX IF NOT EXISTS uq_communication_enrollment_scope
  ON communication_enrollments (
    org_id,
    recipient_id,
    domain,
    COALESCE(cds_customer_id, '00000000-0000-0000-0000-000000000000'::uuid),
    COALESCE(client_id, '00000000-0000-0000-0000-000000000000'::uuid)
  );

ALTER TABLE communication_enrollments DROP CONSTRAINT IF EXISTS communication_enrollment_fleet_scope;
ALTER TABLE communication_enrollments
  ADD CONSTRAINT communication_enrollment_fleet_scope CHECK (
    (domain = 'fleet' AND cds_customer_id IS NULL)
    OR (domain = 'cds' AND cds_customer_id IS NOT NULL AND client_id IS NULL)
    OR (domain = 'platform' AND cds_customer_id IS NULL AND client_id IS NULL)
  );

CREATE INDEX IF NOT EXISTS idx_communication_enrollments_fleet_client
  ON communication_enrollments (org_id, client_id, status) WHERE domain = 'fleet';

COMMENT ON COLUMN vehicles.client_id IS 'Authoritative client ownership. NULL means Admin-owned/unassigned for notification routing.';
COMMENT ON COLUMN guardian_devices.org_id IS 'Organization scope for Guardian devices; nullable for legacy devices pending reconciliation.';
COMMENT ON COLUMN guardian_devices.client_id IS 'Authoritative client ownership when the device is not inheriting ownership from an assigned vehicle.';
COMMENT ON COLUMN client_email_recipients.client_id IS 'Client ownership for external notification recipients. NULL means Admin/global recipient.';
COMMENT ON COLUMN communication_enrollments.client_id IS 'Fleet notification recipient scope. NULL means organization/Admin scope; non-null binds the recipient to one client.';
