export const SHIPMENT_STATUS_LABELS: Record<string, string> = {
  created: 'Created',
  customer_assigned: 'Customer Assigned',
  container_assigned: 'Container Assigned',
  vehicle_assigned: 'Vehicle Assigned',
  driver_assigned: 'Driver Assigned',
  awaiting_lock: 'Awaiting Lock',
  locked: 'Locked',
  lock_assigned: 'Lock Assigned',
  tracking_active: 'Tracking Active',
  dispatched: 'Dispatched',
  in_transit: 'In Transit',
  checkpoint: 'Checkpoint',
  delayed: 'Delayed',
  border_crossing: 'Border Crossing',
  at_port: 'At Port',
  arrived: 'Arrived',
  unlock_authorized: 'Unlock Authorized',
  delivered: 'Delivered',
  lock_removed: 'Lock Removed',
  completed: 'Completed',
  container_returned: 'Container Returned',
  closed: 'Closed',
  archived: 'Archived',
};

export const CONTAINER_TYPES: Record<string, string> = {
  '20GP': "20' General Purpose",
  '40GP': "40' General Purpose",
  '40HC': "40' High Cube",
  '20RF': "20' Reefer",
  '40RF': "40' Reefer",
  '20OT': "20' Open Top",
  '40OT': "40' Open Top",
  '20FR': "20' Flat Rack",
  '40FR': "40' Flat Rack",
  '20TK': "20' Tank",
};

export const ALERT_SEVERITY_COLORS: Record<string, string> = {
  critical: '#ff5c5c',
  high: '#ff5c5c',
  medium: '#ffb020',
  low: '#33d6a8',
  info: '#6b7380',
};

export const RISK_BADGE_STYLES: Record<string, { bg: string; color: string; label: string }> = {
  low: { bg: 'bg-cds-teal-dim', color: 'text-cds-teal', label: 'LOW' },
  medium: { bg: 'bg-cds-amber-dim', color: 'text-cds-amber', label: 'MEDIUM' },
  high: { bg: 'bg-cds-red-dim', color: 'text-cds-red', label: 'HIGH' },
  critical: { bg: 'bg-cds-red-dim', color: 'text-cds-red', label: 'CRITICAL' },
};

export const STATUS_BADGE_STYLES: Record<string, { bg: string; color: string; label: string }> = {
  created: { bg: 'bg-ink-3', color: 'text-text-1', label: 'CREATED' },
  draft: { bg: 'bg-ink-3', color: 'text-text-1', label: 'DRAFT' },
  pending: { bg: 'bg-ink-3', color: 'text-text-1', label: 'PENDING' },
  approved: { bg: 'bg-cds-teal-dim', color: 'text-cds-teal', label: 'APPROVED' },
  assigned: { bg: 'bg-cds-orange-dim', color: 'text-cds-orange', label: 'ASSIGNED' },
  vehicle_assigned: { bg: 'bg-cds-orange-dim', color: 'text-cds-orange', label: 'VEH ASSIGNED' },
  driver_assigned: { bg: 'bg-cds-orange-dim', color: 'text-cds-orange', label: 'DRV ASSIGNED' },
  awaiting_lock: { bg: 'bg-cds-amber-dim', color: 'text-cds-amber', label: 'AWAITING LOCK' },
  locked: { bg: 'bg-cds-teal-dim', color: 'text-cds-teal', label: 'LOCKED' },
  installed: { bg: 'bg-cds-teal-dim', color: 'text-cds-teal', label: 'INSTALLED' },
  dispatched: { bg: 'bg-cds-teal-dim', color: 'text-cds-teal', label: 'DISPATCHED' },
  in_transit: { bg: 'bg-cds-teal-dim', color: 'text-cds-teal', label: 'IN TRANSIT' },
  transit: { bg: 'bg-cds-teal-dim', color: 'text-cds-teal', label: 'IN TRANSIT' },
  checkpoint: { bg: 'bg-cds-amber-dim', color: 'text-cds-amber', label: 'CHECKPOINT' },
  delayed: { bg: 'bg-cds-red-dim', color: 'text-cds-red', label: 'DELAYED' },
  at_port: { bg: 'bg-cds-amber-dim', color: 'text-cds-amber', label: 'AT PORT' },
  arrived: { bg: 'bg-cds-teal-dim', color: 'text-cds-teal', label: 'ARRIVED' },
  delivered: { bg: 'bg-cds-teal-dim', color: 'text-cds-teal', label: 'DELIVERED' },
  lock_removed: { bg: 'bg-purple-500/15', color: 'text-purple-400', label: 'UNCLAMPED' },
  removed: { bg: 'bg-purple-500/15', color: 'text-purple-400', label: 'REMOVED' },
  completed: { bg: 'bg-emerald-500/15', color: 'text-emerald-400', label: 'COMPLETED' },
  archived: { bg: 'bg-ink-3', color: 'text-text-1', label: 'ARCHIVED' },
  cancelled: { bg: 'bg-cds-red-dim', color: 'text-cds-red', label: 'CANCELLED' },
  active: { bg: 'bg-cds-teal-dim', color: 'text-cds-teal', label: 'ACTIVE' },
  idle: { bg: 'bg-ink-3', color: 'text-text-1', label: 'IDLE' },
  available: { bg: 'bg-cds-teal-dim', color: 'text-cds-teal', label: 'AVAILABLE' },
  unlocked: { bg: 'bg-cds-amber-dim', color: 'text-cds-amber', label: 'UNLOCKED' },
  offline: { bg: 'bg-cds-red-dim', color: 'text-cds-red', label: 'OFFLINE' },
  tampered: { bg: 'bg-cds-red-dim', color: 'text-cds-red', label: 'TAMPERED' },
  maintenance: { bg: 'bg-cds-amber-dim', color: 'text-cds-amber', label: 'MAINTENANCE' },
  closed: { bg: 'bg-ink-3', color: 'text-text-1', label: 'CLOSED' },
  in_progress: { bg: 'bg-cds-teal-dim', color: 'text-cds-teal', label: 'IN PROGRESS' },
  generating: { bg: 'bg-cds-amber-dim', color: 'text-cds-amber', label: 'GENERATING' },
  ready: { bg: 'bg-cds-teal-dim', color: 'text-cds-teal', label: 'READY' },
  failed: { bg: 'bg-cds-red-dim', color: 'text-cds-red', label: 'FAILED' },
  on_break: { bg: 'bg-cds-amber-dim', color: 'text-cds-amber', label: 'ON BREAK' },
  off_duty: { bg: 'bg-ink-3', color: 'text-text-1', label: 'OFF DUTY' },
  suspended: { bg: 'bg-cds-red-dim', color: 'text-cds-red', label: 'SUSPENDED' },
  damaged: { bg: 'bg-cds-red-dim', color: 'text-cds-red', label: 'DAMAGED' },
  retired: { bg: 'bg-ink-3', color: 'text-text-1', label: 'RETIRED' },
  in_use: { bg: 'bg-cds-teal-dim', color: 'text-cds-teal', label: 'IN USE' },
  decommissioned: { bg: 'bg-ink-3', color: 'text-text-1', label: 'DECOMMISSIONED' },
  inactive: { bg: 'bg-ink-3', color: 'text-text-1', label: 'INACTIVE' },
};

export const NAV_ITEMS = [
  { id: 'dashboard', label: 'Dashboard', path: '/cds', icon: 'dashboard' },
  { id: 'shipments', label: 'Shipments', path: '/cds/shipments', icon: 'shipments' },
  { id: 'containers', label: 'Containers', path: '/cds/containers', icon: 'containers' },
  { id: 'locks', label: 'E-Locks', path: '/cds/locks', icon: 'locks' },
  { id: 'live', label: 'Live Tracking', path: '/cds/live', icon: 'live' },
  { id: 'drivers', label: 'Drivers', path: '/cds/drivers', icon: 'drivers' },
  { id: 'vehicles', label: 'Vehicles', path: '/cds/vehicles', icon: 'vehicles' },
  { id: 'transporters', label: 'Transporters', path: '/cds/transporters', icon: 'transporters' },
  { id: 'customers', label: 'Customers', path: '/cds/customers', icon: 'customers' },
  { id: 'delivery', label: 'Delivery Ops', path: '/cds/delivery', icon: 'delivery' },
  { id: 'geofences', label: 'Geofences', path: '/cds/geofences', icon: 'geofences' },
  { id: 'inbox', label: 'AI Inbox', path: '/cds/inbox', icon: 'inbox' },
  { id: 'incidents', label: 'Incidents', path: '/cds/incidents', icon: 'incidents' },
  { id: 'alerts', label: 'Alerts', path: '/cds/alerts', icon: 'alerts' },
  { id: 'documents', label: 'Documents', path: '/cds/documents', icon: 'documents' },
  { id: 'reports', label: 'Reports', path: '/cds/reports', icon: 'reports' },
  { id: 'analytics', label: 'Analytics', path: '/cds/analytics', icon: 'analytics' },
  { id: 'audit', label: 'Audit Logs', path: '/cds/audit', icon: 'audit' },
  { id: 'settings', label: 'Settings', path: '/cds/settings', icon: 'settings' },
] as const;
