'use strict';
const { projectOntoRoute,haversineKm }=require('./geofence/corridor');
const { publish }=require('../realtime/centrifugo');
const ACTIVE_EXCEPTION_STATUSES=['open','acknowledged','mitigating'];
const TERMINAL_EXCEPTION_STATUSES=['resolved','waived'];
const DEFAULTS=Object.freeze({separation_km:5,lagging_km:8,lagging_minutes:10,ahead_km:8,cfo_coverage_km:5,telemetry_stale_minutes:10,cfo_stale_minutes:10,stationary_speed_kmh:3,stationary_minutes:10,corridor_km:2,avg_speed_kmh:45});
const SCENARIOS=[
['departure_readiness','Departure readiness',['missing truck/GPS','uncovered truck','unusable route']],
['truck_lagging','Truck delayed behind convoy',['relative progress lag']],
['convoy_separation','Convoy split / physical separation',['nearest-neighbour separation']],
['truck_ahead','Truck outruns convoy',['ahead-of-group progress']],
['vehicle_breakdown','Vehicle breakdown / immobilisation',['explicit mechanical signal']],
['extended_stop','Extended unplanned stop',['sustained near-zero movement']],
['telemetry_gap','Telemetry / communications gap',['stale vehicle fix']],
['cfo_coverage_gap','CFO coverage gap',['missing/stale CFO','CFO too far from assigned truck']],
['shared_cfo_conflict','CFO pulled toward one assigned truck',['shared CFO loses coverage on another truck']],
['route_deviation','Route deviation',['cross-track corridor breach']],
['checkpoint_delay','Checkpoint / border delay',['operator signal']],
['road_blockage','Road blockage / forced hold',['operator signal']],
['security_event','Security event',['operator security signal']],
['resource_conflict','Response resource conflict',['required resource unavailable']],
['rejoin','Truck rejoin / exception clearance',['exception condition clears']]
].map(([id,label,detects])=>({id,label,detects}));
const num=(v,f=null)=>Number.isFinite(Number(v))?Number(v):f;
const ageMinutes=(v,now)=>{if(!v)return Infinity;const t=new Date(v).getTime();return Number.isFinite(t)?Math.max(0,(now-t)/60000):Infinity};
const round=v=>Number.isFinite(v)?Math.round(v*100)/100:null;
const median=a=>{if(!a.length)return null;const s=[...a].sort((x,y)=>x-y),m=Math.floor(s.length/2);return s.length%2?s[m]:(s[m-1]+s[m])/2};
const env=(k,f)=>Number.isFinite(Number(process.env[k]))?Number(process.env[k]):f;
function resolveConfig(o={}){return {separation_km:num(o.separation_km,env('CONVOY_RESILIENCE_SEPARATION_KM',5)),lagging_km:num(o.lagging_km,env('CONVOY_RESILIENCE_LAGGING_KM',8)),lagging_minutes:num(o.lagging_minutes,env('CONVOY_RESILIENCE_LAGGING_MINUTES',10)),ahead_km:num(o.ahead_km,env('CONVOY_RESILIENCE_AHEAD_KM',8)),cfo_coverage_km:num(o.cfo_coverage_km,env('CONVOY_RESILIENCE_CFO_COVERAGE_KM',5)),telemetry_stale_minutes:num(o.telemetry_stale_minutes,env('CONVOY_RESILIENCE_TELEMETRY_STALE_MINUTES',10)),cfo_stale_minutes:num(o.cfo_stale_minutes,env('CONVOY_RESILIENCE_CFO_STALE_MINUTES',10)),stationary_speed_kmh:num(o.stationary_speed_kmh,env('CONVOY_RESILIENCE_STATIONARY_SPEED_KMH',3)),stationary_minutes:num(o.stationary_minutes,env('CONVOY_RESILIENCE_STATIONARY_MINUTES',10)),corridor_km:num(o.corridor_km,env('CONVOY_RESILIENCE_CORRIDOR_KM',2)),avg_speed_kmh:num(o.avg_speed_kmh,env('CONVOY_RESILIENCE_AVG_SPEED_KMH',45))}}
const act=(type,label,resource_type=null)=>({type,label,resource_type,requires_authorization:true});
const recommend=type=>({truck_lagging:[act('contact_driver','Contact driver and verify delay'),act('reassign_backup_cfo','Restore CFO coverage if primary stays with lagging truck'),act('dispatch_mobile_response','Dispatch mobile response support','mobile_response'),act('regroup_convoy','Regroup at controlled location')],convoy_separation:[act('verify_comms','Verify communications and exact truck status'),act('reassign_backup_cfo','Restore CFO coverage to separated element'),act('dispatch_mobile_response','Dispatch mobile response support','mobile_response'),act('regroup_convoy','Regroup at controlled location')],truck_ahead:[act('verify_escort_coverage','Verify escort/CFO coverage'),act('hold_or_regroup','Hold or regroup at controlled location'),act('reassign_backup_cfo','Reassign coverage if escort is no longer adjacent')],vehicle_breakdown:[act('hold_affected_vehicle','Securely hold/isolate affected truck'),act('dispatch_recovery','Dispatch recovery capability','recovery'),act('deploy_static_guard','Deploy static guard protection where required','static_guard'),act('dispatch_mobile_response','Dispatch mobile response support','mobile_response')],extended_stop:[act('contact_driver','Verify reason for extended stop'),act('hold_or_regroup','Control convoy movement while assessed'),act('reassign_backup_cfo','Restore coverage if CFO remains with stopped truck')],telemetry_gap:[act('verify_comms','Verify driver, device, network and last-known position'),act('do_not_assume_breakdown','Do not classify telemetry loss as a breakdown')],cfo_coverage_gap:[act('reassign_backup_cfo','Reassign backup CFO'),act('dispatch_mobile_response','Dispatch mobile response support','mobile_response'),act('deploy_static_guard','Deploy static guard protection where required','static_guard')],route_deviation:[act('contact_driver','Verify route and driver intent'),act('verify_escort_coverage','Verify escort/CFO coverage during deviation'),act('dispatch_mobile_response','Dispatch mobile response if security concern develops','mobile_response')],checkpoint_delay:[act('contact_driver','Verify checkpoint/border status'),act('hold_or_regroup','Maintain controlled convoy disposition')],road_blockage:[act('hold_or_regroup','Hold or regroup at a safe controlled location'),act('verify_comms','Confirm blockage and alternate-route status'),act('dispatch_mobile_response','Dispatch mobile response if protection is required','mobile_response')],security_event:[act('escalate_operator','Escalate to security controller / incident commander'),act('dispatch_mobile_response','Dispatch mobile response support','mobile_response'),act('deploy_static_guard','Deploy static protection where required','static_guard')],departure_readiness:[act('hold_departure','Hold departure until readiness gaps are closed')]})[type]||[act('escalate_operator','Escalate for operator review')];
const resourceCount=(rs,type)=>{const a=type==='mobile_response'?['mobile_response','reaction','armed_response']:[type];return (rs||[]).filter(r=>r.active!==false&&r.status==='standby'&&a.includes(String(r.type||'').toLowerCase())).length};
function evaluateConvoySnapshot(snapshot,o={}){
 const c=resolveConfig(o),raw=snapshot.now?new Date(snapshot.now).getTime():Date.now(),now=Number.isFinite(raw)?raw:Date.now(),convoy=snapshot.convoy||{},route=Array.isArray(snapshot.route)?snapshot.route:[],routeReady=route.length>=2;
 const trucks=(snapshot.trucks||[]).map(t=>({...t,truck_id:String(t.truck_id||t.id),vehicle_id:t.vehicle_id?String(t.vehicle_id):null})),rs=snapshot.response_resources||[],pos=[],proj=new Map(),nearest=new Map(),byCfo=new Map();
 for(const t of trucks){const lat=num(t.lat),lng=num(t.lng);if(lat==null||lng==null)continue;pos.push({...t,lat,lng});if(routeReady)proj.set(t.truck_id,projectOntoRoute(route,lat,lng))}
 for(const a of pos){let d=Infinity;for(const b of pos)if(a.truck_id!==b.truck_id)d=Math.min(d,haversineKm(a.lat,a.lng,b.lat,b.lng));if(pos.length>1)nearest.set(a.truck_id,d)}
 for(const t of trucks)if(t.cfo_user_id){const id=String(t.cfo_user_id);if(!byCfo.has(id))byCfo.set(id,[]);byCfo.get(id).push(t.truck_id)}
 const groupAlong=median([...proj.values()].map(p=>p.alongKm).filter(Number.isFinite)),out=[],seen=new Set();
 const add=e=>{if(seen.has(e.fingerprint))return;seen.add(e.fingerprint);const acts=(e.recommended_actions||[]).map(a=>a.resource_type?{...a,available:resourceCount(rs,a.resource_type)>0}:a);out.push({...e,status:'open',recommended_actions:acts,resource_unavailable:acts.filter(a=>a.resource_type&&a.available===false).map(a=>a.resource_type)})};
 for(const s of snapshot.manual_signals||[]){const type=s.type==='mechanical_failure'?'vehicle_breakdown':s.type;add({fingerprint:s.fingerprint||'manual:'+type+':'+String(s.convoy_truck_id||'convoy'),exception_type:type,severity:s.severity||'high',source:'operator',convoy_truck_id:s.convoy_truck_id||null,vehicle_id:s.vehicle_id||null,cfo_user_id:s.cfo_user_id||null,title:s.title||type.replaceAll('_',' '),detail:s.detail||'Operator-supplied operational signal.',context:{manual:true,signal_id:s.id||null,...(s.context||{})},recommended_actions:recommend(type)})}
 if(convoy.status==='planned'&&(!routeReady||!trucks.length))add({fingerprint:'convoy:departure_readiness',exception_type:'departure_readiness',severity:'high',source:'derived',title:'Departure readiness incomplete',detail:routeReady?'No trucks are on the operational roster.':'No evaluable route has at least two geographic waypoints.',context:{route_ready:routeReady,truck_count:trucks.length},recommended_actions:recommend('departure_readiness')});
 for(const t of trucks){
  const p=proj.get(t.truck_id),lat=num(t.lat),lng=num(t.lng),fixAge=ageMinutes(t.last_fix_at||t.gps_at,now),cfoAge=ageMinutes(t.cfo_last_seen_at,now),cfo=t.cfo_user_id?String(t.cfo_user_id):null,shared=cfo?(byCfo.get(cfo)||[]):[],cfoDist=lat!=null&&lng!=null&&num(t.cfo_lat)!=null&&num(t.cfo_lng)!=null?haversineKm(lat,lng,num(t.cfo_lat),num(t.cfo_lng)):null,covered=!!cfo&&cfoAge<=c.cfo_stale_minutes&&cfoDist!=null&&cfoDist<=c.cfo_coverage_km,broken=!!t.breakdown_signal||String(t.mechanical_state||'').toLowerCase()==='breakdown';
  if(broken)add({fingerprint:'truck:'+t.truck_id+':vehicle_breakdown',exception_type:'vehicle_breakdown',severity:'critical',source:'explicit',convoy_truck_id:t.truck_id,vehicle_id:t.vehicle_id,cfo_user_id:cfo,title:'Vehicle breakdown / immobilisation',detail:'Explicit mechanical/breakdown signal. Zero speed alone is never proof.',context:{speed_kmh:num(t.speed_kmh,0),cfo_distance_km:round(cfoDist),shared_cfo_count:shared.length},recommended_actions:recommend('vehicle_breakdown')});
  if(t.security_signal)add({fingerprint:'truck:'+t.truck_id+':security_event',exception_type:'security_event',severity:'critical',source:'explicit',convoy_truck_id:t.truck_id,vehicle_id:t.vehicle_id,cfo_user_id:cfo,title:'Security event reported',detail:'Explicit security signal attached to this truck.',context:{fix_age_min:round(fixAge)},recommended_actions:recommend('security_event')});
  if(fixAge>c.telemetry_stale_minutes)add({fingerprint:'truck:'+t.truck_id+':telemetry_gap',exception_type:'telemetry_gap',severity:'medium',source:'derived',convoy_truck_id:t.truck_id,vehicle_id:t.vehicle_id,cfo_user_id:cfo,title:'Telemetry / communications gap',detail:'No fresh position is available; this is not proof of a stop or compromise.',context:{last_fix_at:t.last_fix_at||t.gps_at||null,fix_age_min:round(fixAge)},recommended_actions:recommend('telemetry_gap')});
  if(num(t.stationary_minutes)>=c.stationary_minutes&&num(t.speed_kmh,0)<=c.stationary_speed_kmh&&!broken)add({fingerprint:'truck:'+t.truck_id+':extended_stop',exception_type:'extended_stop',severity:'medium',source:'derived',convoy_truck_id:t.truck_id,vehicle_id:t.vehicle_id,cfo_user_id:cfo,title:'Extended unplanned stop',detail:'Near-stationary beyond threshold; verify the reason before classifying a breakdown.',context:{stationary_minutes:round(t.stationary_minutes)},recommended_actions:recommend('extended_stop')});
  if(p&&p.crossTrackKm>c.corridor_km)add({fingerprint:'truck:'+t.truck_id+':route_deviation',exception_type:'route_deviation',severity:p.crossTrackKm>c.corridor_km*2?'critical':'high',source:'derived',convoy_truck_id:t.truck_id,vehicle_id:t.vehicle_id,cfo_user_id:cfo,title:'Route deviation detected',detail:'Observed position is outside the convoy corridor.',context:{cross_track_km:round(p.crossTrackKm),corridor_km:c.corridor_km,along_km:round(p.alongKm)},recommended_actions:recommend('route_deviation')});
  if(!cfo)add({fingerprint:'truck:'+t.truck_id+':cfo_coverage_gap',exception_type:'cfo_coverage_gap',severity:'high',source:'derived',convoy_truck_id:t.truck_id,vehicle_id:t.vehicle_id,title:'No CFO coverage assigned',detail:'No active CFO-to-truck assignment exists.',context:{assignment_state:'missing'},recommended_actions:recommend('cfo_coverage_gap')});
  else if(!covered)add({fingerprint:'truck:'+t.truck_id+':cfo_coverage_gap',exception_type:'cfo_coverage_gap',severity:cfoDist!=null&&cfoDist>c.cfo_coverage_km*2?'critical':'high',source:'derived',convoy_truck_id:t.truck_id,vehicle_id:t.vehicle_id,cfo_user_id:cfo,title:shared.length>1?'CFO coverage conflict across assigned trucks':'CFO coverage gap',detail:cfoAge>c.cfo_stale_minutes?'CFO position is stale or unavailable.':'CFO is outside configured coverage radius.',context:{cfo_distance_km:round(cfoDist),cfo_fix_age_min:round(cfoAge),coverage_km:c.cfo_coverage_km,shared_cfo_count:shared.length,shared_cfo_conflict:shared.length>1},recommended_actions:recommend('cfo_coverage_gap')});
  if(p&&groupAlong!=null&&pos.length>2){const lag=groupAlong-p.alongKm,ahead=p.alongKm-groupAlong;if(lag>=c.lagging_km||(c.avg_speed_kmh>0&&lag/c.avg_speed_kmh*60>=c.lagging_minutes))add({fingerprint:'truck:'+t.truck_id+':lagging',exception_type:'truck_lagging',severity:lag>=c.lagging_km*2?'high':'medium',source:'derived',convoy_truck_id:t.truck_id,vehicle_id:t.vehicle_id,cfo_user_id:cfo,title:'Truck lagging behind convoy',detail:'Truck is materially behind the group progress reference.',context:{lag_km:round(lag),lag_minutes:round(c.avg_speed_kmh>0?lag/c.avg_speed_kmh*60:0)},recommended_actions:recommend('truck_lagging')});if(ahead>=c.ahead_km||(c.avg_speed_kmh>0&&ahead/c.avg_speed_kmh*60>=c.lagging_minutes))add({fingerprint:'truck:'+t.truck_id+':ahead',exception_type:'truck_ahead',severity:ahead>=c.ahead_km*2?'high':'medium',source:'derived',convoy_truck_id:t.truck_id,vehicle_id:t.vehicle_id,cfo_user_id:cfo,title:'Truck ahead of convoy group',detail:'Truck has materially outrun the group progress reference, creating a potential escort-coverage gap.',context:{ahead_km:round(ahead),ahead_minutes:round(c.avg_speed_kmh>0?ahead/c.avg_speed_kmh*60:0)},recommended_actions:recommend('truck_ahead')})}
  const gap=nearest.get(t.truck_id);if(gap!=null&&gap>=c.separation_km)add({fingerprint:'truck:'+t.truck_id+':separation',exception_type:'convoy_separation',severity:gap>=c.separation_km*2?'critical':'high',source:'derived',convoy_truck_id:t.truck_id,vehicle_id:t.vehicle_id,cfo_user_id:cfo,title:'Convoy separation detected',detail:'Truck is farther from its nearest positioned convoy member than the configured threshold.',context:{nearest_gap_km:round(gap),separation_threshold_km:c.separation_km,along_km:p?round(p.alongKm):null},recommended_actions:recommend('convoy_separation')});
 }
 const resource_conflicts=[];for(const e of out)for(const a of e.recommended_actions||[])if(a.resource_type&&a.available===false)resource_conflicts.push({resource_type:a.resource_type,exception_fingerprint:e.fingerprint,exception_type:e.exception_type,required_action:a.type,available:0});
 const posture=out.some(e=>e.severity==='critical')?'critical':out.some(e=>e.severity==='high')?'elevated':out.some(e=>e.severity==='medium')?'watch':'secure';
 const summary={truck_count:trucks.length,positioned_count:pos.length,unpositioned_count:trucks.length-pos.length,exception_count:out.length,critical_count:out.filter(e=>e.severity==='critical').length,high_count:out.filter(e=>e.severity==='high').length,medium_count:out.filter(e=>e.severity==='medium').length,lagging_truck_ids:out.filter(e=>e.exception_type==='truck_lagging').map(e=>e.convoy_truck_id),separated_truck_ids:out.filter(e=>e.exception_type==='convoy_separation').map(e=>e.convoy_truck_id),coverage_gap_truck_ids:out.filter(e=>e.exception_type==='cfo_coverage_gap').map(e=>e.convoy_truck_id),breakdown_truck_ids:out.filter(e=>e.exception_type==='vehicle_breakdown').map(e=>e.convoy_truck_id),group_reference_along_km:round(groupAlong),route_ready:routeReady,resource_conflict_count:resource_conflicts.length};
 return {version:'convoy-resilience-v1',generated_at:new Date(now).toISOString(),convoy_id:convoy.id||snapshot.convoy_id||null,posture,summary,exceptions:out,resource_conflicts,requires_human_decision:out.length>0,response_resources:rs};
}
async function loadSnapshot(db,convoyId,orgId,now=new Date()){
 const c=await db('SELECT id,org_id,name,status,departure_time,route_origin,route_destination,priority FROM convoys WHERE id=$1 AND org_id=$2 AND deleted_at IS NULL',[convoyId,orgId]);if(!c.rows.length){const e=new Error('Convoy not found');e.statusCode=404;throw e}
 const cr=await db('SELECT route_line FROM convoy_route_corridors WHERE convoy_id=$1 AND org_id=$2 AND active=true ORDER BY updated_at DESC LIMIT 1',[convoyId,orgId]);let route=[];if(cr.rows[0]?.route_line){try{const raw=typeof cr.rows[0].route_line==='string'?JSON.parse(cr.rows[0].route_line):cr.rows[0].route_line;if(Array.isArray(raw))route=raw.map(p=>({lat:Number(p?.lat),lng:Number(p?.lng)})).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lng))}catch(_){}}
 if(route.length<2){const w=await db('SELECT seq,lat,lng FROM convoy_route_waypoints WHERE convoy_id=$1 AND org_id=$2 ORDER BY seq',[convoyId,orgId]);route=w.rows.map(p=>({lat:Number(p.lat),lng:Number(p.lng)})).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lng))}
 const tr=await db('SELECT ct.id truck_id,ct.vehicle_id,ct.registration roster_registration,v.registration,v.latitude lat,v.longitude lng,v.last_ping,gp.speed speed_kmh,gp.timestamp gps_at,gm.timestamp last_moving_at,ccta.cfo_user_id,gd.last_lat cfo_lat,gd.last_lng cfo_lng,gd.last_seen cfo_last_seen_at FROM convoy_trucks ct LEFT JOIN vehicles v ON v.id=ct.vehicle_id AND v.org_id=$2 AND v.deleted_at IS NULL LEFT JOIN LATERAL(SELECT speed,timestamp FROM gps_logs WHERE vehicle_id=ct.vehicle_id ORDER BY timestamp DESC,id DESC LIMIT 1)gp ON true LEFT JOIN LATERAL(SELECT timestamp FROM gps_logs WHERE vehicle_id=ct.vehicle_id AND speed>3 ORDER BY timestamp DESC,id DESC LIMIT 1)gm ON true LEFT JOIN convoy_cfo_truck_assignments ccta ON ccta.convoy_truck_id=ct.id AND ccta.convoy_id=$1 LEFT JOIN convoy_cfos cc ON cc.convoy_id=$1 AND cc.cfo_user_id=ccta.cfo_user_id LEFT JOIN guardian_devices gd ON gd.id=cc.guardian_device_id AND gd.org_id=$2 AND gd.deleted_at IS NULL WHERE ct.convoy_id=$1 AND ct.org_id=$2 ORDER BY ct.position',[convoyId,orgId]);
 const alerts=await db('SELECT vehicle_id,type FROM alerts WHERE convoy_id=$1 AND org_id=$2 AND resolved_at IS NULL AND deleted_at IS NULL ORDER BY created_at DESC LIMIT 200',[convoyId,orgId]);
 const manual=await db("SELECT id,fingerprint,exception_type type,severity,title,detail,convoy_truck_id,vehicle_id,cfo_user_id,context FROM convoy_operational_exceptions WHERE convoy_id=$1 AND org_id=$2 AND status=ANY($3::text[]) AND source='operator' ORDER BY created_at DESC LIMIT 100",[convoyId,orgId,ACTIVE_EXCEPTION_STATUSES]);
 const resources=await db('SELECT id,name,type,status,active,eta_minutes,base_lat,base_lng FROM response_teams WHERE org_id=$1 AND active=true ORDER BY name',[orgId]);
 const byVehicle=new Map();for(const a of alerts.rows){if(!a.vehicle_id)continue;const k=String(a.vehicle_id);if(!byVehicle.has(k))byVehicle.set(k,[]);byVehicle.get(k).push(a)}
 const trucks=tr.rows.map(r=>{const speed=num(r.speed_kmh,0),stopped=r.last_moving_at?ageMinutes(r.last_moving_at,now.getTime()):0,va=byVehicle.get(String(r.vehicle_id||''))||[];return {...r,id:r.truck_id,registration:r.registration||r.roster_registration||null,lat:num(r.lat),lng:num(r.lng),speed_kmh:speed,last_fix_at:r.gps_at||r.last_ping||null,stationary_minutes:round(speed<=3?stopped:0),breakdown_signal:va.some(a=>a.type==='mechanical'),security_signal:va.some(a=>a.type==='security'),cfo_user_id:r.cfo_user_id||null,cfo_lat:num(r.cfo_lat),cfo_lng:num(r.cfo_lng),cfo_last_seen_at:r.cfo_last_seen_at||null}})
 return {now:now.toISOString(),convoy:c.rows[0],route,trucks,manual_signals:manual.rows.map(x=>({...x,context:x.context||{}})),response_resources:resources.rows};
}
async function persistEvaluation(db,orgId,e){
 await db('INSERT INTO convoy_operational_states(org_id,convoy_id,posture,summary,version,evaluated_at) VALUES($1,$2,$3,$4::jsonb,1,NOW()) ON CONFLICT(convoy_id) DO UPDATE SET posture=EXCLUDED.posture,summary=EXCLUDED.summary,version=convoy_operational_states.version+1,evaluated_at=NOW(),updated_at=NOW()',[orgId,e.convoy_id,e.posture,JSON.stringify(e.summary)]);
 const cur=await db('SELECT id,fingerprint,source FROM convoy_operational_exceptions WHERE convoy_id=$1 AND org_id=$2 AND status=ANY($3::text[])',[e.convoy_id,orgId,ACTIVE_EXCEPTION_STATUSES]),map=new Map(cur.rows.map(r=>[String(r.fingerprint),r])),seen=new Set();
 for(const x of e.exceptions){seen.add(x.fingerprint);const old=map.get(x.fingerprint);if(old)await db('UPDATE convoy_operational_exceptions SET severity=$1,exception_type=$2,title=$3,detail=$4,context=$5::jsonb,recommended_actions=$6::jsonb,last_seen_at=NOW(),updated_at=NOW() WHERE id=$7 AND org_id=$8',[x.severity,x.exception_type,x.title,x.detail,JSON.stringify(x.context||{}),JSON.stringify(x.recommended_actions||[]),old.id,orgId]);else await db('INSERT INTO convoy_operational_exceptions(org_id,convoy_id,convoy_truck_id,vehicle_id,cfo_user_id,exception_type,severity,status,source,fingerprint,title,detail,context,recommended_actions,first_seen_at,last_seen_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13::jsonb,$14::jsonb,NOW(),NOW())',[orgId,e.convoy_id,x.convoy_truck_id,x.vehicle_id,x.cfo_user_id,x.exception_type,x.severity,x.status,x.source,x.fingerprint,x.title,x.detail,JSON.stringify(x.context||{}),JSON.stringify(x.recommended_actions||[])])}
 for(const x of cur.rows)if(!seen.has(String(x.fingerprint))&&x.source!=='operator')await db("UPDATE convoy_operational_exceptions SET status='resolved',resolved_at=NOW(),resolution_note='Condition cleared by deterministic convoy resilience evaluation.',updated_at=NOW() WHERE id=$1 AND org_id=$2",[x.id,orgId]);
 return {persisted_at:new Date().toISOString()};
}
async function evaluateConvoyOperationalState(db,orgId,convoyId){const snapshot=await loadSnapshot(db,convoyId,orgId,new Date()),evaluation=evaluateConvoySnapshot(snapshot),persistence=await persistEvaluation(db,orgId,evaluation);publish('org#'+orgId,{type:'convoy.operational',convoyId,posture:evaluation.posture,summary:evaluation.summary,exceptions:evaluation.exceptions.map(e=>({fingerprint:e.fingerprint,type:e.exception_type,severity:e.severity,truck_id:e.convoy_truck_id})),resource_conflicts:evaluation.resource_conflicts,generated_at:evaluation.generated_at});publish('portal#'+convoyId,{type:'convoy.operational',convoyId,posture:evaluation.posture,exception_count:evaluation.summary.exception_count,critical_count:evaluation.summary.critical_count,high_count:evaluation.summary.high_count,generated_at:evaluation.generated_at});return {snapshot,evaluation,persistence}}
module.exports={ACTIVE_EXCEPTION_STATUSES,TERMINAL_EXCEPTION_STATUSES,DEFAULTS,SCENARIOS,resolveConfig,evaluateConvoySnapshot,loadSnapshot,persistEvaluation,evaluateConvoyOperationalState};
