const PDFDocument = require('pdfkit');
const sharp = require('sharp');
const { PutObjectCommand, GetObjectCommand, S3Client } = require('@aws-sdk/client-s3');
const { getSignedUrl } = require('@aws-sdk/s3-request-presigner');
const { query } = require('../config/database');
const logger = require('../utils/logger');

const COUNTRY_NAMES = { KE:'Kenya', SO:'Somalia', ET:'Ethiopia', UG:'Uganda', TZ:'Tanzania', RW:'Rwanda', BI:'Burundi', SS:'South Sudan', DJ:'Djibouti', ER:'Eritrea', SD:'Sudan', CD:'DR Congo' };
const BOUNDS = {
  KE:[33.8,-4.8,41.9,4.7], TZ:[29.3,-11.8,40.5,-0.9], UG:[29.5,-1.5,35.1,4.3], RW:[28.8,-2.9,30.9,-1.0], BI:[28.9,-4.5,30.9,-2.3], SO:[40.9,-1.9,51.5,12.2], ET:[32.9,3.3,47.9,14.9], SS:[23.4,3.4,35.9,12.2], DJ:[41.6,10.9,43.5,13.1], ER:[36.4,12.3,43.2,18.0], SD:[21.8,8.7,38.1,22.2], CD:[12.1,-13.5,31.3,5.4]
};

function esc(v){return String(v ?? '').replace(/[&<>\"]/g, s=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[s]||s));}
function severityScore(v){return ({critical:4,high:3,moderate:2,low:1,informational:0}[String(v||'').toLowerCase()] ?? 2);}
function svgMap(country, events){
  const [minLon,minLat,maxLon,maxLat]=BOUNDS[country]||[20,-20,55,20];
  const W=1200,H=720,pad=70;
  const x=lon=>pad+((lon-minLon)/(maxLon-minLon))*(W-pad*2);
  const y=lat=>H-pad-((lat-minLat)/(maxLat-minLat))*(H-pad*2);
  const dots=events.filter(e=>Number.isFinite(Number(e.longitude))&&Number.isFinite(Number(e.latitude))).slice(0,80).map(e=>{
    const r=4+severityScore(e.severity)*2; const c={critical:'#ef4444',high:'#f97316',moderate:'#f59e0b',low:'#38bdf8',informational:'#94a3b8'}[String(e.severity||'moderate').toLowerCase()]||'#f59e0b';
    return `<circle cx="${x(Number(e.longitude)).toFixed(1)}" cy="${y(Number(e.latitude)).toFixed(1)}" r="${r}" fill="${c}" opacity=".9"><title>${esc(e.headline||e.title||'Event')}</title></circle>`;
  }).join('');
  const graticule=[]; for(let i=0;i<=6;i++){const yy=pad+i*((H-pad*2)/6);graticule.push(`<line x1="${pad}" y1="${yy}" x2="${W-pad}" y2="${yy}" stroke="#334155" stroke-width="1" opacity=".5"/>`)}
  for(let i=0;i<=8;i++){const xx=pad+i*((W-pad*2)/8);graticule.push(`<line x1="${xx}" y1="${pad}" x2="${xx}" y2="${H-pad}" stroke="#334155" stroke-width="1" opacity=".5"/>`)}
  return Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}"><rect width="${W}" height="${H}" fill="#0b1220"/><rect x="${pad}" y="${pad}" width="${W-pad*2}" height="${H-pad*2}" rx="18" fill="#0f172a" stroke="#475569" stroke-width="2"/>${graticule.join('')}<text x="${pad}" y="38" fill="#f8fafc" font-family="Arial" font-size="26" font-weight="700">${esc(COUNTRY_NAMES[country]||country)} SECURITY EVENT MAP</text><text x="${pad}" y="62" fill="#94a3b8" font-family="Arial" font-size="14">Geospatial intelligence plot · event coordinates from Sonalit evidence ledger</text>${dots}</svg>`);
}

async function buildPdf(publication, events, images){
  const doc=new PDFDocument({size:'A4',margin:42,info:{Title:publication.title,Author:'SONALIT INTELLIGENCE',Subject:'Security intelligence report'}});
  const chunks=[]; doc.on('data',c=>chunks.push(c)); const done=new Promise((resolve,reject)=>{doc.on('end',()=>resolve(Buffer.concat(chunks)));doc.on('error',reject)});
  const country=publication.country_code; const name=COUNTRY_NAMES[country]||country;
  const navy='#0b1220', orange='#f97316', muted='#64748b', ink='#0f172a', line='#e2e8f0';
  const pageHeader=()=>{doc.font('Helvetica-Bold').fontSize(8).fillColor(muted).text('SONALIT  /  INTELLIGENCE & SECURITY OPERATIONS',42,24,{characterSpacing:1.1});doc.moveTo(42,36).lineTo(553,36).strokeColor(line).stroke();};
  const footer=()=>{doc.font('Helvetica').fontSize(7).fillColor(muted).text('Evidence-governed product · Generated by Sonalit publication pipeline',42,800,{width:400});doc.text(String(doc.page),515,800,{align:'right'});};
  pageHeader();
  doc.rect(42,58,511,180).fill(navy); doc.fillColor('#fff').font('Helvetica-Bold').fontSize(10).text('SONALIT INTELLIGENCE',64,80,{characterSpacing:1.3});
  doc.fillColor('#fff').font('Helvetica-Bold').fontSize(24).text(name.toUpperCase(),64,112,{width:430}); doc.fillColor('#e2e8f0').font('Helvetica').fontSize(13).text(`${String(publication.publication_type||'daily').toUpperCase()} SECURITY INTELLIGENCE REPORT`,64,151,{width:430});
  doc.fillColor('#cbd5e1').fontSize(9).text(`${new Date(publication.period_start).toLocaleDateString('en-GB')} — ${new Date(publication.period_end).toLocaleDateString('en-GB')}`,64,190); doc.fillColor(orange).font('Helvetica-Bold').fontSize(8).text('CONFIDENTIAL • CONTROLLED DISTRIBUTION',64,213,{characterSpacing:1});
  doc.addPage(); pageHeader();
  doc.fillColor(ink).font('Helvetica-Bold').fontSize(18).text('EXECUTIVE ASSESSMENT',42,60); doc.moveTo(42,86).lineTo(553,86).strokeColor(line).stroke();
  doc.font('Helvetica').fontSize(10).fillColor(ink).text(publication.executive_assessment||'No executive assessment supplied.',42,105,{width:511,lineGap:4});
  const metrics=[['EVENTS',events.length],['SOURCES',new Set(events.flatMap(e=>e.source_ids||[]).filter(Boolean)).size||'—'],['EVIDENCE',events.reduce((n,e)=>n+Number(e.observation_count||0),0)],['CONFIDENCE',publication.confidence!=null?`${Math.round(Number(publication.confidence))}%`:'—']];
  metrics.forEach((m,i)=>{const xx=42+i*128;doc.roundedRect(xx,205,116,62,8).fill('#f8fafc');doc.fillColor(muted).font('Helvetica-Bold').fontSize(7).text(m[0],xx+10,217);doc.fillColor(ink).font('Helvetica-Bold').fontSize(19).text(String(m[1]),xx+10,235)});
  doc.fillColor(ink).font('Helvetica-Bold').fontSize(14).text('SECURITY POSTURE',42,302);
  const counts=events.reduce((a,e)=>{const k=String(e.severity||'moderate').toLowerCase();a[k]=(a[k]||0)+1;return a},{});
  ['critical','high','moderate','low','informational'].forEach((s,i)=>{const y=330+i*28;doc.fillColor(muted).font('Helvetica').fontSize(8).text(s.toUpperCase(),42,y);doc.roundedRect(110,y-2,330,12,5).fill('#eef2f7');const w=Math.min(330,(counts[s]||0)/Math.max(1,events.length)*330);doc.roundedRect(110,y-2,w,12,5).fill({critical:'#ef4444',high:orange,moderate:'#f59e0b',low:'#38bdf8',informational:'#94a3b8'}[s]);doc.fillColor(ink).font('Helvetica-Bold').fontSize(8).text(String(counts[s]||0),450,y);});
  footer();

  doc.addPage(); pageHeader(); doc.fillColor(ink).font('Helvetica-Bold').fontSize(17).text('GEOSPATIAL SECURITY LANDSCAPE',42,58);
  const map=await sharp(svgMap(country,events)).png().toBuffer(); doc.image(map,42,85,{width:511});
  doc.fillColor(muted).font('Helvetica').fontSize(7).text('Map is generated from Sonalit event coordinates. Where precise coordinates are unavailable, events are not plotted.',42,645,{width:511}); footer();

  const sections=(publication.body&&publication.body.sections)||{}; const sectionNames=[['SECURITY ENVIRONMENT','security_environment'],['POLITICAL & GOVERNANCE','political_developments'],['CRIME & PUBLIC SAFETY','crime_and_public_safety'],['BORDER & TRANSPORT','border_and_transport'],['NATURAL HAZARDS','natural_hazards'],['OPERATIONAL IMPLICATIONS','operational_implications']];
  for(const [label,key] of sectionNames){doc.addPage();pageHeader();doc.fillColor(ink).font('Helvetica-Bold').fontSize(17).text(label,42,58);const val=sections[key];const text=Array.isArray(val)?val.map(x=>typeof x==='string'?x:JSON.stringify(x)).join('\n\n'):String(val||'No material update identified in the reporting period.');doc.font('Helvetica').fontSize(9.5).fillColor(ink).text(text,42,92,{width:511,lineGap:5});
    if(key==='operational_implications'&&events.length){doc.moveDown(1);doc.font('Helvetica-Bold').fontSize(12).text('KEY EVENTS');events.sort((a,b)=>severityScore(b.severity)-severityScore(a.severity)||new Date(b.last_seen_at||0)-new Date(a.last_seen_at||0)).slice(0,8).forEach((e,i)=>{doc.moveDown(.5);doc.font('Helvetica-Bold').fontSize(9).text(`${i+1}. ${e.headline||e.title||'Security event'}`);doc.font('Helvetica').fontSize(8.5).fillColor(muted).text(`${String(e.severity||'moderate').toUpperCase()} · ${e.intelligence_type||'OTHER'} · ${e.observation_count||0} evidence items · ${e.source_count||0} sources`);doc.fillColor(ink).text(e.brief||e.summary||'');});}}
    footer();
  if(images.length){doc.addPage();pageHeader();doc.fillColor(ink).font('Helvetica-Bold').fontSize(17).text('VISUAL INTELLIGENCE',42,58);let y=92;for(const img of images.slice(0,4)){try{doc.image(img.buffer,42,y,{width:245,height:160,fit:[245,160]});doc.font('Helvetica-Bold').fontSize(8).fillColor(ink).text(img.label||'Source image',300,y+10,{width:235});doc.font('Helvetica').fontSize(7).fillColor(muted).text(img.source_url||'Provenance unavailable',300,y+28,{width:235});y+=185;if(y>640){footer();doc.addPage();pageHeader();y=70;}}catch(error){logger.warn(`Could not embed publication image: ${error.message}`)}}}
  doc.addPage();pageHeader();doc.fillColor(ink).font('Helvetica-Bold').fontSize(17).text('OUTLOOK & COLLECTION GAPS',42,58);doc.font('Helvetica').fontSize(9.5).fillColor(ink).text(JSON.stringify(publication.body?.outlook||[],null,2),42,92,{width:511,lineGap:5});doc.moveDown();doc.font('Helvetica-Bold').fontSize(12).text('EVIDENCE CONTRACT');doc.font('Helvetica').fontSize(9).text(publication.body?.collection_coverage?.evidence_contract_met?'Threshold met for automated publication.':'Threshold not met; analyst review remains required.');doc.moveDown();doc.font('Helvetica-Bold').fontSize(12).text('SOURCES / PROVENANCE');doc.font('Helvetica').fontSize(8).text(`Publication ID: ${publication.id}`);doc.text(`Generator: ${publication.body?.generator?.name||'SONALIT PUBLICATION AGENT'}`);doc.text(`Generator provider: ${publication.body?.generator?.provider||'unknown'}`);footer();doc.end();return done;}

async function getR2Client(){const {R2_ACCOUNT_ID,R2_ACCESS_KEY,R2_SECRET_KEY}=process.env;if(!(R2_ACCOUNT_ID&&R2_ACCESS_KEY&&R2_SECRET_KEY))return null;return new S3Client({region:'auto',endpoint:`https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com`,credentials:{accessKeyId:R2_ACCESS_KEY,secretAccessKey:R2_SECRET_KEY}})}
async function fetchImages(rows){const out=[];for(const row of rows){const url=row.raw_metadata?.image_url||row.raw_metadata?.imageUrl||row.raw_metadata?.thumbnail_url||row.raw_metadata?.thumbnailUrl;if(!url||!/^https?:\/\//i.test(url))continue;try{const r=await fetch(url,{redirect:'follow'});if(!r.ok)continue;const b=Buffer.from(await r.arrayBuffer());if(!b.length||b.length>5*1024*1024)continue;out.push({buffer:b,label:row.title||'Source image',source_url:row.url||url});if(out.length>=4)break;}catch(error){logger.warn(`Image fetch failed: ${error.message}`)}}return out;}

async function renderAndStorePublicationPdf(orgId, publicationId){
  const {rows:[publication]}=await query('SELECT * FROM intel_publications WHERE id=$1 AND org_id=$2 LIMIT 1',[publicationId,orgId]);
  if(!publication)throw new Error('Publication not found');
  if(publication.status!=='published')return{status:'skipped',reason:'publication_not_published'};
  await query("UPDATE intel_publications SET pdf_status='generating',pdf_error=NULL WHERE id=$1 AND org_id=$2",[publicationId,orgId]);
  try{
    const {rows:events}=await query(`SELECT e.id,COALESCE(e.canonical_headline,e.title) AS headline,COALESCE(e.executive_brief,e.summary) AS brief,e.summary,e.title,e.severity,e.confidence,e.intelligence_type,e.latitude,e.longitude,e.last_seen_at,COUNT(DISTINCT eo.observation_id)::int AS observation_count,COUNT(DISTINCT o.source_id)::int AS source_count,array_agg(DISTINCT o.source_id) FILTER (WHERE o.source_id IS NOT NULL) AS source_ids,array_agg(DISTINCT jsonb_build_object('id',o.id,'title',o.title,'url',o.url,'raw_metadata',o.raw_metadata)) FILTER (WHERE o.id IS NOT NULL) AS observations FROM intel_events e LEFT JOIN intel_event_observations eo ON eo.event_id=e.id LEFT JOIN intel_observations o ON o.id=eo.observation_id WHERE e.org_id=$1 AND e.country_code=$2 AND e.last_seen_at>=$3 AND e.last_seen_at<$4 GROUP BY e.id ORDER BY e.last_seen_at DESC LIMIT 120`,[orgId,publication.country_code,publication.period_start,publication.period_end]);
    const observationRows=[];for(const e of events){for(const o of e.observations||[])observationRows.push(o)}
    const images=await fetchImages(observationRows); const pdf=await buildPdf(publication,events,images);
    const r2=await getR2Client(); if(!r2)throw new Error('R2 not configured'); const bucket=process.env.R2_BUCKET; if(!bucket)throw new Error('R2_BUCKET not configured');
    const safe=`${publication.country_code}-${publication.publication_type}-${new Date(publication.period_start).toISOString().slice(0,10)}`.replace(/[^A-Z0-9._-]/gi,'-');const key=`intelligence-publications/${orgId}/${safe}-v${publication.pdf_version||1}.pdf`;
    await r2.send(new PutObjectCommand({Bucket:bucket,Key:key,Body:pdf,ContentType:'application/pdf',CacheControl:'private, max-age=0'}));
    const publicBase=(process.env.R2_PUBLIC_URL||'').replace(/\/$/,''); const pdfUrl=publicBase?`${publicBase}/${key}`:null;
    await query("UPDATE intel_publications SET pdf_status='ready',pdf_key=$3,pdf_url=$4,pdf_generated_at=NOW(),pdf_error=NULL,updated_at=NOW() WHERE id=$1 AND org_id=$2",[publicationId,orgId,key,pdfUrl]);
    for(const img of images)await query('INSERT INTO intel_publication_pdf_assets (org_id,publication_id,asset_type,source_url,source_label,provenance) VALUES ($1,$2,$3,$4,$5,$6::jsonb)',[orgId,publicationId,'image',img.source_url,img.label,JSON.stringify({embedded:true})]).catch(()=>{});
    return{status:'ready',publication_id:publicationId,pdf_url:pdfUrl,key};
  }catch(error){await query("UPDATE intel_publications SET pdf_status='failed',pdf_error=$3 WHERE id=$1 AND org_id=$2",[publicationId,orgId,String(error.message||error).slice(0,2000)]).catch(()=>{});throw error;}
}

async function getPublicationPdfAccessUrl(orgId,publicationId){
  const {rows:[row]}=await query('SELECT pdf_key FROM intel_publications WHERE id=$1 AND org_id=$2 AND status=\'published\' AND pdf_status=\'ready\' LIMIT 1',[publicationId,orgId]);
  if(!row?.pdf_key)throw new Error('Publication PDF is not ready');
  const r2=await getR2Client(); if(!r2)throw new Error('R2 not configured');
  const bucket=process.env.R2_BUCKET; if(!bucket)throw new Error('R2_BUCKET not configured');
  return getSignedUrl(r2,new GetObjectCommand({Bucket:bucket,Key:row.pdf_key}),{expiresIn:300});
}

async function generateMissingPublicationPdfs(orgId,limit=3){const {rows}=await query("SELECT id FROM intel_publications WHERE org_id=$1 AND status='published' AND (pdf_status='not_requested' OR pdf_status IS NULL OR (pdf_status='failed' AND updated_at < NOW()-INTERVAL '30 minutes')) ORDER BY published_at DESC NULLS LAST LIMIT $2",[orgId,limit]);const out=[];for(const r of rows){try{out.push(await renderAndStorePublicationPdf(orgId,r.id))}catch(error){out.push({status:'failed',publication_id:r.id,error:error.message})}}return out;}
module.exports={renderAndStorePublicationPdf,generateMissingPublicationPdfs,getPublicationPdfAccessUrl};
