require("dotenv").config();
const express=require("express"),http=require("http"),{Server}=require("socket.io"),helmet=require("helmet"),cors=require("cors"),rateLimit=require("express-rate-limit"),morgan=require("morgan"),jwt=require("jsonwebtoken");
const logger=require("./utils/logger"),{errorHandler}=require("./middleware/error"),{setIO:gpsSetIO}=require("./workers/gpsWorker"),{setIO:alertSetIO}=require("./workers/alertWorker"),{createQueues}=require("./config/queue"),{healthCheck:dbHealth}=require("./config/database"),{healthCheck:redisHealth}=require("./config/redis");
const app=express(),server=http.createServer(app),io=new Server(server,{cors:{origin:true,credentials:true}});
io.on("connection",s=>{s.on("subscribe:region",r=>s.join("region:"+r));s.on("subscribe:convoy",id=>s.join("convoy:"+id));});
app.set("io",io);gpsSetIO(io);alertSetIO(io);
app.use(helmet({contentSecurityPolicy:false}));
app.use(cors({origin:true,credentials:true}));
app.use(express.json({limit:"2mb"}));
app.use(express.urlencoded({extended:true}));
app.use(morgan("tiny",{stream:{write:m=>logger.info(m.trim())}}));
app.use(rateLimit({windowMs:900000,max:300,standardHeaders:true,legacyHeaders:false,validate:{xForwardedForHeader:false}}));
app.get("/health",async(req,res)=>{try{const[db,redis]=await Promise.all([dbHealth(),redisHealth()]);res.json({status:"ok",database:db?"ok":"error",redis,uptime:Math.floor(process.uptime())});}catch(e){res.status(503).json({error:e.message});}});
app.get("/metrics",(req,res)=>{res.set("Content-Type","text/plain");res.send("process_uptime_seconds "+Math.floor(process.uptime()));});
["auth","vehicles","convoys","alerts","messages","analytics","geofences","devices","incidents","rules","gps","sensors","ai","apikeys","reports","documents","webhooks"].forEach(r=>app.use("/api/v1/"+r,require("./routes/"+r)));
app.use((req,res)=>res.status(404).json({error:"not found"}));
app.use(errorHandler);
const PORT=parseInt(process.env.PORT)||5000;
createQueues();
server.listen(PORT,()=>logger.info("FleetOps v2 port "+PORT));
process.on("SIGTERM",()=>server.close(()=>process.exit(0)));
process.on("SIGINT",()=>server.close(()=>process.exit(0)));
module.exports={app,server,io};
