const router = require('express').Router();
const { authenticate } = require('../middleware/auth');
const { attachOrgDb } = require('../utils/orgScopedDb');
const { asyncHandler } = require('../middleware/error');
const { buildAssessment } = require('../utils/intelligenceEngine');
const { translatePayload } = require('../utils/intelligenceTranslation');
const operationsRouter = require('./intelligenceOperations');

router.use(authenticate);
router.use(attachOrgDb);
function adminWrite(req,res,next){if(!['admin','super_admin'].includes(req.user.role))return res.status(403).json({error:'Administrator role required for this action'});next();}

router.use((req,res,next)=>{
  const originalJson=res.json.bind(res);
  res.json=async payload=>{
    try{
      if(req.path==='/events'||req.path==='/observations'||req.path==='/events/'||req.path==='/observations/'||/^\/events\/[^/]+$/.test(req.path))payload=await translatePayload(payload);
    }catch(_err){}
    return originalJson(payload);
  };
  next();
});

router.use('/', operationsRouter);
router.use('/ops', operationsRouter);

router.get('/picture',asyncHandler(async(req,res)=>{const {rows:events}=await req.db(`SELECT * FROM intel_events WHERE org_id=$1 AND last_seen_at>=now()-interval '7 days' ORDER BY last_seen_at DESC LIMIT 500`,[req.user.org_id]);const {rows:observations}=await req.db(`SELECT io.*,s.reliability,s.name AS source_name FROM intel_observations io LEFT JOIN intel_sources s ON s.id=io.source_id WHERE io.org_id=$1 AND io.observed_at>=now()-interval '7 days' ORDER BY io.observed_at DESC LIMIT 1000`,[req.user.org_id]);const assessment=buildAssessment({scope:'global',events,observations});const {rows:countries}=await req.db(`SELECT country_code,COUNT(*)::int AS events,ROUND(AVG(confidence))::int AS confidence FROM intel_events WHERE org_id=$1 AND country_code IS NOT NULL AND intel_country_evidence_ok(country_code,CONCAT_WS(' ',title,summary)) AND last_seen_at>=now()-interval '24 hours' GROUP BY country_code ORDER BY events DESC LIMIT 20`,[req.user.org_id]);res.json({picture:{...assessment,countries},generated_at:new Date().toISOString()});}));
router.get('/countries',asyncHandler(async(req,res)=>{const {rows}=await req.db(`SELECT country_code,COUNT(*) FILTER(WHERE last_seen_at>=now()-interval '24 hours')::int AS events_24h,COUNT(*) FILTER(WHERE last_seen_at>=now()-interval '7 days')::int AS events_7d,ROUND(AVG(confidence))::int AS confidence,MAX(last_seen_at) AS last_seen_at,MAX(CASE severity WHEN 'critical' THEN 4 WHEN 'high' THEN 3 WHEN 'moderate' THEN 2 WHEN 'low' THEN 1 ELSE 0 END) AS severity_rank FROM intel_events WHERE org_id=$1 AND country_code IS NOT NULL AND intel_country_evidence_ok(country_code,CONCAT_WS(' ',title,summary)) GROUP BY country_code ORDER BY severity_rank DESC,events_24h DESC`,[req.user.org_id]);res.json({countries:rows});}));
router.get('/countries/:country/publications',asyncHandler(async(req,res)=>{const {rows}=await req.db(`SELECT * FROM intel_publications WHERE org_id=$1 AND country_code=$2 ORDER BY period_end DESC NULLS LAST,created_at DESC LIMIT 100`,[req.user.org_id,req.params.country.toUpperCase()]);res.json({publications:rows});}));
router.get('/countries/:country/assessment',asyncHandler(async(req,res)=>{const country=req.params.country.toUpperCase();const {rows:events}=await req.db(`SELECT * FROM intel_events WHERE org_id=$1 AND country_code=$2 AND intel_country_evidence_ok(country_code,CONCAT_WS(' ',title,summary)) AND last_seen_at>=now()-interval '7 days' ORDER BY last_seen_at DESC LIMIT 300`,[req.user.org_id,country]);const {rows:observations}=await req.db(`SELECT io.*,s.reliability FROM intel_observations io LEFT JOIN intel_sources s ON s.id=io.source_id WHERE io.org_id=$1 AND io.country_code=$2 AND intel_country_evidence_ok(io.country_code,CONCAT_WS(' ',io.title,io.body)) AND io.observed_at>=now()-interval '7 days' ORDER BY io.observed_at DESC LIMIT 500`,[req.user.org_id,country]);res.json({country,assessment:buildAssessment({scope:{type:'country',country},events,observations})});}));
router.get('/early-warnings/:id/actions',asyncHandler(async(req,res)=>{const {getWarningActions}=require('../utils/intelligenceAdvancedRuntime');const actions=await getWarningActions(req.user.org_id,req.params.id);res.json({actions,generated_at:new Date().toISOString()});}));
router.post('/early-warnings/:id/transition',adminWrite,asyncHandler(async(req,res)=>{const {transitionWarning}=require('../utils/intelligenceAdvancedRuntime');const {status,notes,disposition,reasoning}=req.body||{};if(!status)return res.status(400).json({error:'status is required'});const result=await transitionWarning(req.user.org_id,req.params.id,status,req.user.id,notes,disposition,reasoning);res.json({transition:result});}));
router.get('/trajectories',asyncHandler(async(req,res)=>{const {getRiskTrajectories}=require('../utils/intelligenceAdvancedRuntime');const scopeType=String(req.query.scope_type||'country');const scopeKey=req.query.scope_key?String(req.query.scope_key).toUpperCase():null;const trajectories=await getRiskTrajectories(req.user.org_id,scopeType,scopeKey,req.query.limit);res.json({trajectories,generated_at:new Date().toISOString()});}));
router.get('/exposures',asyncHandler(async(req,res)=>{const country=req.query.country_code?String(req.query.country_code).toUpperCase():null;const {rows}=await req.db(`SELECT x.*,w.warning_type,w.headline,w.severity,w.confidence,w.scope_key FROM intel_warning_exposures x JOIN intel_early_warnings w ON w.id=x.warning_id WHERE x.org_id=$1 AND w.org_id=$1 AND ($2::text IS NULL OR w.scope_key=$2) ORDER BY x.exposure_score DESC,x.detected_at DESC LIMIT 300`,[req.user.org_id,country]);res.json({exposures:rows,generated_at:new Date().toISOString()});}));
router.get('/event-links',asyncHandler(async(req,res)=>{const eventId=req.query.event_id||null;const {rows}=await req.db(`SELECT l.*,a.title AS from_title,b.title AS to_title,a.country_code FROM intel_event_links l JOIN intel_events a ON a.id=l.from_event_id JOIN intel_events b ON b.id=l.to_event_id WHERE a.org_id=$2 AND b.org_id=$2 AND ($1::uuid IS NULL OR l.from_event_id=$1 OR l.to_event_id=$1) ORDER BY l.created_at DESC LIMIT 500`,[eventId,req.user.org_id]);res.json({links:rows});}));
router.get('/fusion/status',asyncHandler(async(req,res)=>{const {rows:[stats]}=await req.db(`SELECT COUNT(*)::int AS events,COUNT(*) FILTER(WHERE last_seen_at>=now()-interval '24 hours')::int AS events_24h,COUNT(DISTINCT country_code)::int AS countries,COUNT(DISTINCT source_id)::int AS sources,COUNT(*) FILTER(WHERE manipulation_score>=40)::int AS manipulation_flagged FROM intel_observations WHERE org_id=$1 AND observed_at>=now()-interval '48 hours'`,[req.user.org_id]);const {rows:[links]}=await req.db(`SELECT COUNT(*)::int AS links,COUNT(*) FILTER(WHERE relationship='spatial_cluster')::int AS spatial_clusters,COUNT(*) FILTER(WHERE relationship='same_story')::int AS same_story FROM intel_event_links l JOIN intel_events a ON a.id=l.from_event_id JOIN intel_events b ON b.id=l.to_event_id WHERE a.org_id=$1 AND b.org_id=$1 AND l.created_at>=now()-interval '48 hours'`,[req.user.org_id]);res.json({fusion:{...stats,...links,checked_at:new Date().toISOString()}});}));
router.get('/collection/status',asyncHandler(async(req,res)=>{const {rows:sources}=await req.db(`SELECT id,name,source_type,provider,reliability,active,last_seen_at,updated_at FROM intel_sources WHERE org_id=$1 ORDER BY last_seen_at DESC NULLS LAST`,[req.user.org_id]);const {rows:runs}=await req.db(`SELECT r.source_id,r.status,r.started_at,r.finished_at,r.observations_seen,r.observations_inserted,r.observations_duplicate,r.error_count,r.error_message,r.metadata FROM intel_collection_runs r JOIN (SELECT source_id,MAX(started_at) AS started_at FROM intel_collection_runs WHERE org_id=$1 GROUP BY source_id) latest ON latest.source_id=r.source_id AND latest.started_at=r.started_at WHERE r.org_id=$1 ORDER BY r.started_at DESC`,[req.user.org_id]);const runMap=new Map(runs.map(r=>[String(r.source_id),r]));const {rows:totals}=await req.db(`SELECT source_id,COUNT(*) FILTER(WHERE observed_at>=now()-interval '24 hours')::int AS observations_24h,COUNT(*)::int AS observations_total,MAX(observed_at) AS latest_observation FROM intel_observations WHERE org_id=$1 GROUP BY source_id`,[req.user.org_id]);const totalMap=new Map(totals.map(r=>[String(r.source_id),r]));res.json({collection:{sources:sources.map(s=>({...s,health:runMap.get(String(s.id))||null,metrics:totalMap.get(String(s.id))||{observations_24h:0,observations_total:0,latest_observation:null}})),checked_at:new Date().toISOString()}});}));
router.post('/collection/run',adminWrite,asyncHandler(async(_req,res)=>{const {runCollection}=require('../utils/intelligenceCollectionBootstrap');const result=await runCollection();res.status(result?.skipped?202:200).json({collection:result});}));
router.post('/requirements',adminWrite,asyncHandler(async(req,res)=>{const {reference,title,question,priority,scope,due_at}=req.body;if(!title||!question)return res.status(400).json({error:'title and question are required'});const ref=reference||`ICR-${Date.now().toString(36).toUpperCase()}`;const {rows}=await req.db(`INSERT INTO intel_requirements (org_id,reference,title,question,priority,scope,due_at,created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[req.user.org_id,ref,title,question,priority||'medium',scope||{},due_at||null,req.user.id]);res.status(201).json({requirement:rows[0]});}));
router.post('/advisories/draft',adminWrite,asyncHandler(async(req,res)=>{const country=String(req.body.country_code||'').toUpperCase();if(!country)return res.status(400).json({error:'country_code is required'});const profile=req.body.traveller_profile||'general';const destination=req.body.destination||null;const {rows:events}=await req.db(`SELECT id,title,summary,severity,confidence,last_seen_at,latitude,longitude FROM intel_events WHERE org_id=$1 AND country_code=$2 AND intel_country_evidence_ok(country_code,CONCAT_WS(' ',title,summary)) AND last_seen_at>=now()-interval '7 days' ORDER BY last_seen_at DESC LIMIT 100`,[req.user.org_id,country]);const {rows:assessments}=await req.db(`SELECT headline,judgement,severity,confidence,evidence,validity_start,validity_end FROM intel_assessments WHERE org_id=$1 AND scope_type='country' AND scope_key=$2 ORDER BY validity_start DESC LIMIT 10`,[req.user.org_id,country]);const severityRank={critical:4,high:3,moderate:2,low:1,informational:0};const top=events.reduce((a,e)=>severityRank[e.severity]>severityRank[a]?e.severity:a,'informational');const advisoryLevel=top==='critical'?'avoid':top==='high'?'reconsider':top==='moderate'?'caution':'normal';const confidence=assessments[0]?.confidence||Math.round(events.reduce((s,e)=>s+Number(e.confidence||0),0)/Math.max(events.length,1));const content={executive_summary:`Draft generated from Sonalit intelligence evidence for ${country}.`,traveller_profile:profile,destination,threat_environment:assessments,key_events:events,sections:['security_environment','areas_of_concern','transport','civil_unrest','crime','terrorism','natural_hazards','recommended_posture','emergency_considerations'],evidence_policy:'Every substantive claim must resolve to an observation or verified assessment before publication.'};const {rows}=await req.db(`INSERT INTO intel_advisories (org_id,country_code,destination,traveller_profile,advisory_level,confidence,valid_until,content,evidence,created_by) VALUES ($1,$2,$3,$4,$5,$6,now()+interval '24 hours',$7,$8,$9) RETURNING *`,[req.user.org_id,country,destination,profile,advisoryLevel,confidence,content,events.map(e=>e.id),req.user.id]);res.status(201).json({advisory:rows[0]});}));
router.get('/advisories',asyncHandler(async(req,res)=>{const country=req.query.country_code?String(req.query.country_code).toUpperCase():null;const {rows}=await req.db(`SELECT * FROM intel_advisories WHERE org_id=$1 AND ($2::text IS NULL OR country_code=$2) ORDER BY created_at DESC LIMIT 100`,[req.user.org_id,country]);res.json({advisories:rows});}));
module.exports=router;
