const router = require('express').Router();
const { asyncHandler } = require('../middleware/error');
const { normaliseScope, countryClause, scopedObjectClause, watchlistClause, REGIONS, AFRICA } = require('../utils/intelligenceScope');
const priorityRank = `CASE priority WHEN 'critical' THEN 1 WHEN 'high' THEN 2 WHEN 'medium' THEN 3 ELSE 4 END`;
const scope = req => normaliseScope(req);

router.get('/gaps', asyncHandler(async (req,res)=>{const status=req.query.status||null,s=scope(req),geo=scopedObjectClause(s,'g',2);const {rows}=await req.db(`SELECT g.* FROM intel_gaps g WHERE g.org_id=$1 AND ($2::text IS NULL OR g.status=$2) AND ${geo.clause} ORDER BY ${priorityRank},g.created_at DESC LIMIT 300`,[req.user.org_id,status,...geo.params]);res.json({gaps:rows,scope:s,generated_at:new Date().toISOString()});}));
router.post('/gaps', asyncHandler(async(req,res)=>{const {gap_type,title,description,scope_type,scope_key,priority,recommended_action,evidence,due_at}=req.body||{};if(!gap_type||!title||!scope_type)return res.status(400).json({error:'gap_type, title and scope_type are required'});const {rows}=await req.db(`INSERT INTO intel_gaps (org_id,gap_type,title,description,scope_type,scope_key,priority,recommended_action,evidence,due_at,created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[req.user.org_id,gap_type,title,description||null,scope_type,scope_key||null,priority||'medium',recommended_action||null,evidence||[],due_at||null,req.user.id]);res.status(201).json({gap:rows[0]});}));
router.patch('/gaps/:id', asyncHandler(async(req,res)=>{const allowed=['title','description','priority','status','recommended_action','evidence','due_at'];const sets=[],vals=[];for(const f of allowed)if(Object.prototype.hasOwnProperty.call(req.body||{},f)){vals.push(req.body[f]);sets.push(`${f}=$${vals.length}`);}if(req.body?.status==='resolved'){vals.push(new Date());sets.push(`resolved_at=$${vals.length}`);vals.push(req.user.id);sets.push(`resolved_by=$${vals.length}`);}if(!sets.length)return res.status(400).json({error:'No valid fields to update'});vals.push(req.params.id,req.user.org_id);const {rows}=await req.db(`UPDATE intel_gaps SET ${sets.join(',')},updated_at=now() WHERE id=$${vals.length-1} AND org_id=$${vals.length} RETURNING *`,vals);if(!rows.length)return res.status(404).json({error:'Gap not found'});res.json({gap:rows[0]});}));

router.get('/storylines', asyncHandler(async(req,res)=>{const s=scope(req),geo=scopedObjectClause(s,'s',2);const {rows}=await req.db(`SELECT s.*,COUNT(se.event_id)::int AS event_count FROM intel_storylines s LEFT JOIN intel_storyline_events se ON se.storyline_id=s.id WHERE s.org_id=$1 AND ($2::text IS NULL OR s.status=$2) AND ${geo.clause} GROUP BY s.id ORDER BY s.updated_at DESC LIMIT 200`,[req.user.org_id,req.query.status||null,...geo.params]);res.json({storylines:rows,scope:s,generated_at:new Date().toISOString()});}));
router.get('/storylines/:id', asyncHandler(async(req,res)=>{const {rows}=await req.db(`SELECT s.*,COALESCE(json_agg(json_build_object('event_id',e.id,'sequence_no',se.sequence_no,'relationship',se.relationship,'title',e.title,'summary',e.summary,'severity',e.severity,'confidence',e.confidence,'occurred_from',e.occurred_from,'occurred_to',e.occurred_to) ORDER BY se.sequence_no,e.occurred_from) FILTER(WHERE e.id IS NOT NULL),'[]') AS events FROM intel_storylines s LEFT JOIN intel_storyline_events se ON se.storyline_id=s.id LEFT JOIN intel_events e ON e.id=se.event_id WHERE s.id=$1 AND s.org_id=$2 GROUP BY s.id`,[req.params.id,req.user.org_id]);if(!rows.length)return res.status(404).json({error:'Storyline not found'});res.json({storyline:rows[0]});}));
router.post('/storylines', asyncHandler(async(req,res)=>{const {reference,title,summary,severity,scope_type,scope_key,assessment}=req.body||{};if(!title)return res.status(400).json({error:'title is required'});const ref=reference||`STL-${Date.now().toString(36).toUpperCase()}`;const {rows}=await req.db(`INSERT INTO intel_storylines (org_id,reference,title,summary,severity,scope_type,scope_key,assessment,created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[req.user.org_id,ref,title,summary||null,severity||'moderate',scope_type||'global',scope_key||null,assessment||null,req.user.id]);res.status(201).json({storyline:rows[0]});}));
router.post('/storylines/:id/events', asyncHandler(async(req,res)=>{const {event_id,sequence_no,relationship}=req.body||{};if(!event_id)return res.status(400).json({error:'event_id is required'});const {rows}=await req.db(`INSERT INTO intel_storyline_events (storyline_id,event_id,sequence_no,relationship) SELECT $1,$2,$3,$4 WHERE EXISTS(SELECT 1 FROM intel_storylines WHERE id=$1 AND org_id=$5) AND EXISTS(SELECT 1 FROM intel_events WHERE id=$2 AND org_id=$5) ON CONFLICT(storyline_id,event_id) DO UPDATE SET sequence_no=EXCLUDED.sequence_no,relationship=EXCLUDED.relationship RETURNING *`,[req.params.id,event_id,sequence_no||0,relationship||'develops',req.user.org_id]);if(!rows.length)return res.status(404).json({error:'Storyline or event not found'});res.status(201).json({link:rows[0]});}));

router.get('/forecasts', asyncHandler(async(req,res)=>{const s=scope(req),geo=scopedObjectClause(s,'f',3);const {rows}=await req.db(`SELECT f.* FROM intel_forecasts f WHERE f.org_id=$1 AND ($2::text IS NULL OR f.status<>'expired') AND ${geo.clause} ORDER BY f.valid_until ASC NULLS LAST,f.created_at DESC LIMIT 300`,[req.user.org_id,req.query.status||null,...geo.params]);res.json({forecasts:rows,scope:s,generated_at:new Date().toISOString()});}));
router.post('/forecasts', asyncHandler(async(req,res)=>{const {scope_type,scope_key,horizon,scenario,probability,confidence,judgement,assumptions,indicators,invalidation_triggers,evidence,valid_until}=req.body||{};if(!scope_type||!horizon||!scenario||!judgement)return res.status(400).json({error:'scope_type, horizon, scenario and judgement are required'});const {rows}=await req.db(`INSERT INTO intel_forecasts (org_id,scope_type,scope_key,horizon,scenario,probability,confidence,judgement,assumptions,indicators,invalidation_triggers,evidence,valid_until,created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING *`,[req.user.org_id,scope_type,scope_key||null,horizon,scenario,probability??null,confidence??50,judgement,assumptions||[],indicators||[],invalidation_triggers||[],evidence||[],valid_until||null,req.user.id]);res.status(201).json({forecast:rows[0]});}));

router.post('/publications/:id/review', asyncHandler(async(req,res)=>{const {action,notes}=req.body||{};if(!['submit','approve','reject','withdraw','request_changes'].includes(action))return res.status(400).json({error:'Invalid review action'});const {rows:pub}=await req.db(`SELECT id,status FROM intel_publications WHERE id=$1 AND org_id=$2`,[req.params.id,req.user.org_id]);if(!pub.length)return res.status(404).json({error:'Publication not found'});const next={submit:'review',approve:'published',reject:'draft',withdraw:'withdrawn',request_changes:'draft'}[action];if(action==='approve'&&pub[0].status!=='review')return res.status(409).json({error:'Publication must be in review before approval'});const {rows}=await req.db(`INSERT INTO intel_publication_reviews (org_id,publication_id,action,reviewer_id,notes) VALUES ($1,$2,$3,$4,$5) RETURNING *`,[req.user.org_id,req.params.id,action,req.user.id,notes||null]);await req.db(`UPDATE intel_publications SET status=$1,updated_at=now(),published_at=CASE WHEN $1='published' THEN now() ELSE published_at END,version=CASE WHEN $1 IN ('published','review') THEN version+1 ELSE version END WHERE id=$2 AND org_id=$3`,[next,req.params.id,req.user.org_id]);res.json({review:rows[0],status:next});}));

router.get('/quality', asyncHandler(async(req,res)=>{const s=scope(req),oq=countryClause(s,'o',2),eq=countryClause(s,'e',2),gq=scopedObjectClause(s,'g',2);const {rows:[q]}=await req.db(`SELECT COUNT(*)::int AS observations_30d,COUNT(DISTINCT o.source_id)::int AS sources_30d,ROUND(AVG(o.credibility))::int AS avg_credibility,ROUND(AVG(o.manipulation_score))::int AS avg_manipulation,COUNT(*) FILTER(WHERE o.manipulation_score>=40)::int AS manipulation_flags FROM intel_observations o WHERE o.org_id=$1 AND o.observed_at>=now()-interval '30 days' AND ${oq.clause}`,[req.user.org_id,...oq.params]);const {rows:[e]}=await req.db(`SELECT COUNT(*)::int AS events_30d,ROUND(AVG(e.confidence))::int AS avg_event_confidence,COUNT(*) FILTER(WHERE e.severity IN ('critical','high'))::int AS high_critical_events FROM intel_events e WHERE e.org_id=$1 AND e.last_seen_at>=now()-interval '30 days' AND ${eq.clause}`,[req.user.org_id,...eq.params]);const {rows:[g]}=await req.db(`SELECT COUNT(*) FILTER(WHERE g.status IN ('open','tasked','monitoring'))::int AS open_gaps,COUNT(*) FILTER(WHERE g.status='resolved')::int AS resolved_gaps FROM intel_gaps g WHERE g.org_id=$1 AND ${gq.clause}`,[req.user.org_id,...gq.params]);res.json({quality:{...q,...e,...g,scope:s,checked_at:new Date().toISOString()}});}));

router.get('/events', asyncHandler(async(req,res)=>{const limit=Math.min(500,Math.max(1,Number(req.query.limit)||200)),severity=req.query.severity||null,status=req.query.status||null,s=scope(req),geo=countryClause(s,'e',4),limitIndex=4+geo.params.length;const {rows}=await req.db(`SELECT e.*,COUNT(eo.observation_id)::int AS source_count FROM intel_events e LEFT JOIN intel_event_observations eo ON eo.event_id=e.id WHERE e.org_id=$1 AND ($2::text IS NULL OR e.severity=$2) AND ($3::text IS NULL OR e.status=$3) AND ${geo.clause} GROUP BY e.id ORDER BY e.last_seen_at DESC LIMIT $${limitIndex}`,[req.user.org_id,severity,status,...geo.params,limit]);res.json({events:rows,scope:s,generated_at:new Date().toISOString()});}));
router.get('/events/:id', asyncHandler(async(req,res)=>{const {rows}=await req.db(`SELECT e.*,COALESCE((SELECT json_agg(json_build_object('id',o.id,'title',o.title,'body',o.body,'url',o.url,'observed_at',o.observed_at,'credibility',o.credibility,'manipulation_score',o.manipulation_score,'relationship',eo.relationship,'weight',eo.weight,'source',json_build_object('id',s.id,'name',s.name,'source_type',s.source_type,'provider',s.provider,'reliability',s.reliability))) FROM intel_event_observations eo JOIN intel_observations o ON o.id=eo.observation_id LEFT JOIN intel_sources s ON s.id=o.source_id WHERE eo.event_id=e.id),'[]') AS evidence,COALESCE((SELECT json_agg(json_build_object('event_id',x.id,'title',x.title,'relationship',l.relationship,'confidence',l.confidence)) FROM intel_event_links l JOIN intel_events x ON x.id=CASE WHEN l.from_event_id=e.id THEN l.to_event_id ELSE l.from_event_id END WHERE l.from_event_id=e.id OR l.to_event_id=e.id),'[]') AS related_events FROM intel_events e WHERE e.id=$1 AND e.org_id=$2 GROUP BY e.id`,[req.params.id,req.user.org_id]);if(!rows.length)return res.status(404).json({error:'Event not found'});res.json({event:rows[0]});}));

router.get('/sources', asyncHandler(async(req,res)=>{const active=req.query.active==null?null:req.query.active==='true',s=scope(req),geo=countryClause(s,'o',3);const sourceGeo=s.type==='global'?'TRUE':`EXISTS (SELECT 1 FROM intel_observations os WHERE os.org_id=src.org_id AND os.source_id=src.id AND ${geo.clause.replace(/\bo\./g,'os.')})`;const {rows}=await req.db(`SELECT src.*,COUNT(DISTINCT o.id)::int AS observation_count,MAX(o.observed_at) AS latest_observation FROM intel_sources src LEFT JOIN intel_observations o ON o.source_id=src.id WHERE src.org_id=$1 AND ($2::boolean IS NULL OR src.active=$2) AND ${sourceGeo} GROUP BY src.id ORDER BY src.last_seen_at DESC NULLS LAST,src.name LIMIT 300`,[req.user.org_id,active,...geo.params]);res.json({sources:rows,scope:s,generated_at:new Date().toISOString()});}));
router.get('/observations', asyncHandler(async(req,res)=>{const limit=Math.min(500,Math.max(1,Number(req.query.limit)||200)),s=scope(req),geo=countryClause(s,'o',2),limitIndex=2+geo.params.length;const {rows}=await req.db(`SELECT o.*,s.name AS source_name,s.source_type,s.provider FROM intel_observations o LEFT JOIN intel_sources s ON s.id=o.source_id WHERE o.org_id=$1 AND ${geo.clause} ORDER BY o.observed_at DESC LIMIT $${limitIndex}`,[req.user.org_id,...geo.params,limit]);res.json({observations:rows,scope:s,generated_at:new Date().toISOString()});}));
router.get('/publications', asyncHandler(async(req,res)=>{const status=req.query.status||null,s=scope(req),geo=countryClause(s,'p',3);const {rows}=await req.db(`SELECT p.*,COUNT(r.id)::int AS review_count FROM intel_publications p LEFT JOIN intel_publication_reviews r ON r.publication_id=p.id WHERE p.org_id=$1 AND ($2::text IS NULL OR p.status=$2) AND ${geo.clause} GROUP BY p.id ORDER BY p.updated_at DESC LIMIT 300`,[req.user.org_id,status,...geo.params]);res.json({publications:rows,scope:s,generated_at:new Date().toISOString()});}));
router.get('/watchlists', asyncHandler(async(req,res)=>{const s=scope(req),geo=watchlistClause(s,'w',2);const {rows}=await req.db(`SELECT w.* FROM intel_watchlists w WHERE w.org_id=$1 AND w.active=true AND ${geo.clause} ORDER BY w.updated_at DESC LIMIT 300`,[req.user.org_id,...geo.params]);res.json({watchlists:rows,scope:s,generated_at:new Date().toISOString()});}));
router.get('/requirements', asyncHandler(async(req,res)=>{const status=req.query.status||null,s=scope(req),countries=s.type==='country'?[s.key]:s.type==='region'?REGIONS[s.key]:s.type==='continent'?AFRICA:[];const geo=s.type==='global'?'TRUE':`((LOWER(COALESCE(r.scope->>'scope_type',''))=$2 AND LOWER(COALESCE(r.scope->>'scope_key',''))=$3) OR UPPER(COALESCE(r.scope->>'country_code',''))=ANY($4::text[]))`;const {rows}=await req.db(`SELECT r.* FROM intel_requirements r WHERE r.org_id=$1 AND ($5::text IS NULL OR r.status=$5) AND ${geo} ORDER BY ${priorityRank},r.due_at ASC NULLS LAST,r.created_at DESC LIMIT 300`,[req.user.org_id,s.type,s.key,countries,status]);res.json({requirements:rows,scope:s,generated_at:new Date().toISOString()});}));
router.get('/assessments', asyncHandler(async(req,res)=>{const s=scope(req),geo=scopedObjectClause(s,'a',3);const {rows}=await req.db(`SELECT a.* FROM intel_assessments a WHERE a.org_id=$1 AND ($2::text IS NULL OR a.status=$2) AND (a.validity_end IS NULL OR a.validity_end>=now()) AND ${geo.clause} ORDER BY a.validity_start DESC LIMIT 300`,[req.user.org_id,req.query.status||null,...geo.params]);res.json({assessments:rows,scope:s,generated_at:new Date().toISOString()});}));
router.get('/entities', asyncHandler(async(req,res)=>{const type=req.query.entity_type||null,s=scope(req),geo=countryClause(s,'e',3);const {rows}=await req.db(`SELECT e.* FROM intel_entities e WHERE e.org_id=$1 AND ($2::text IS NULL OR e.entity_type=$2) AND ${geo.clause} ORDER BY e.last_seen_at DESC LIMIT 500`,[req.user.org_id,type,...geo.params]);res.json({entities:rows,scope:s,generated_at:new Date().toISOString()});}));
router.get('/early-warnings', asyncHandler(async(req,res)=>{const s=scope(req),geo=scopedObjectClause(s,'w',2);const {rows}=await req.db(`SELECT w.* FROM intel_early_warnings w WHERE w.org_id=$1 AND w.status IN ('open','review','acknowledged') AND ${geo.clause} ORDER BY CASE w.severity WHEN 'critical' THEN 1 WHEN 'high' THEN 2 WHEN 'moderate' THEN 3 ELSE 4 END,w.last_detected_at DESC LIMIT 300`,[req.user.org_id,...geo.params]);res.json({warnings:rows,scope:s,generated_at:new Date().toISOString()});}));
module.exports=router;
