const crypto = require('crypto');
const zlib = require('zlib');
const { query } = require('../../config/database');
const { withOrg } = require('../../utils/orgScopedDb');
const logger = require('../../utils/logger');
const { queueClientPulseEmail } = require('./email.service');

const MANIFEST_COLUMNS = [
  ['booking_number', 'BOOKING NO'], ['carrier_reference', 'CARRIER REF'], ['vessel', 'VESSEL'], ['file_reference', 'AW FILE REF NO'], ['controller', 'CONTROLLER'], ['commodity', 'COMMODITY'],
  ['packing_list_no', 'PACKING LIST NO'], ['container_number', 'CONTAINER NO'], ['iso_type', 'TYPE'], ['seal_number', 'SEAL 1'], ['seal_number_2', 'SEAL 2'], ['status', 'STAGE'], ['clamped_at', 'DATE CLAMPED'], ['clamped_at_t', 'TIME CLAMPED'], ['unclamped_at', 'TIME UNCLAMPED'], ['lock_number', 'LOCK NO'], ['terminal', 'TERMINAL'], ['yard_status', 'LOCATION'], ['transporter', 'TRANSPORTER'], ['horse_reg', 'HORSE REG'], ['trailer_reg', 'TRAILER REG'], ['driver_name', 'DRIVER NAME'], ['driver_contact', 'DRIVER CONTACT'], ['invoiced', 'INVOICED'],
];
const ACTIVE_CONTAINER_STATUSES = new Set(['pending', 'assigned', 'in_transit', 'at_port']);
const INACTIVE_BOOKING_STATUSES = new Set(['completed', 'delivered', 'cancelled', 'canceled', 'archived', 'closed']);
function isActiveRow(row) { const bs = String(row.booking_status || '').toLowerCase(); const cs = String(row.status || '').toLowerCase(); if (INACTIVE_BOOKING_STATUSES.has(bs)) return false; return ACTIVE_CONTAINER_STATUSES.has(cs) || !['delivered', 'completed'].includes(cs); }

async function fetchManifestSnapshot(orgId) {
  return withOrg(orgId, client => client.query(`
    SELECT bc.id, bc.booking_id, bc.container_number, bc.seal_number, bc.seal_number_2, bc.packing_list_no, bc.iso_type,
           bc.weight_kg, bc.status, bc.notes, bc.clamped_at, bc.unclamped_at, bc.terminal, bc.yard_status, bc.invoiced,
           bc.lock_number, bc.transporter_name, bc.horse_reg, bc.trailer_reg, bc.driver_name, bc.driver_contact,
           b.booking_number, b.reference AS file_reference, b.vessel, b.commodity, b.controller, b.country_code, b.direction,
           b.carrier_reference, b.status AS booking_status, b.pickup_location, b.delivery_location, b.eta, b.created_at AS booking_created_at,
           cu.company_name AS customer_name, t.trip_number, t.status AS trip_status,
           COALESCE(bc.transporter_name, tr.company_name) AS transporter,
           COALESCE(bc.horse_reg, v.registration) AS horse_reg_derived,
           COALESCE(bc.driver_name, d.name) AS driver_name_derived,
           COALESCE(bc.driver_contact, d.phone) AS driver_contact_derived,
           l.serial AS lock_serial
      FROM cds_booking_containers bc
      JOIN cds_bookings b ON b.id = bc.booking_id
      LEFT JOIN cds_customers cu ON cu.id = b.customer_id
      LEFT JOIN cds_trips t ON t.id = bc.trip_id
      LEFT JOIN cds_transporters tr ON tr.id = t.transporter_id
      LEFT JOIN cds_vehicles v ON v.id = t.vehicle_id
      LEFT JOIN cds_drivers d ON d.id = t.driver_id
      LEFT JOIN cds_electronic_locks l ON l.id = t.lock_id
     WHERE bc.org_id=$1 AND bc.deleted_at IS NULL AND b.org_id=$1 AND b.deleted_at IS NULL
     ORDER BY b.created_at DESC NULLS LAST, b.id, bc.id`, [orgId]));
}
function manifestRow(row) { return { booking_number: row.booking_number, carrier_reference: row.carrier_reference, vessel: row.vessel, file_reference: row.file_reference, controller: row.controller, commodity: row.commodity, packing_list_no: row.packing_list_no, container_number: row.container_number, iso_type: row.iso_type, seal_number: row.seal_number, seal_number_2: row.seal_number_2, status: row.status, clamped_at: row.clamped_at, clamped_at_t: row.clamped_at, unclamped_at: row.unclamped_at, lock_number: row.lock_number || row.lock_serial, terminal: row.terminal, yard_status: row.yard_status, transporter: row.transporter, horse_reg: row.horse_reg || row.horse_reg_derived, trailer_reg: row.trailer_reg, driver_name: row.driver_name || row.driver_name_derived, driver_contact: row.driver_contact || row.driver_contact_derived, invoiced: row.invoiced ? 'YES' : 'NO' }; }

function xmlEscape(value) { return String(value ?? '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;').replace(/'/g,'&apos;'); }
function colLetter(n) { let s=''; for(let x=n+1;x>0;x=Math.floor((x-1)/26)) s=String.fromCharCode(65+(x-1)%26)+s; return s; }
function eatDateSerial(value, dateOnly=false) { const d=new Date(value); if(Number.isNaN(d.getTime())) return null; const local=new Date(d.getTime()+3*60*60*1000); const base=Date.UTC(1899,11,30); const days=(local.getTime()-base)/86400000; return dateOnly ? Math.floor(days) : days; }
function crc32(buffer) { let table=crc32.table; if(!table){ table=new Uint32Array(256); for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xEDB88320^(c>>>1):c>>>1;table[n]=c>>>0;} crc32.table=table; } let c=0xFFFFFFFF; for(const b of buffer)c=table[(c^b)&0xFF]^(c>>>8); return (c^0xFFFFFFFF)>>>0; }
function zip(entries) {
  const chunks=[]; const central=[]; let offset=0;
  for(const entry of entries){ const name=Buffer.from(entry.name); const data=Buffer.isBuffer(entry.data)?entry.data:Buffer.from(entry.data); const compressed=zlib.deflateRawSync(data,{level:6}); const useDeflated=compressed.length<data.length; const body=useDeflated?compressed:data; const method=useDeflated?8:0; const crc=crc32(data); const local=Buffer.alloc(30+name.length); local.writeUInt32LE(0x04034b50,0); local.writeUInt16LE(20,4); local.writeUInt16LE(0,6); local.writeUInt16LE(method,8); local.writeUInt16LE(0,10); local.writeUInt16LE(0,12); local.writeUInt32LE(crc,14); local.writeUInt32LE(body.length,18); local.writeUInt32LE(data.length,22); local.writeUInt16LE(name.length,26); local.writeUInt16LE(0,28); name.copy(local,30); chunks.push(local,body); const c=Buffer.alloc(46+name.length); c.writeUInt32LE(0x02014b50,0); c.writeUInt16LE(20,4); c.writeUInt16LE(20,6); c.writeUInt16LE(0,8); c.writeUInt16LE(method,10); c.writeUInt16LE(0,12); c.writeUInt16LE(0,14); c.writeUInt32LE(crc,16); c.writeUInt32LE(body.length,20); c.writeUInt32LE(data.length,24); c.writeUInt16LE(name.length,28); c.writeUInt16LE(0,30); c.writeUInt16LE(0,32); c.writeUInt16LE(0,34); c.writeUInt16LE(0,36); c.writeUInt32LE(0,38); c.writeUInt32LE(offset,42); name.copy(c,46); central.push(c); offset+=local.length+body.length; }
  const centralBuf=Buffer.concat(central); const end=Buffer.alloc(22); end.writeUInt32LE(0x06054b50,0); end.writeUInt16LE(0,8); end.writeUInt16LE(central.length,10); end.writeUInt32LE(centralBuf.length,12); end.writeUInt32LE(offset,16); return Buffer.concat([...chunks,centralBuf,end]);
}
function cellXml(ref,value,style=0){ if(value==null||value==='') return ''; if(style===2||style===3) return `<c r=\"${ref}\" s=\"${style}\"><v>${value}</v></c>`; return `<c r=\"${ref}\" t=\"inlineStr\"${style?` s=\"${style}\"`:''}><is><t xml:space=\"preserve\">${xmlEscape(value)}</t></is></c>`; }
function sheetXml(rows){ const total=rows.length+1; let xml='<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><worksheet xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\"><sheetViews><sheetView workbookViewId=\"0\"><pane ySplit=\"1\" topLeftCell=\"A2\" activePane=\"bottomLeft\" state=\"frozen\"/></sheetView></sheetViews><sheetFormatPr defaultRowHeight=\"15\"/><sheetData><row r=\"1\" ht=\"22\" customHeight=\"1\">'; MANIFEST_COLUMNS.forEach(([,h],i)=>{xml+=cellXml(`${colLetter(i)}1`,h,1);}); xml+='</row>'; rows.forEach((row,ri)=>{const r=ri+2; xml+=`<row r=\"${r}\">`; MANIFEST_COLUMNS.forEach(([key],i)=>{let v=row[key],style=0;if(key==='clamped_at') {v=eatDateSerial(v,true);style=v==null?0:2;} else if(key==='clamped_at_t'||key==='unclamped_at'){v=eatDateSerial(v,false);style=v==null?0:3;} xml+=cellXml(`${colLetter(i)}${r}`,v,style);}); xml+='</row>';}); xml+=`</sheetData><autoFilter ref=\"A1:X${total}\"/><pageMargins left=\"0.25\" right=\"0.25\" top=\"0.5\" bottom=\"0.5\" header=\"0.2\" footer=\"0.2\"/></worksheet>`; return xml; }
async function buildManifestWorkbook(rows,snapshotAt){
  const styles='<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><styleSheet xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\"><numFmts count=\"2\"><numFmt numFmtId=\"164\" formatCode=\"dd/mm/yyyy\"/><numFmt numFmtId=\"165\" formatCode=\"hhmm&quot;hrs&quot;\"/></numFmts><fonts count=\"2\"><font><sz val=\"11\"/><name val=\"Arial\"/></font><font><b/><sz val=\"11\"/><name val=\"Arial\"/></font></fonts><fills count=\"2\"><fill><patternFill patternType=\"none\"/></fill><fill><patternFill patternType=\"gray125\"/></fill></fills><borders count=\"2\"><border/><border><bottom style=\"thin\"/></border></borders><cellStyleXfs count=\"1\"><xf numFmtId=\"0\" fontId=\"0\" fillId=\"0\" borderId=\"0\"/></cellStyleXfs><cellXfs count=\"4\"><xf numFmtId=\"0\" fontId=\"0\" fillId=\"0\" borderId=\"0\"/><xf numFmtId=\"0\" fontId=\"1\" fillId=\"0\" borderId=\"1\"/><xf numFmtId=\"164\" fontId=\"0\" fillId=\"0\" borderId=\"0\"/><xf numFmtId=\"165\" fontId=\"0\" fillId=\"0\" borderId=\"0\"/></cellXfs></styleSheet>';
  const contentTypes='<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\"><Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/><Default Extension=\"xml\" ContentType=\"application/xml\"/><Override PartName=\"/xl/workbook.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml\"/><Override PartName=\"/xl/worksheets/sheet1.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/><Override PartName=\"/xl/styles.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml\"/><Override PartName=\"/docProps/core.xml\" ContentType=\"application/vnd.openxmlformats-package.core-properties+xml\"/><Override PartName=\"/docProps/app.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.extended-properties+xml\"/></Types>';
  const rootRels='<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"xl/workbook.xml\"/><Relationship Id=\"rId2\" Type=\"http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties\" Target=\"docProps/core.xml\"/><Relationship Id=\"rId3\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties\" Target=\"docProps/app.xml\"/></Relationships>';
  const workbook='<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><workbook xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\"><sheets><sheet name=\"Booking Manifest\" sheetId=\"1\" r:id=\"rId1\"/></sheets></workbook>';
  const wbRels='<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet\" Target=\"worksheets/sheet1.xml\"/><Relationship Id=\"rId2\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles\" Target=\"styles.xml\"/></Relationships>';
  const iso=snapshotAt.toISOString(); const core=`<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><cp:coreProperties xmlns:cp=\"http://schemas.openxmlformats.org/package/2006/metadata/core-properties\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\"><dc:creator>Sonalit</dc:creator><dc:title>CDS Active Booking Manifest</dc:title><dc:subject>Sonalit CDS Client Pulse</dc:subject><cp:lastModifiedBy>Sonalit</cp:lastModifiedBy><dcterms:created xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:type=\"dcterms:W3CDTF\">${iso}</dcterms:created><dcterms:modified xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:type=\"dcterms:W3CDTF\">${iso}</dcterms:modified></cp:coreProperties>`;
  const app='<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><Properties xmlns=\"http://schemas.openxmlformats.org/officeDocument/2006/extended-properties\" xmlns:vt=\"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes\"><Application>Sonalit</Application><AppVersion>1.0</AppVersion></Properties>';
  return zip([['[Content_Types].xml',contentTypes],['_rels/.rels',rootRels],['xl/workbook.xml',workbook],['xl/_rels/workbook.xml.rels',wbRels],['xl/styles.xml',styles],['xl/worksheets/sheet1.xml',sheetXml(rows)],['docProps/core.xml',core],['docProps/app.xml',app]].map(([name,data])=>({name,data})));
}
async function resolveClientPulseRecipients(orgId){
  const result=await withOrg(orgId,client=>client.query(`SELECT DISTINCT email,name FROM client_email_recipients WHERE org_id=$1 AND enabled=true AND deleted_at IS NULL AND cds_client_pulse=true AND email IS NOT NULL ORDER BY email`,[orgId]));
  return result.rows;
}
function dateLabel(date){return new Intl.DateTimeFormat('en-GB',{timeZone:process.env.CDS_CLIENT_PULSE_TIMEZONE||'Africa/Nairobi',day:'2-digit',month:'short',year:'numeric'}).format(date);}
async function generateAndQueueClientPulse(orgId,{snapshotAt=new Date()}={}){
  if(!orgId)throw new Error('orgId is required for Client Pulse');const snapshot=snapshotAt instanceof Date?snapshotAt:new Date(snapshotAt);if(Number.isNaN(snapshot.getTime()))throw new Error('Invalid Client Pulse snapshot time');
  const idempotencyKey=`cds-client-pulse:${snapshot.toISOString().slice(0,13)}`;const claim=await withOrg(orgId,client=>client.query(`INSERT INTO cds_client_pulse_runs (org_id,snapshot_at,status,idempotency_key) VALUES ($1,$2,'generating',$3) ON CONFLICT (org_id,idempotency_key) DO NOTHING RETURNING id`,[orgId,snapshot,idempotencyKey]));if(!claim.rows.length)return{skipped:true,reason:'duplicate_snapshot'};const runId=claim.rows[0].id;
  try{const active=(await fetchManifestSnapshot(orgId)).rows.filter(isActiveRow).map(manifestRow);const recipients=await resolveClientPulseRecipients(orgId);const activeBookingCount=new Set(active.map(r=>r.booking_number).filter(Boolean)).size;if(!active.length){await query(`UPDATE cds_client_pulse_runs SET status='skipped',active_booking_count=$2,row_count=$3,updated_at=NOW() WHERE id=$1`,[runId,activeBookingCount,active.length]);return{skipped:true,reason:'no_active_bookings',rows:0};}if(!recipients.length){await query(`UPDATE cds_client_pulse_runs SET status='skipped',active_booking_count=$2,row_count=$3,updated_at=NOW() WHERE id=$1`,[runId,activeBookingCount,active.length]);return{skipped:true,reason:'no_client_pulse_recipients',rows:active.length};}const workbook=await buildManifestWorkbook(active,snapshot);if(!workbook.length)throw new Error('Generated Client Pulse workbook is empty');const manifestHash=crypto.createHash('sha256').update(workbook).digest('hex');const stamp=snapshot.toISOString().replace(/[:]/g,'').replace(/\.\d{3}Z$/,'Z');const filename=`CDS_Client_Pulse_Active_Bookings_${stamp}_EAT.xlsx`;const result=await queueClientPulseEmail({orgId,recipients:recipients.map(r=>r.email),snapshotAt:snapshot.toISOString(),activeBookingCount,dateLabel:dateLabel(snapshot),attachment:{filename,content:workbook.toString('base64'),contentType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'},correlationId:`cds-client-pulse:${runId}`,idempotencyKey});const ids=await withOrg(orgId,client=>client.query(`SELECT id FROM email_notifications WHERE org_id=$1 AND notification_type='cds_client_pulse' AND correlation_id=$2 ORDER BY created_at DESC`,[orgId,`cds-client-pulse:${runId}`]));await query(`UPDATE cds_client_pulse_runs SET status=$2,active_booking_count=$3,row_count=$4,attachment_name=$5,manifest_hash=$6,email_notification_ids=$7,updated_at=NOW() WHERE id=$1`,[runId,result.queued?'queued':'skipped',activeBookingCount,active.length,filename,manifestHash,ids.rows.map(r=>r.id)]);return{runId,queued:result.queued,duplicate:result.duplicate,rows:active.length,recipients:recipients.length,filename,manifestHash};}
  catch(err){await query(`UPDATE cds_client_pulse_runs SET status='failed',error=$2,updated_at=NOW() WHERE id=$1`,[runId,String(err.message||err).slice(0,4000)]);logger.error(`CDS Client Pulse failed: org=${orgId} run=${runId} error=${err.message}`);throw err;}
}
module.exports={MANIFEST_COLUMNS,isActiveRow,fetchManifestSnapshot,buildManifestWorkbook,resolveClientPulseRecipients,generateAndQueueClientPulse};
