const crypto = require('crypto');
const { getQueues } = require('../../config/queue');
const { withOrg } = require('../../utils/orgScopedDb');
const { alertTemplate, securityAlertTemplate, clientPulseTemplate, genericTemplate } = require('./templates');
const { resolveEmailRoute } = require('./routing');
const { mapUrlForPanic } = require('../securityIncidentMap');
const FROM = process.env.RESEND_FROM_EMAIL || 'Sonalit <notifications@sonalit.com>';
const REPLY_TO = process.env.RESEND_REPLY_TO || undefined;
function normalizeRecipients(recipients){return [...new Set((Array.isArray(recipients)?recipients:[recipients]).filter(Boolean).map(String).map(s=>s.trim().toLowerCase()))]}
function stableKey(input){return crypto.createHash('sha256').update(JSON.stringify(input)).digest('hex')}
function normalizeAttachments(attachments){if(!Array.isArray(attachments))return [];return attachments.map(a=>({filename:String(a.filename),content:String(a.content),contentType:a.contentType?String(a.contentType):undefined})).filter(a=>a.filename&&a.content)}
async function enqueueEmail({orgId,to,recipientName,notificationType,severity='normal',entityType,entityId,correlationId,idempotencyKey,templateData,attachments=[],sender,replyTo,securityEvent=false}){if(!orgId)throw new Error('orgId is required for email enqueue');const recipients=normalizeRecipients(to);if(!recipients.length)return{queued:0,duplicate:0};if(!process.env.RESEND_API_KEY)throw new Error('Email provider is not configured');const route=resolveEmailRoute({type:templateData?.alertType||notificationType,severity,securityEvent});const selectedSender=sender||(notificationType==='operational_alert'||notificationType==='security_incident'?route.sender:FROM);const selectedReplyTo=replyTo!==undefined?replyTo:(notificationType==='operational_alert'||notificationType==='security_incident'?route.replyTo:REPLY_TO);const rendered=notificationType==='security_incident'?securityAlertTemplate(templateData):notificationType==='cds_client_pulse'?clientPulseTemplate(templateData):templateData?.alertType?alertTemplate(templateData):genericTemplate(templateData);const normalizedAttachments=normalizeAttachments(attachments);const queue=getQueues().emailQueue;if(!queue)throw new Error('Email queue is unavailable; refusing to drop email');let queued=0,duplicate=0;for(const recipient of recipients){const key=idempotencyKey?stableKey({base:idempotencyKey,recipient}):stableKey({orgId,recipient,notificationType,entityType,entityId,subject:rendered.subject});const inserted=await withOrg(orgId,client=>client.query(`INSERT INTO email_notifications (org_id,recipient,recipient_name,notification_type,severity,subject,text_body,html_body,entity_type,entity_id,correlation_id,idempotency_key,status,sender,reply_to,attachments) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,'queued',$13,$14,$15::jsonb) ON CONFLICT (org_id,idempotency_key) DO NOTHING RETURNING id`,[orgId,recipient,recipientName||null,notificationType,severity,rendered.subject,rendered.text,rendered.html,entityType||null,entityId||null,correlationId||null,key,selectedSender,selectedReplyTo||null,JSON.stringify(normalizedAttachments)]));if(!inserted.rows.length){duplicate++;continue}await queue.add('email.send',{emailNotificationId:inserted.rows[0].id},{jobId:`email:${inserted.rows[0].id}`,priority:severity==='critical'?1:severity==='high'?2:5,attempts:8,backoff:{type:'exponential',delay:2000},removeOnComplete:{count:1000},removeOnFail:false});queued++}return{queued,duplicate}}
async function queueAlertEmail({orgId,recipients,alert,correlationId,ctaUrl}){const route=resolveEmailRoute({type:alert.type,severity:alert.severity,securityEvent:alert.security_event===true});const metadata=alert.metadata||{};return enqueueEmail({orgId,to:recipients.map(r=>r.email||r),notificationType:route.audience==='security'?'security_incident':'operational_alert',severity:alert.severity,entityType:'alert',entityId:alert.id,correlationId,idempotencyKey:`alert:${alert.id}`,sender:route.sender,replyTo:route.replyTo,securityEvent:route.audience==='security',templateData:{alertType:alert.type,severity:alert.severity,vehicle:alert.registration,region:alert.region,convoy:alert.convoy_name,message:alert.message,time:alert.created_at,ctaLabel:'Open incident in Sonalit',ctaUrl,incidentId:alert.id,mapUrl:metadata.map_url||null,clientId:metadata.client_id||null,deviceId:metadata.device_id||null,vehicleId:metadata.vehicle_id||null,convoyId:metadata.convoy_id||null,convoyStatus:metadata.convoy_status||null,route:metadata.route||null,ownership:metadata.ownership||null,coordinates:metadata.coordinates||null}})}
async function queueClientPulseEmail({orgId,recipients,snapshotAt,activeBookingCount,dateLabel,attachment,correlationId,idempotencyKey}){if(!Number(activeBookingCount))return{queued:0,duplicate:0,skipped:true,reason:'no_active_bookings'};if(!attachment?.filename||!attachment?.content)throw new Error('Client Pulse attachment is required');return enqueueEmail({orgId,to:recipients,notificationType:'cds_client_pulse',severity:'normal',entityType:'cds_client_pulse',correlationId,idempotencyKey,sender:process.env.RESEND_CDS_PULSE_FROM_EMAIL||FROM,replyTo:process.env.RESEND_CDS_PULSE_REPLY_TO||REPLY_TO,attachments:[attachment],templateData:{snapshotAt,activeBookingCount,dateLabel}})}
module.exports={enqueueEmail,queueAlertEmail,queueClientPulseEmail,stableKey,FROM,REPLY_TO};
