const escapeHtml = (value) => String(value ?? '')
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  .replace(/"/g, '&quot;').replace(/'/g, '&#39;');

const severityMeta = { critical: { label: 'CRITICAL', glyph: '●' }, high: { label: 'HIGH', glyph: '●' }, normal: { label: 'NOTICE', glyph: '●' }, low: { label: 'INFO', glyph: '●' } };

function layout({ preheader = '', title, eyebrow = 'SONALIT OPERATIONS', body, ctaLabel, ctaUrl }) {
  const cta = ctaLabel && ctaUrl ? `<table role="presentation" cellpadding="0" cellspacing="0" border="0"><tr><td bgcolor="#F0B429" style="background-color:#F0B429;border-radius:6px"><a href="${escapeHtml(ctaUrl)}" style="display:inline-block;font-family:Arial,Helvetica,sans-serif;font-size:14px;line-height:20px;color:#081018;text-decoration:none;font-weight:700;padding:12px 18px">${escapeHtml(ctaLabel)}</a></td></tr></table>` : '';
  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head><body style="margin:0;padding:0;background:#070B12;color:#E5E7EB;font-family:Arial,Helvetica,sans-serif"><div style="display:none;max-height:0;overflow:hidden;font-size:1px;line-height:1px">${escapeHtml(preheader)}</div><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" bgcolor="#070B12"><tr><td align="center" style="padding:28px 16px"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="max-width:600px;background:#0D1321"><tr><td style="padding:26px 28px 12px"><p style="margin:0;font-size:11px;line-height:16px;color:#94A3B8;letter-spacing:1.4px">${escapeHtml(eyebrow)}</p><h1 style="margin:8px 0 0;font-size:24px;line-height:32px;color:#F8FAFC">${escapeHtml(title)}</h1></td></tr><tr><td style="padding:12px 28px 28px">${body}${cta ? `<table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%"><tr><td style="padding-top:24px">${cta}</td></tr></table>` : ''}</td></tr><tr><td style="padding:18px 28px 20px;border-top:1px solid #1F2937"><p style="margin:0;font-size:11px;line-height:17px;color:#64748B">Automated message from Sonalit. Please do not rely on this email alone for time-critical operational decisions.</p></td></tr></table></td></tr></table></body></html>`;
}

function alertTemplate(data) {
  const severity = String(data.severity || 'normal').toLowerCase(); const meta = severityMeta[severity] || severityMeta.normal;
  const rows = [['Alert type', data.alertType], ['Severity', `${meta.glyph} ${meta.label}`], ['Vehicle', data.vehicle || 'Unknown'], ['Region', data.region || 'Unknown'], ['Convoy', data.convoy || 'N/A'], ['Time', data.time || new Date().toISOString()]].map(([k,v]) => `<tr><td style="padding:8px 0;font-size:13px;color:#94A3B8">${escapeHtml(k)}</td><td style="padding:8px 0;font-size:13px;color:#F8FAFC;font-weight:700">${escapeHtml(v)}</td></tr>`).join('');
  const body = `<p style="margin:0 0 18px;font-size:15px;line-height:24px;color:#CBD5E1">${escapeHtml(data.message)}</p><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">${rows}</table>`;
  return { subject: `[${meta.label}] Sonalit operational alert — ${data.alertType || 'Alert'} — ${data.vehicle || 'Unknown vehicle'}`, text: `Sonalit ${meta.label} operational alert\n\nType: ${data.alertType || 'Alert'}\nSeverity: ${severity}\nVehicle: ${data.vehicle || 'Unknown'}\nRegion: ${data.region || 'Unknown'}\nConvoy: ${data.convoy || 'N/A'}\nTime: ${data.time || new Date().toISOString()}\n\n${data.message}`, html: layout({ preheader: `${meta.label} operational alert for ${data.vehicle || 'unknown vehicle'}`, title: `${meta.label} operational alert`, body, ctaLabel: data.ctaLabel, ctaUrl: data.ctaUrl }) };
}

function securityAlertTemplate(data) {
  const severity = String(data.severity || 'high').toLowerCase(); const meta = severityMeta[severity] || severityMeta.high;
  const rows = [['Event', data.alertType || 'Security event'], ['Severity', meta.label], ['Vehicle', data.vehicle || 'Unknown'], ['Convoy', data.convoy || 'N/A'], ['Region', data.region || 'Unknown'], ['Detected', data.time || new Date().toISOString()]].map(([k,v]) => `<tr><td style="padding:8px 0;font-size:13px;color:#94A3B8">${escapeHtml(k)}</td><td style="padding:8px 0;font-size:13px;color:#F8FAFC;font-weight:700">${escapeHtml(v)}</td></tr>`).join('');
  const body = `<p style="margin:0 0 14px;font-size:15px;line-height:24px;color:#F8FAFC;font-weight:700">Security event requires attention.</p><p style="margin:0 0 18px;font-size:14px;line-height:22px;color:#CBD5E1">${escapeHtml(data.message)}</p><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">${rows}</table>`;
  return { subject: `[${meta.label}] Sonalit security incident — ${data.alertType || 'Security event'} — ${data.vehicle || 'Unknown vehicle'}`, text: `Sonalit ${meta.label} security incident\n\nEvent: ${data.alertType || 'Security event'}\nSeverity: ${severity}\nVehicle: ${data.vehicle || 'Unknown'}\nConvoy: ${data.convoy || 'N/A'}\nRegion: ${data.region || 'Unknown'}\nDetected: ${data.time || new Date().toISOString()}\n\n${data.message}`, html: layout({ preheader: `${meta.label} security incident requiring attention`, title: `${meta.label} security incident`, eyebrow: 'SONALIT SECURITY', body, ctaLabel: data.ctaLabel, ctaUrl: data.ctaUrl }) };
}

function clientPulseTemplate(data) {
  const snapshot = data.snapshotAt || new Date().toISOString(); const count = Number(data.activeBookingCount || 0);
  const body = `<p style="margin:0 0 14px;font-size:15px;line-height:24px;color:#CBD5E1">Please find attached the latest CDS Active Booking Manifest, showing all currently active bookings and their latest recorded state.</p><p style="margin:0;font-size:13px;line-height:20px;color:#94A3B8">Snapshot: <strong style="color:#F8FAFC">${escapeHtml(snapshot)}</strong><br>Active bookings: <strong style="color:#F8FAFC">${count}</strong><br>The spreadsheet reflects the Booking Manifest at the snapshot time.</p>`;
  return { subject: `CDS Client Pulse — Active Booking Manifest — ${data.dateLabel}`, text: `Please find attached the latest CDS Active Booking Manifest, showing all currently active bookings and their latest recorded state.\n\nSnapshot: ${snapshot}\nActive bookings: ${count}\n\nThe spreadsheet reflects the Booking Manifest at the snapshot time.\n\nRegards,\nSonalit Operations`, html: layout({ preheader: `CDS active booking manifest snapshot — ${data.dateLabel}`, title: 'CDS Client Pulse', eyebrow: 'SONALIT CDS · CLIENT PULSE', body }) };
}

function genericTemplate(data) { const body = `<p style="margin:0;font-size:15px;line-height:24px;color:#CBD5E1">${escapeHtml(data.message)}</p>`; return { subject: data.subject, text: data.message, html: layout({ preheader: data.subject, title: data.title || data.subject, body, ctaLabel: data.ctaLabel, ctaUrl: data.ctaUrl }) }; }

module.exports = { escapeHtml, alertTemplate, securityAlertTemplate, clientPulseTemplate, genericTemplate };
