// Shared provider-resilient AI client. Anthropic is primary; Groq is an open-weight fallback.
const Anthropic=require('@anthropic-ai/sdk');const OpenAI=require('openai');const logger=require('./logger');
const GROQ_MODEL=process.env.GROQ_MODEL||'openai/gpt-oss-120b';const DEFAULT_ANTHROPIC_MODEL=process.env.ANTHROPIC_MODEL||'claude-sonnet-4-6';const ANTHROPIC_COOLDOWN_MS=60_000,GROQ_COOLDOWN_MS=120_000;let anthropicClient=null,groqClient=null,anthropicDownUntil=0,groqDownUntil=0;
function hasAnthropic(){const k=process.env.ANTHROPIC_API_KEY;return!!(k&&k.length>=20);}function hasGroqFallback(){const k=process.env.GROQ_API_KEY;return!!(k&&k.length>=20);}function getAnthropicClient(){if(!anthropicClient)anthropicClient=new Anthropic({apiKey:process.env.ANTHROPIC_API_KEY});return anthropicClient;}function getGroqClient(){if(!groqClient)groqClient=new OpenAI({apiKey:process.env.GROQ_API_KEY,baseURL:'https://api.groq.com/openai/v1'});return groqClient;}
function isRetryableAnthropicError(err){const s=err?.status;return s===429||s===500||s===503||s===529||(err?.message||'').includes('Overloaded');}function isRateLimited(err){return err?.status===429||/rate.?limit|quota|too many/i.test(err?.message||'');}
function normalizeAnthropicParams(input){const params={...input};params.model=params.model||DEFAULT_ANTHROPIC_MODEL;let hasWebSearch=false;if(Array.isArray(params.tools)){params.tools=params.tools.map(t=>{if(t?.type&&String(t.type).startsWith('web_search')){hasWebSearch=true;return{...t,type:'web_search_20250305',allowed_callers:undefined};}return t;});}if(hasWebSearch&&/^claude-sonnet-5/i.test(params.model))params.model='claude-sonnet-4-6';if(Array.isArray(params.messages)&&params.messages.length){const last=params.messages[params.messages.length-1];if(last?.role==='assistant'&&typeof last.content==='string')params.messages=params.messages.slice(0,-1).concat([{role:'user',content:`Continue from the preceding context. ${last.content}`}]);}return params;}
async function callAnthropicWithRetry(params,maxRetries=2){const client=getAnthropicClient(),normalized=normalizeAnthropicParams(params);for(let attempt=0;attempt<=maxRetries;attempt++){try{return await client.messages.create(normalized);}catch(err){if(isRetryableAnthropicError(err)&&attempt<maxRetries){await new Promise(r=>setTimeout(r,Math.min(8000,(attempt+1)*2000)));continue;}throw err;}}}
function toolsToOpenAI(tools){return(tools||[]).filter(t=>t.input_schema).map(t=>({type:'function',function:{name:t.name,description:t.description,parameters:t.input_schema}}));}function toolChoiceToOpenAI(c){if(!c)return undefined;if(c.type==='tool')return{type:'function',function:{name:c.name}};if(c.type==='any')return'required';return'auto';}function systemToOpenAI(system){if(!system)return undefined;if(typeof system==='string')return system;if(Array.isArray(system))return system.map(b=>b.text).filter(Boolean).join('\n');return undefined;}
function messagesToOpenAI(messages){const out=[];for(const m of messages||[]){if(typeof m.content==='string'){out.push({role:m.role,content:m.content});continue;}if(!Array.isArray(m.content))continue;if(m.role==='assistant'){const text=m.content.filter(b=>b.type==='text').map(b=>b.text).join('\n');const calls=m.content.filter(b=>b.type==='tool_use').map(b=>({id:b.id,type:'function',function:{name:b.name,arguments:JSON.stringify(b.input??{})}}));const msg={role:'assistant',content:text||null};if(calls.length)msg.tool_calls=calls;out.push(msg);}else{const trs=m.content.filter(b=>b.type==='tool_result');if(trs.length)for(const tr of trs)out.push({role:'tool',tool_call_id:tr.tool_use_id,content:typeof tr.content==='string'?tr.content:JSON.stringify(tr.content)});else{const text=m.content.filter(b=>b.type==='text').map(b=>b.text).join('\n');if(text)out.push({role:'user',content:text});}}}return out;}
function openAIResponseToAnthropicShape(completion){const choice=completion.choices?.[0],message=choice?.message||{},content=[];if(message.content)content.push({type:'text',text:message.content});for(const tc of message.tool_calls||[]){let input={};try{input=JSON.parse(tc.function?.arguments||'{}')}catch{}content.push({type:'tool_use',id:tc.id,name:tc.function?.name,input});}return{content,stop_reason:choice?.finish_reason==='tool_calls'?'tool_use':'end_turn'};}
async function callGroq({system,messages,tools,tool_choice,max_tokens}){const completion=await getGroqClient().chat.completions.create({model:GROQ_MODEL,max_completion_tokens:Math.min(Number(max_tokens)||2048,4096),messages:[...(system?[{role:'system',content:systemToOpenAI(system)}]:[]),...messagesToOpenAI(messages)],...(tools?.length?{tools:toolsToOpenAI(tools)}:{}),...(tool_choice?{tool_choice:toolChoiceToOpenAI(tool_choice)}:{})});return openAIResponseToAnthropicShape(completion);}
async function createMessage(params,{allowFallback=true}={}){if(hasAnthropic()&&Date.now()>=anthropicDownUntil){try{return{...(await callAnthropicWithRetry(params)),_provider:'anthropic'};}catch(err){anthropicDownUntil=Date.now()+ANTHROPIC_COOLDOWN_MS;if(!allowFallback||!hasGroqFallback())throw err;logger.warn(`AI client: Anthropic failed (${err?.status||err.message}); opening ${ANTHROPIC_COOLDOWN_MS/1000}s circuit and falling back to Groq`);}}if(!allowFallback||!hasGroqFallback())throw new Error('AI client: no provider available');if(Date.now()<groqDownUntil)throw new Error('AI client: Groq fallback circuit is open');try{return{...(await callGroq(params)),_provider:'groq'};}catch(err){if(isRateLimited(err)){groqDownUntil=Date.now()+GROQ_COOLDOWN_MS;logger.warn(`AI client: Groq rate/quota limited; opening ${GROQ_COOLDOWN_MS/1000}s circuit`);}throw err;}}
module.exports={hasAnthropic,hasGroqFallback,createMessage,isRetryableAnthropicError,getAnthropicClient};