const crypto=require('crypto');
const {query}=require('../config/database');
const logger=require('./logger');
const telegramMtproto=require('./telegramMtproto');
const TIMEOUT_MS=15000;
const INCIDENT_TERMS='protest OR protests OR rally OR demonstration OR fire OR explosion OR gunfire OR shooting OR attack OR attacked OR ambush OR kidnapping OR abduction OR IED OR bomb OR accident OR crash OR collision OR traffic OR roadblock OR unrest OR riot OR robbery OR flooding OR landslide';
const GEO_TERMS='Kenya OR Nairobi OR Mombasa OR Kisumu OR Nakuru OR Eldoret OR Garissa OR Mandera OR Somalia OR Tanzania OR Uganda OR Rwanda OR Burundi OR DRC OR Congo OR Ethiopia OR South Sudan';
function sha(v){return crypto.createHash('sha256').update(String(v||'')).digest('hex');}
function clean(v,n=6000){return String(v||'').replace(/\s+/g,' ').trim().slice(0,n);}
function category(text){const s=String(text||'').toLowerCase();if(/ied|improvised explosive|bomb|explosion/.test(s))return'ied';if(/armed attack|gunfire|shooting|ambush|militia|insurgent/.test(s))return'armed_attack';if(/protest|riot|unrest|demonstration|roadblock/.test(s))return'protest';if(/rally|political rally/.test(s))return'political_rally';if(/fire|blaze|burning/.test(s))return'fire';if(/traffic|congestion|road closed|gridlock/.test(s))return'traffic';if(/accident|crash|collision|overturned/.test(s))return'accident';if(/kidnap|abduct/.test(s))return'kidnapping';if(/flood|landslide|earthquake|storm/.test(s))return'natural_hazard';if(/robbery|carjacking|crime|mugging/.test(s))return'crime';return'other';}
function severity(cat,text){if(['ied','armed_attack','kidnapping'].includes(cat))return'high';if(['protest','political_rally','fire','accident','natural_hazard'].includes(cat))return'medium';return /death|dead|fatal|casualties|multiple injured/i.test(text)?'high':'low';}
function timeoutFetch(url,options={}){return fetch(url,{...options,signal:AbortSignal.timeout(TIMEOUT_MS)});}
async function ensureSource(orgId,name,provider,endpoint,reliability){const{rows}=await query(`INSERT INTO intel_sources (org_id,name,source_type,provider,endpoint,reliability,metadata,last_seen_at) VALUES ($1,$2,'social',$3,$4,$5,$6::jsonb,NOW()) ON CONFLICT (org_id,provider,endpoint) WHERE provider IS NOT NULL AND endpoint IS NOT NULL DO UPDATE SET last_seen_at=NOW(),updated_at=NOW() RETURNING *`,[orgId,name,provider,endpoint,reliability,JSON.stringify({role:'incident-alert-feed',collection:'near-real-time'})]);return rows[0];}
async function persistObservation(orgId,source,item){const title=clean(item.title||item.text,700),body=clean(item.text||item.body||title,7000),url=item.url||null,externalId=item.external_id||`${source.provider}:${sha(url||body)}`,observedAt=item.observed_at||new Date().toISOString(),cat=category(`${title} ${body}`),sev=severity(cat,`${title} ${body}`);const r=await query(`INSERT INTO intel_observations (org_id,source_id,external_id,observed_at,published_at,title,body,url,language,country_code,raw_metadata,credibility,manipulation_score) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb,$12,$13) ON CONFLICT (org_id,source_id,external_id) DO UPDATE SET last_seen_at=NOW() RETURNING id,title,body,url,observed_at,published_at,country_code,raw_metadata`,[orgId,source.id,externalId,observedAt,item.published_at||null,title,body,url,item.language||null,item.country_code||'KE',JSON.stringify({...item.raw_metadata,incident_category:cat,severity_hint:sev}),item.credibility||35,0]);return{row:r.rows[0],category:cat,severity:sev};}
async function materializeAlert(orgId,source,observation){const o=observation.row;if(!o?.id)return false;const title=clean(o.title||o.body,500),cat=observation.category,sev=observation.severity;const existing=await query(`SELECT id FROM intel_alerts WHERE org_id=$1 AND observation_id=$2 LIMIT 1`,[orgId,o.id]);if(existing.rows[0]){await query(`UPDATE intel_alerts SET last_seen_at=NOW(),updated_at=NOW() WHERE id=$1`,[existing.rows[0].id]);return false;}await query(`INSERT INTO intel_alerts (org_id,observation_id,source_id,category,title,summary,severity,confidence,verification_state,status,country_code,first_seen_at,last_seen_at,metadata) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,'unverified','open',$9,$10,$10,$11::jsonb)`,[orgId,o.id,source.id,cat,title,clean(o.body||title,1500),sev,source.provider==='x'?35:30,o.country_code||'KE',o.observed_at||new Date().toISOString(),JSON.stringify({source_provider:source.provider,source_reliability:source.reliability,evidence_boundary:'source observation; not independently verified'})]);return true;}
async function collectX(orgId){const token=process.env.X_BEARER_TOKEN||process.env.TWITTER_BEARER_TOKEN;if(!token)return{provider:'x',status:'disabled',seen:0,alerts:0};const q=`(${GEO_TERMS}) (${INCIDENT_TERMS}) -is:retweet`;const p=new URLSearchParams({query:q,max_results:'100',sort_order:'recency','tweet.fields':'created_at,lang,author_id,public_metrics,context_annotations,geo,entities'});const source=await ensureSource(orgId,'X Incident Monitor','x','https://api.x.com/2/tweets/search/recent',45);const r=await timeoutFetch(`https://api.x.com/2/tweets/search/recent?${p}`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error(`X API HTTP ${r.status}`);const d=await r.json();let alerts=0;for(const t of d.data||[]){const o=await persistObservation(orgId,source,{external_id:`x:${t.id}`,text:t.text,published_at:t.created_at,observed_at:t.created_at,language:t.lang,country_code:'KE',url:`https://x.com/i/web/status/${t.id}`,credibility:45,raw_metadata:{author_id:t.author_id,public_metrics:t.public_metrics,context_annotations:t.context_annotations,geo:t.geo}});if(await materializeAlert(orgId,source,o))alerts++;}return{provider:'x',status:'success',seen:(d.data||[]).length,alerts};}
async function collectBluesky(orgId){const source=await ensureSource(orgId,'Bluesky Incident Monitor','bluesky','https://public.api.bsky.app/xrpc/app.bsky.feed.searchPosts',35);const q=`Kenya ${INCIDENT_TERMS.split(' OR ').slice(0,10).join(' OR ')}`;const p=new URLSearchParams({q,limit:'100',sort:'latest',lang:'en'});const r=await timeoutFetch(`https://public.api.bsky.app/xrpc/app.bsky.feed.searchPosts?${p}`);if(!r.ok)throw new Error(`Bluesky API HTTP ${r.status}`);const d=await r.json();let alerts=0;for(const post of d.posts||[]){const text=post.record?.text||'';const uri=post.uri;const o=await persistObservation(orgId,source,{external_id:`bluesky:${sha(uri)}`,text,published_at:post.record?.createdAt,observed_at:post.record?.createdAt,url:uri,country_code:'KE',language:'en',credibility:35,raw_metadata:{author:post.author?.handle,uri}});if(await materializeAlert(orgId,source,o))alerts++;}return{provider:'bluesky',status:'success',seen:(d.posts||[]).length,alerts};}
async function collectTelegram(orgId){let channels=[];try{channels=JSON.parse(process.env.RISK_INTEL_TELEGRAM_CHANNELS||'[]')}catch{}if(!Array.isArray(channels)||!channels.length)return{provider:'telegram',status:'disabled',seen:0,alerts:0};const source=await ensureSource(orgId,'Telegram Incident Monitor','telegram','mtproto://configured-channels',40);const since=Date.now()-60*60*1000;let seen=0,alerts=0;for(const entry of channels.slice(0,40)){const channel=typeof entry==='string'?entry:entry?.channel;if(!channel)continue;try{const messages=await telegramMtproto.fetchChannelMessages(channel,since);for(const m of messages){const o=await persistObservation(orgId,source,{external_id:`telegram:${channel}:${m.id}`,text:m.text,published_at:new Date(m.postedAt).toISOString(),observed_at:new Date(m.postedAt).toISOString(),url:`https://t.me/${channel}/${String(m.id).split('/').pop()}`,country_code:(entry?.country_code)||'KE',credibility:Number(entry?.reliability)||40,raw_metadata:{channel,mtproto:true}});if(await materializeAlert(orgId,source,o))alerts++;seen++;}}catch(e){logger.warn(`Incident Alert Fabric: Telegram ${channel} failed: ${e.message}`);}}return{provider:'telegram',status:telegramMtproto.isConfigured()?'success':'disabled',seen,alerts};}
async function collectPersistedNewsAlerts(orgId){
  const {rows}=await query(`SELECT o.id,o.title,o.body,o.url,o.observed_at,o.published_at,o.country_code,o.raw_metadata,s.id AS source_id,s.name AS source_name,s.provider,s.reliability
    FROM intel_observations o JOIN intel_sources s ON s.id=o.source_id
    WHERE o.org_id=$1 AND o.observed_at >= NOW()-INTERVAL '2 hours'
      AND (lower(COALESCE(o.title,'')) ~ '(protest|rally|demonstration|fire|explosion|gunfire|shooting|attack|ambush|kidnap|abduct|ied|bomb|accident|crash|collision|traffic|roadblock|unrest|riot|robbery|flood|landslide)'
        OR lower(COALESCE(o.body,'')) ~ '(protest|rally|demonstration|fire|explosion|gunfire|shooting|attack|ambush|kidnap|abduct|ied|bomb|accident|crash|collision|traffic|roadblock|unrest|riot|robbery|flood|landslide)')
    ORDER BY o.observed_at DESC LIMIT 100`,[orgId]);
  const sourceById=new Map();let alerts=0;
  for(const row of rows){let source=sourceById.get(row.source_id);if(!source){source={id:row.source_id,name:row.source_name,provider:row.provider||'rss',reliability:Number(row.reliability)||60};sourceById.set(row.source_id,source);}const o={row:{id:row.id,title:row.title,body:row.body,url:row.url,observed_at:row.observed_at,published_at:row.published_at,country_code:row.country_code,raw_metadata:row.raw_metadata},category:category(`${row.title||''} ${row.body||''}`),severity:severity(category(`${row.title||''} ${row.body||''}`),`${row.title||''} ${row.body||''}`)};if(await materializeAlert(orgId,source,o))alerts++;}
  return{provider:'persisted_news',status:'success',seen:rows.length,alerts};
}
async function runIncidentAlertSweep(orgId){const results=[];for(const fn of [collectPersistedNewsAlerts,collectX,collectBluesky,collectTelegram]){try{results.push(await fn(orgId));}catch(e){logger.warn(`Incident Alert Fabric: ${e.message}`);results.push({provider:fn.name,status:'failed',seen:0,alerts:0,error:e.message});}}const total=results.reduce((s,r)=>s+(r.alerts||0),0);logger.info(`Incident Alert Fabric: org=${orgId} alerts=${total} ${JSON.stringify(results)}`);return{results,totalAlerts:total};}
module.exports={runIncidentAlertSweep,category,severity};
