'use strict';
const aiClient=require('../../utils/aiClient');
const logger=require('../../utils/logger');
const AGENTS=[
{id:'route_engineer',role:'ROAD NETWORK ENGINEER',mission:'Validate route geometry, connectivity, distance, duration and alternatives. Never invent roads.'},
{id:'security_analyst',role:'SECURITY THREAT ANALYST',mission:'Assess crime, conflict, banditry, kidnapping and hostile exposure from supplied evidence only.'},
{id:'environment_analyst',role:'ENVIRONMENT & WEATHER ANALYST',mission:'Assess weather, flooding, storm, visibility and natural-hazard effects from supplied evidence.'},
{id:'infrastructure_analyst',role:'INFRASTRUCTURE / ROAD CONDITIONS',mission:'Assess closures, construction, barriers, bottlenecks and border constraints.'},
{id:'operations_analyst',role:'CONVOY OPERATIONS ANALYST',mission:'Translate route evidence into convoy timing, staging, checkpoints and execution hazards.'},
{id:'data_assurance',role:'DATA ASSURANCE AGENT',mission:'Detect missing, stale, contradictory, low-confidence or invalid evidence.'},
{id:'red_team',role:'RED TEAM / ADVERSARIAL ROUTE REVIEW',mission:'Try to disprove the proposed route and expose unsafe assumptions and overconfidence.'},
];
const clip=(v,m)=>{const s=typeof v==='string'?v:JSON.stringify(v);return s.length>m?s.slice(0,m)+'…':s;};
function json(text){if(!text)return null;const c=String(text).replace(/```json|```/g,'').trim();try{return JSON.parse(c)}catch(_){}const a=c.indexOf('{'),b=c.lastIndexOf('}');if(a>=0&&b>a)try{return JSON.parse(c.slice(a,b+1))}catch(_){}return null;}
async function ask(system,user,max){const r=await aiClient.createMessage({max_tokens:max||1500,system,messages:[{role:'user',content:user}]});const text=(r.content||[]).filter(x=>x.type==='text').map(x=>x.text).join('\n').trim();return {provider:r._provider||'unknown',text,json:json(text)};}
async function runAgent(agent,input){
const system='You are '+agent.role+' inside Sonalit Route Safety. Mission: '+agent.mission+' Never invent coordinates, roads, incidents, weather or closures. Separate observed evidence from inference. Do not treat absence of evidence as safety. Return JSON only: {"status":"supported|uncertain","finding":"...","confidence":0,"risks":[{"risk":"...","severity":"low|medium|high|critical","evidence":"..."}],"actions":[{"action":"...","urgency":"now|soon|monitor"}],"contradictions":[],"evidence_gaps":[],"provenance":[]}';
try{const r=await ask(system,'ROUTE SAFETY INPUT:\n'+clip(input,15000),1500);const j=r.json;if(!j)return {...agent,provider:r.provider,status:'uncertain',finding:r.text||'No structured response',confidence:.15,risks:[],actions:[],contradictions:['Unstructured output'],evidence_gaps:['Structured output missing'],provenance:[]};return {...agent,provider:r.provider,status:j.status||'uncertain',finding:j.finding||'',confidence:Math.max(0,Math.min(1,Number(j.confidence??.3))),risks:j.risks||[],actions:j.actions||[],contradictions:j.contradictions||[],evidence_gaps:j.evidence_gaps||[],provenance:j.provenance||[]};}
catch(e){return {...agent,provider:'failed',status:'unavailable',finding:'Agent unavailable',confidence:0,risks:[],actions:[],contradictions:[e.message],evidence_gaps:['Agent unavailable'],provenance:[]};}}
async function runSwarm(input){
const reports=await Promise.all(AGENTS.map(a=>runAgent(a,input)));const severity={low:1,medium:2,high:3,critical:4};const risks=new Map();
for(const r of reports)for(const x of r.risks||[]){const k=String(x.risk||'').toLowerCase().trim();if(!k)continue;const cur=risks.get(k)||{risk:x.risk,severity:x.severity,sources:[]};cur.sources.push(r.id);if((severity[x.severity]||1)>(severity[cur.severity]||1))cur.severity=x.severity;risks.set(k,cur);}
const available=reports.filter(r=>r.status==='supported'||r.status==='uncertain');const unavailable=reports.length-available.length;const critical=reports.some(r=>(r.risks||[]).some(x=>String(x.severity).toLowerCase()==='critical'));
let arbiter;try{const r=await ask('You are the SENIOR ROUTE SAFETY ARBITER for Sonalit. Reconcile independent specialist reports and deterministic route evidence. Never invent facts. Missing agents are unavailable evidence, not proof of danger. Flag disagreements. Return JSON: {"route_selection_reason":"...","risk_level":"LOW|MEDIUM|HIGH|CRITICAL","confidence":0,"material_risks":[{"risk":"...","severity":"low|medium|high|critical","evidence":"..."}],"actions":[{"action":"...","urgency":"now|soon|monitor","approval":"none|human"}],"go_no_go":"GO|CONDITIONAL|NO_GO|HUMAN_REVIEW","uncertainties":[],"dissent":[]}',clip(JSON.stringify({input,reports}),28000),2200);arbiter=r.json;if(!arbiter)throw new Error('Arbiter returned invalid structured output');arbiter.provider=r.provider;}catch(e){logger.warn('Route Safety arbiter unavailable: '+e.message);arbiter={route_selection_reason:'Arbitration unavailable; operator review required.',risk_level:'HIGH',confidence:.2,material_risks:[],actions:[],go_no_go:'HUMAN_REVIEW',uncertainties:['Arbiter unavailable'],dissent:[],provider:'failed'};}
let critic;try{critic=await runAgent({id:'route_critic',role:'FINAL ROUTE SAFETY AUDITOR',mission:'Attack the arbitration and find hidden unsafe assumptions.'},{route_evidence:input,arbiter,reports});}catch(e){critic={id:'route_critic',provider:'failed',status:'unavailable',finding:'Critic unavailable',confidence:0,risks:[],actions:[],contradictions:[e.message],evidence_gaps:['Critic unavailable'],provenance:[]};}
const hardBlock=critical||available.length===0||arbiter.go_no_go==='NO_GO';if(critical||arbiter.go_no_go==='NO_GO')arbiter.go_no_go='HUMAN_REVIEW';
const confs=available.map(r=>Number(r.confidence)).filter(Number.isFinite);const mean=confs.length?confs.reduce((a,b)=>a+b,0)/confs.length:0;const finalConfidence=Number(((Number(arbiter.confidence||mean||0)*.6)+(mean*.4)).toFixed(2));
return {version:'route-safety-swarm-v2',agent_count:reports.length+2,reports,arbiter,critic,aggregated_risks:Array.from(risks.values()),consensus:{confidence:finalConfidence,hard_block:hardBlock,available_agents:available.length,unavailable_agents:unavailable,coverage:Number((available.length/reports.length).toFixed(2))}};
}
module.exports={AGENTS,runSwarm};