import { useEffect, useMemo, useState } from 'react'
import { api } from '../../../lib/api.js'

type Tab = 'warnings'|'storylines'|'forecasts'|'gaps'|'quality'
const tabs: {id:Tab;label:string}[]=[{id:'warnings',label:'Early Warning'},{id:'storylines',label:'Storylines'},{id:'forecasts',label:'Forecasts'},{id:'gaps',label:'Collection Gaps'},{id:'quality',label:'Quality'}]
const tone=(s:string)=>s==='critical'||s==='high'?'#E24B4A':s==='moderate'||s==='medium'?'#F0B429':'#7DCEA0'
export default function IntelligenceOperations(){
 const [tab,setTab]=useState<Tab>('warnings'); const [data,setData]=useState<any>({}); const [loading,setLoading]=useState(true)
 const load=async()=>{setLoading(true);try{const paths=['early-warnings','ops/storylines','ops/forecasts','ops/gaps','ops/quality'];const res=await Promise.all(paths.map(p=>api.get(`/intelligence/${p}`)));setData({warnings:res[0].data.warnings||[],storylines:res[1].data.storylines||[],forecasts:res[2].data.forecasts||[],gaps:res[3].data.gaps||[],quality:res[4].data.quality||{}})}finally{setLoading(false)}}
 useEffect(()=>{load()},[]); const items=useMemo(()=>data[tab]||[],[data,tab])
 return <section style={{borderTop:'1px solid rgba(255,255,255,.07)',background:'#0b1420',padding:'14px 16px',fontFamily:'Inter,system-ui,sans-serif'}}><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:12,marginBottom:12}}><div><div style={{fontFamily:'IBM Plex Mono,monospace',fontSize:10,letterSpacing:'.14em',textTransform:'uppercase',color:'#F0B429'}}>Intelligence Operations</div><div style={{fontSize:11,color:'#666e79',marginTop:3}}>Evidence-led warning, collection and analytic tradecraft</div></div><button onClick={load} style={{background:'rgba(255,255,255,.04)',border:'1px solid rgba(255,255,255,.08)',color:'#9aa2ad',borderRadius:5,padding:'5px 9px',fontSize:10,cursor:'pointer'}}>Sync</button></div><div style={{display:'flex',gap:5,overflowX:'auto',paddingBottom:8}}>{tabs.map(t=><button key={t.id} onClick={()=>setTab(t.id)} style={{whiteSpace:'nowrap',padding:'6px 9px',borderRadius:5,border:`1px solid ${tab===t.id?'rgba(240,180,41,.35)':'rgba(255,255,255,.07)'}`,background:tab===t.id?'rgba(240,180,41,.10)':'transparent',color:tab===t.id?'#F0B429':'#737c88',fontSize:10,cursor:'pointer'}}>{t.label}</button>)}</div>{loading?<div style={{padding:24,color:'#59616c',fontSize:11}}>Synchronising intelligence layer…</div>:tab==='quality'?<Quality q={data.quality}/>:<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:8,maxHeight:260,overflow:'auto'}}>{items.length===0?<div style={{padding:20,color:'#59616c',fontSize:11}}>No intelligence records in this view.</div>:items.map((x:any,i:number)=><div key={x.id||x.reference||i} style={{border:'1px solid rgba(255,255,255,.06)',background:'rgba(255,255,255,.018)',borderRadius:7,padding:11}}><div style={{display:'flex',justifyContent:'space-between',gap:8}}><span style={{fontFamily:'IBM Plex Mono,monospace',fontSize:9,color:'#69727d'}}>{x.reference||x.warning_type||x.gap_type||x.horizon||'INTEL'}</span><span style={{fontSize:9,textTransform:'uppercase',color:tone(x.severity||x.priority||x.status||'low')}}>{x.severity||x.priority||x.status||'active'}</span></div><div style={{fontSize:12,color:'#e5e8ec',fontWeight:600,marginTop:7}}>{x.headline||x.title||x.scenario||'Intelligence item'}</div><div style={{fontSize:10,color:'#77808b',lineHeight:1.45,marginTop:5}}>{x.summary||x.description||x.judgement||x.recommended_action||'Evidence record available in the intelligence layer.'}</div>{x.confidence!=null&&<div style={{marginTop:8,fontFamily:'IBM Plex Mono,monospace',fontSize:9,color:'#929aa5'}}>CONFIDENCE {Math.round(Number(x.confidence))}%</div>}</div>)}</div>}</section>
}
function Quality({q}:any){const vals=[['OBS 30D',q.observations_30d],['SOURCES',q.sources_30d],['AVG CRED',q.avg_credibility],['MANIP FLAGS',q.manipulation_flags],['EVENTS 30D',q.events_30d],['AVG CONF',q.avg_event_confidence],['OPEN GAPS',q.open_gaps]];return <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(100px,1fr))',gap:7}}>{vals.map(([k,v])=><div key={String(k)} style={{border:'1px solid rgba(255,255,255,.06)',borderRadius:6,padding:'10px 8px'}}><div style={{fontFamily:'IBM Plex Mono,monospace',fontSize:8,color:'#68717c'}}>{k}</div><div style={{fontFamily:'IBM Plex Mono,monospace',fontSize:16,color:'#e7eaee',marginTop:5}}>{v??'—'}</div></div>)}</div>}
