import React, { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Activity, AlertTriangle, ArrowRight, Bell, CheckCircle2, ExternalLink, FileText, Link2, Loader2, MapPin, Package, RefreshCw, Search, ShieldCheck, Truck, Users } from 'lucide-react';
import { api } from '../lib/api.js';
import { CargoClientsPanel } from './CargoClientsPanel.js';

interface Convoy { id:string; reference:string; status:string; origin:string; destination:string; estimated_arrival_at?:string|null; seal_intact?:boolean|null }
interface Token { id:string; convoy_id:string; cargo_owner_ref:string|null; issued_at:string; expires_at:string; last_used_at:string|null; revoked_at:string|null; issued_by_name:string|null }

const fmt=(v:string|null|undefined)=>v?new Date(v).toLocaleString('en-ZA',{dateStyle:'medium',timeStyle:'short'}):'—';
const active=(c:Convoy)=>['active','in_transit','pending'].includes(c.status);
const tokenActive=(t:Token)=>!t.revoked_at&&new Date(t.expires_at)>new Date();

function Metric({label,value,detail,icon:Icon,tone='orange'}:{label:string;value:React.ReactNode;detail:string;icon:React.ElementType;tone?:'orange'|'green'|'red'|'blue'}) {
 const c={orange:'text-orange-300 border-orange-500/20',green:'text-emerald-300 border-emerald-500/20',red:'text-red-300 border-red-500/20',blue:'text-sky-300 border-sky-500/20'}[tone];
 return <div className={\`rounded-2xl border bg-white/[.018] p-4 \${c}\`}><div className="flex justify-between"><div><p className="text-[10px] uppercase tracking-[.18em] text-white/30">{label}</p><p className="mono mt-2 text-3xl text-white">{value}</p><p className="mt-1 text-[11px] text-white/25">{detail}</p></div><Icon size={17}/></div></div>;
}

function ConvoyCard({convoy,onIssue,onOpen}:{convoy:Convoy;onIssue:()=>void;onOpen:()=>void}) {
 const needs=convoy.seal_intact===false;
 return <div className={\`rounded-2xl border p-4 transition-all hover:border-orange-500/25 \${needs?'border-red-500/20 bg-red-500/[.025]':'border-white/[.07] bg-white/[.012]'}\`}>
   <div className="flex items-start gap-3"><div className={\`h-10 w-10 rounded-xl border flex items-center justify-center \${needs?'border-red-500/20 bg-red-500/10':'border-orange-500/20 bg-orange-500/10'}\`}><Truck size={17} className={needs?'text-red-400':'text-orange-400'}/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold text-white truncate">{convoy.reference}</p>{needs?<span className="text-[10px] rounded-full border border-red-500/20 bg-red-500/10 px-2 py-1 text-red-300">SEAL ATTENTION</span>:<span className="text-[10px] rounded-full border border-emerald-500/20 bg-emerald-500/10 px-2 py-1 text-emerald-300">SECURE</span>}</div><p className="mt-1 text-xs text-white/35 truncate">{convoy.origin} → {convoy.destination}</p></div></div>
   <div className="mt-4 grid grid-cols-3 gap-2 text-[10px]"><div className="rounded-lg border border-white/[.05] p-2"><span className="block text-white/20">Status</span><span className="mt-1 block text-white/60">{convoy.status.replace(/_/g,' ')}</span></div><div className="rounded-lg border border-white/[.05] p-2"><span className="block text-white/20">ETA</span><span className="mono mt-1 block text-white/60">{fmt(convoy.estimated_arrival_at)}</span></div><div className="rounded-lg border border-white/[.05] p-2"><span className="block text-white/20">Seal</span><span className={\`mt-1 block \${needs?'text-red-300':convoy.seal_intact?'text-emerald-300':'text-amber-300'}\`}>{convoy.seal_intact?'Intact':needs?'Compromised':'Unverified'}</span></div></div>
   <div className="mt-4 flex gap-2"><button onClick={onOpen} className="flex-1 rounded-xl border border-white/[.07] px-3 py-2 text-xs font-semibold text-white/55 hover:text-white">Open shipment</button><button onClick={onIssue} className="flex-1 rounded-xl bg-orange-600 px-3 py-2 text-xs font-semibold text-white hover:bg-orange-500"><Link2 size={12} className="mr-1 inline"/>Grant portal</button></div>
 </div>;
}

function QuickActions() {
 const actions=[['Client workspaces','Provision, inspect and manage customer visibility.','clients',Users],['Shipment intelligence','Open the customer-safe shipment operating picture.','portal',MapPin],['Evidence centre','Review documents, custody and POD from the customer scope.','portal',FileText],['Communication control','Configure customer notifications and Client Pulse.','clients',Bell]];
 return <div className="grid grid-cols-1 md:grid-cols-2 gap-3">{actions.map(([title,desc,kind,Icon])=><div key={String(title)} className="rounded-2xl border border-white/[.07] bg-white/[.012] p-4"><div className="flex items-center gap-2"><Icon size={15} className="text-orange-400"/><p className="text-sm font-semibold text-white/80">{title}</p></div><p className="mt-2 text-[11px] leading-relaxed text-white/30">{desc}</p><p className="mt-3 text-[10px] uppercase tracking-[.16em] text-orange-300/60">Available in {kind==='clients'?'Clients':'customer workspace'} view</p></div>)}</div>;
}

export default function CargoPortalControlTower():React.ReactElement {
 const qc=useQueryClient(); const [view,setView]=useState<'overview'|'clients'|'access'>('overview'); const [search,setSearch]=useState(''); const [showIssue,setShowIssue]=useState(false); const [selectedConvoy,setSelectedConvoy]=useState('');
 const convoysQuery=useQuery<{data:Convoy[]}>({queryKey:['cargo-portal-control-convoys'],queryFn:()=>api.get('/convoys?status=active&limit=200').then(r=>r.data)});
 const convoys=convoysQuery.data?.data??[]; const filtered=useMemo(()=>convoys.filter(c=>!search.trim()||[c.reference,c.origin,c.destination].some(v=>v.toLowerCase().includes(search.toLowerCase()))),[convoys,search]);
 const tokensQuery=useQuery<{data:Token[]}>({queryKey:['cargo-portal-control-tokens',selectedConvoy],queryFn:()=>api.get('/portal/tokens?convoy_id='+encodeURIComponent(selectedConvoy)).then(r=>r.data),enabled:!!selectedConvoy});
 const tokens=tokensQuery.data?.data??[]; const grantable=convoys.find(c=>c.id===selectedConvoy);
 const tokenActiveCount=tokens.filter(tokenActive).length;
 const issue=useMutation({mutationFn:()=>api.post('/portal/tokens',{convoy_id:selectedConvoy,cargo_owner_ref:'',ttl_hours:24}),onSuccess:()=>{setShowIssue(false);void qc.invalidateQueries({queryKey:['cargo-portal-control-tokens',selectedConvoy]})}});
 const secure=convoys.filter(c=>c.seal_intact===true).length; const attention=convoys.filter(c=>c.seal_intact===false).length;
 return <div className="max-w-[1480px] mx-auto px-4 sm:px-6 xl:px-8 py-6 space-y-5">
  <section className="rounded-3xl border border-orange-500/15 overflow-hidden" style={{background:'radial-gradient(circle at 86% 10%,rgba(249,115,22,.12),transparent 34%),linear-gradient(135deg,rgba(255,255,255,.035),rgba(255,255,255,.008))'}}>
   <div className="p-5 sm:p-7 flex flex-col xl:flex-row xl:items-end justify-between gap-5"><div><p className="text-[10px] uppercase tracking-[.24em] text-orange-300/70">SONALIT · Cargo Owner Control Tower</p><h1 className="mt-2 text-3xl sm:text-4xl font-semibold tracking-tight text-white">Customer cargo visibility, engineered as an operating system.</h1><p className="mt-3 max-w-3xl text-sm leading-relaxed text-white/40">One administrative surface for customer identities, shipment visibility grants, access health, communication control and the customer-safe operational workspace.</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>void convoysQuery.refetch()} className="rounded-xl border border-white/[.08] px-3 py-2 text-xs text-white/50 hover:text-white"><RefreshCw size={12} className="mr-1 inline"/>Refresh</button><button onClick={()=>setView('clients')} className="rounded-xl bg-orange-600 px-3 py-2 text-xs font-semibold text-white"><Users size={12} className="mr-1 inline"/>Manage clients</button></div></div>
  </section>
  <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><Metric label="Live movements" value={convoys.length} detail="Active convoy universe" icon={Truck} tone="green"/><Metric label="Secure cargo" value={secure} detail="Reporting intact seals" icon={ShieldCheck} tone="green"/><Metric label="Attention" value={attention} detail="Seal integrity exceptions" icon={AlertTriangle} tone={attention?'red':'orange'}/><Metric label="Access links" value={tokenActiveCount} detail={selectedConvoy?'Active for selected convoy':'Select a movement below'} icon={Link2} tone="blue"/></div>
  <div className="flex flex-wrap rounded-xl border border-white/[.07] bg-white/[.012] p-1 w-fit"><button onClick={()=>setView('overview')} className={\`rounded-lg px-4 py-2 text-xs font-semibold \${view==='overview'?'bg-orange-500 text-white':'text-white/40'}\`}>Control Tower</button><button onClick={()=>setView('clients')} className={\`rounded-lg px-4 py-2 text-xs font-semibold \${view==='clients'?'bg-orange-500 text-white':'text-white/40'}\`}>Client 360</button><button onClick={()=>setView('access')} className={\`rounded-lg px-4 py-2 text-xs font-semibold \${view==='access'?'bg-orange-500 text-white':'text-white/40'}\`}>Access Control</button></div>

  {view==='clients'&&<CargoClientsPanel convoys={convoys}/>}
  {view==='overview'&&<><section className="grid grid-cols-1 lg:grid-cols-[minmax(0,1fr)_330px] gap-4"><div><div className="rounded-2xl border border-white/[.07] overflow-hidden bg-white/[.012]"><div className="p-4 border-b border-white/[.06] flex flex-col md:flex-row md:items-center justify-between gap-3"><div><p className="text-[10px] uppercase tracking-[.18em] text-white/30">Movement board</p><p className="mt-1 text-sm font-semibold text-white/75">{filtered.length} active movement{filtered.length===1?'':'s'}</p></div><div className="relative w-full md:w-72"><Search size={13} className="absolute left-3 top-1/2 -translate-y-1/2 text-white/25"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search reference or route…" className="w-full rounded-xl border border-white/[.07] bg-black/10 py-2 pl-8 pr-3 text-xs text-white placeholder-white/20 outline-none focus:border-orange-500/30"/></div></div><div className="p-4 grid grid-cols-1 xl:grid-cols-2 gap-3">{filtered.map(c=><ConvoyCard key={c.id} convoy={c} onOpen={()=>window.open('/portal/convoy/'+c.id+'/track','_blank')} onIssue={()=>{setSelectedConvoy(c.id);setShowIssue(true)}}/>)}{!filtered.length&&<div className="col-span-full py-12 text-center text-xs text-white/25">No active movements match the current filter.</div>}</div></div></div><QuickActions/></section></>}
  {view==='access'&&<section className="rounded-2xl border border-white/[.07] bg-white/[.012]"><div className="p-4 border-b border-white/[.06]"><p className="text-[10px] uppercase tracking-[.18em] text-white/30">Scoped portal access</p><p className="mt-1 text-sm text-white/60">Select a movement to inspect and rotate its legacy bearer-token access grants.</p></div><div className="p-4 grid grid-cols-1 lg:grid-cols-[320px_1fr] gap-4"><div className="space-y-2">{convoys.map(c=><button key={c.id} onClick={()=>setSelectedConvoy(c.id)} className={\`w-full text-left rounded-xl border p-3 \${selectedConvoy===c.id?'border-orange-500/30 bg-orange-500/[.05]':'border-white/[.06] bg-white/[.012]'}\`}><p className="text-xs font-semibold text-white">{c.reference}</p><p className="mt-1 text-[11px] text-white/30 truncate">{c.origin} → {c.destination}</p></button>)}</div><div className="rounded-xl border border-white/[.06] p-4">{!selectedConvoy?<div className="py-12 text-center"><Link2 size={26} className="mx-auto text-white/10"/><p className="mt-3 text-xs text-white/30">Choose a movement.</p></div>:<><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-white">{grantable?.reference}</p><p className="text-[11px] text-white/30">{tokenActiveCount} active access token{tokenActiveCount===1?'':'s'}</p></div><button onClick={()=>setShowIssue(true)} className="rounded-xl bg-orange-600 px-3 py-2 text-xs font-semibold text-white">Issue token</button></div><div className="mt-4 space-y-2">{tokens.map(t=><div key={t.id} className="rounded-xl border border-white/[.06] p-3 flex items-center justify-between gap-3"><div><p className="text-xs text-white/70">{t.cargo_owner_ref||'Unlabelled cargo owner access'}</p><p className="mt-1 text-[10px] text-white/25">Expires {fmt(t.expires_at)} · {t.last_used_at?'Used '+fmt(t.last_used_at):'Not used yet'}</p></div><span className={\`text-[10px] rounded-full border px-2 py-1 \${tokenActive(t)?'border-emerald-500/20 bg-emerald-500/10 text-emerald-300':'border-white/10 text-white/30'}\`}>{tokenActive(t)?'ACTIVE':t.revoked_at?'REVOKED':'EXPIRED'}</span></div>)}{!tokens.length&&<p className="py-8 text-center text-xs text-white/25">No tokens issued for this movement.</p>}</div></>}</div></div></section>}

  {showIssue&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm"><div className="w-full max-w-md rounded-2xl border border-white/10 bg-[#0b1221] p-6"><p className="text-[10px] uppercase tracking-[.18em] text-orange-300/60">Access provisioning</p><h2 className="mt-1 text-lg font-semibold text-white">Issue customer portal access</h2><p className="mt-2 text-xs leading-relaxed text-white/35">This creates a 24-hour read-only bearer token scoped to the selected movement.</p><div className="mt-4 rounded-xl border border-white/[.06] bg-white/[.02] p-3 text-xs text-white/60">{grantable?.reference||selectedConvoy}</div>{issue.isError&&<p className="mt-3 text-xs text-red-300">Token issuance failed. Check the movement and operator permissions.</p>}<div className="mt-5 flex justify-end gap-2"><button onClick={()=>setShowIssue(false)} className="rounded-xl border border-white/10 px-4 py-2 text-sm text-white/45">Cancel</button><button onClick={()=>issue.mutate()} disabled={!selectedConvoy||issue.isPending} className="flex items-center gap-2 rounded-xl bg-orange-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{issue.isPending?<Loader2 size={13} className="animate-spin"/>:<Link2 size={13}/>}Issue access</button></div></div></div>}
 </div>;
}
