import React, { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { CheckCircle2, Copy, Link, Loader2, Mail, Plus, Shield, Users, Bell, Send } from 'lucide-react';
import { api } from '../lib/api.js';

interface CargoClient { id:string; email:string; name:string; company:string|null; last_login_at:string|null; created_at:string; }
interface Convoy { id:string; reference:string; origin:string; destination:string; }
interface EmailRecipient { id:string; email:string; name:string|null; company:string|null; enabled:boolean; sonalit_operational:boolean; sonalit_security:boolean; cds_client_pulse:boolean; }
function fmt(val:string|null):string { if(!val)return 'Never'; return new Date(val).toLocaleString('en-ZA',{dateStyle:'medium',timeStyle:'short'}); }

function CreateClientModal({onClose,onCreated}:{onClose:()=>void;onCreated:(c:CargoClient)=>void}) {
  const [form,setForm]=useState({email:'',name:'',company:''}); const [err,setErr]=useState('');
  const mutation=useMutation({mutationFn:()=>api.post<{data:CargoClient}>('/portal/clients',form),onSuccess:r=>onCreated(r.data.data),onError:(e:unknown)=>setErr((e as {response?:{data?:{error?:string}}}).response?.data?.error??'Failed')});
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm"><div className="w-full max-w-md rounded-xl border border-white/10 p-6" style={{background:'rgba(13,20,38,0.98)'}}><h2 className="text-lg font-bold text-white mb-4 flex items-center gap-2"><Plus size={16} className="text-orange-400"/> New Cargo Client</h2>{err&&<div className="mb-3 rounded border border-red-700 bg-red-900/30 px-3 py-2 text-xs text-red-400">{err}</div>}<div className="space-y-3">{(['email','name','company'] as const).map(f=><div key={f}><label className="block text-xs text-gray-400 mb-1 capitalize">{f}{f==='company'?' (optional)':''}</label><input type={f==='email'?'email':'text'} value={form[f]} onChange={e=>setForm(p=>({...p,[f]:e.target.value}))} className="w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm text-white"/></div>)}</div><div className="mt-3 rounded-lg border border-white/10 bg-white/[.03] p-3 text-xs text-gray-400">After creation, configure exactly which Sonalit and CDS emails this client receives from the notification controls on the client row.</div><div className="flex gap-3 mt-5"><button onClick={onClose} className="flex-1 rounded-lg border border-white/10 py-2 text-sm text-gray-400 hover:text-white">Cancel</button><button onClick={()=>mutation.mutate()} disabled={!form.email||!form.name||mutation.isPending} className="flex-1 rounded-lg bg-orange-600 hover:bg-orange-500 disabled:opacity-50 py-2 text-sm font-semibold text-white flex items-center justify-center gap-2">{mutation.isPending?<Loader2 size={13} className="animate-spin"/>:<Plus size={13}/>} Create</button></div></div></div>;
}

function LinkConvoyModal({client,convoys,onClose,onLinked}:{client:CargoClient;convoys:Convoy[];onClose:()=>void;onLinked:()=>void}) {
  const [convoyId,setConvoyId]=useState(convoys[0]?.id??''); const [showValue,setShowValue]=useState(false); const [err,setErr]=useState('');
  const mutation=useMutation({mutationFn:()=>api.post(`/portal/clients/${client.id}/links`,{convoy_id:convoyId,show_value:showValue}),onSuccess:onLinked,onError:(e:unknown)=>setErr((e as {response?:{data?:{error?:string}}}).response?.data?.error??'Failed')});
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm"><div className="w-full max-w-md rounded-xl border border-white/10 p-6" style={{background:'rgba(13,20,38,0.98)'}}><h2 className="text-lg font-bold text-white mb-1">Link Convoy</h2><p className="text-xs text-gray-500 mb-4">Grant <span className="text-white/80">{client.name}</span> access to a convoy</p>{err&&<div className="mb-3 rounded border border-red-700 bg-red-900/30 px-3 py-2 text-xs text-red-400">{err}</div>}<div className="space-y-3"><div><label className="block text-xs text-gray-400 mb-1">Convoy</label><select value={convoyId} onChange={e=>setConvoyId(e.target.value)} className="w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm text-white">{convoys.map(c=><option key={c.id} value={c.id}>{c.reference} — {c.origin} → {c.destination}</option>)}</select></div><label className="flex items-center gap-2 text-xs text-gray-400 cursor-pointer"><input type="checkbox" checked={showValue} onChange={e=>setShowValue(e.target.checked)} className="rounded border-white/20"/> Show declared cargo value in manifest</label></div><div className="flex gap-3 mt-5"><button onClick={onClose} className="flex-1 rounded-lg border border-white/10 py-2 text-sm text-gray-400 hover:text-white">Cancel</button><button onClick={()=>mutation.mutate()} disabled={!convoyId||mutation.isPending} className="flex-1 rounded-lg bg-orange-600 hover:bg-orange-500 disabled:opacity-50 py-2 text-sm font-semibold text-white">{mutation.isPending?'Linking…':'Link'}</button></div></div></div>;
}

function EmailControls({client}:{client:CargoClient}) {
  const qc=useQueryClient();
  const {data,isLoading}=useQuery<{data:EmailRecipient[]}>({queryKey:['client-email-recipients'],queryFn:()=>api.get('/settings/email-recipients').then(r=>r.data)});
  const existing=data?.data?.find(r=>r.email.toLowerCase()===client.email.toLowerCase());
  const [editing,setEditing]=useState(false);
  const [form,setForm]=useState({enabled:true,sonalit_operational:true,sonalit_security:false,cds_client_pulse:true});
  const save=useMutation({mutationFn:()=>api.post<{data:EmailRecipient}>('/settings/email-recipients',{email:client.email,name:client.name,company:client.company,...form}),onSuccess:()=>{qc.invalidateQueries({queryKey:['client-email-recipients']});setEditing(false)}});
  React.useEffect(()=>{if(existing)setForm({enabled:existing.enabled,sonalit_operational:existing.sonalit_operational,sonalit_security:existing.sonalit_security,cds_client_pulse:existing.cds_client_pulse})},[existing?.id]);
  return <div className="mt-3 rounded-lg border border-white/[.07] bg-black/10 p-3"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><Bell size={12} className="text-orange-400"/><span className="text-[11px] font-semibold text-gray-300">EMAIL DELIVERY</span>{existing?.enabled?<span className="text-[10px] text-green-400">ACTIVE</span>:<span className="text-[10px] text-gray-600">NOT CONFIGURED</span>}</div><button onClick={()=>setEditing(v=>!v)} className="text-[10px] text-orange-400 hover:text-orange-300">{editing?'Close':'Configure'}</button></div>{editing&&<div className="mt-3 grid gap-2"><label className="flex items-center gap-2 text-[11px] text-gray-400"><input type="checkbox" checked={form.enabled} onChange={e=>setForm(p=>({...p,enabled:e.target.checked}))}/> Enable email delivery</label><label className="flex items-center gap-2 text-[11px] text-gray-400"><input type="checkbox" checked={form.sonalit_operational} onChange={e=>setForm(p=>({...p,sonalit_operational:e.target.checked}))}/> Sonalit operational alerts</label><label className="flex items-center gap-2 text-[11px] text-gray-400"><input type="checkbox" checked={form.sonalit_security} onChange={e=>setForm(p=>({...p,sonalit_security:e.target.checked}))}/> Sonalit security alerts</label><label className="flex items-center gap-2 text-[11px] text-gray-400"><input type="checkbox" checked={form.cds_client_pulse} onChange={e=>setForm(p=>({...p,cds_client_pulse:e.target.checked}))}/> CDS Client Pulse manifest</label><button onClick={()=>save.mutate()} disabled={save.isPending} className="mt-1 rounded-lg bg-orange-600 px-3 py-1.5 text-[11px] font-semibold text-white disabled:opacity-50">{save.isPending?'Saving…':'Save Email Rules'}</button></div>} {!editing&&existing&&<div className="mt-2 flex flex-wrap gap-1">{existing.sonalit_operational&&<span className="rounded bg-blue-500/10 px-2 py-1 text-[9px] text-blue-300">OPS</span>}{existing.sonalit_security&&<span className="rounded bg-red-500/10 px-2 py-1 text-[9px] text-red-300">SECURITY</span>}{existing.cds_client_pulse&&<span className="rounded bg-orange-500/10 px-2 py-1 text-[9px] text-orange-300">CDS PULSE</span>}</div>}</div>;
}

function ClientRow({client,convoys}:{client:CargoClient;convoys:Convoy[]}) {
  const [showLink,setShowLink]=useState(false); const [linkSent,setLinkSent]=useState(false); const [linkCopied,setLinkCopied]=useState(false); const [linkUrl,setLinkUrl]=useState<string|null>(null); const qc=useQueryClient();
  const sendLink=useMutation({mutationFn:()=>api.post('/portal/auth/request-link',{email:client.email}),onSuccess:()=>{setLinkSent(true);setTimeout(()=>setLinkSent(false),5000)}});
  const copyLink=useMutation({mutationFn:()=>api.post<{data:{url:string}}>(`/portal/clients/${client.id}/magic-link`,{}),onSuccess:res=>{const url=res.data.data.url;setLinkUrl(url);navigator.clipboard.writeText(url).then(()=>{setLinkCopied(true);setTimeout(()=>setLinkCopied(false),4000)})}});
  return <><div className="px-5 py-4 flex items-start gap-4"><div className="w-8 h-8 rounded-full bg-orange-500/10 border border-orange-500/20 flex items-center justify-center shrink-0 mt-0.5"><span className="text-xs font-bold text-orange-400">{client.name[0]?.toUpperCase()}</span></div><div className="flex-1 min-w-0"><p className="text-sm font-semibold text-white">{client.name}</p><p className="text-xs text-gray-500">{client.email}{client.company?` · ${client.company}`:''}</p><p className="text-xs text-gray-600 mt-0.5">Last login: {fmt(client.last_login_at)}</p><EmailControls client={client}/></div><div className="flex flex-col items-end gap-1.5 shrink-0"><div className="flex items-center gap-1.5"><button onClick={()=>setShowLink(true)} className="flex items-center gap-1 px-2 py-1 rounded-lg border border-white/10 text-xs text-gray-400 hover:text-orange-400 hover:border-orange-500/30 transition-all"><Shield size={11}/> Link Convoy</button><button onClick={()=>sendLink.mutate()} disabled={sendLink.isPending||linkSent} className="flex items-center gap-1 px-2 py-1 rounded-lg border border-white/10 text-xs text-gray-400 hover:text-blue-400 disabled:opacity-50" title="Send magic link email">{linkSent?<CheckCircle2 size={11} className="text-green-400"/>:<Mail size={11}/>} {linkSent?'Sent':'Email'}</button></div><button onClick={()=>copyLink.mutate()} disabled={copyLink.isPending} className="flex items-center gap-1 px-2 py-1 rounded-lg border text-xs transition-all disabled:opacity-50 w-full justify-center" style={linkCopied?{borderColor:'rgba(34,197,94,.4)',color:'#4ade80',background:'rgba(34,197,94,.08)'}:{borderColor:'rgba(249,115,22,.3)',color:'#fb923c',background:'rgba(249,115,22,.08)'}}>{copyLink.isPending?<Loader2 size={11} className="animate-spin"/>:linkCopied?<CheckCircle2 size={11}/>:<Copy size={11}/>} {linkCopied?'Copied!':'Copy Login Link'}</button></div></div>{linkUrl&&linkCopied&&<div className="mx-5 mb-3 flex items-center gap-2 rounded-lg border border-orange-500/20 bg-orange-500/05 px-3 py-2"><Link size={11} className="text-orange-400 shrink-0"/><code className="flex-1 text-[10px] text-orange-200 break-all">{linkUrl}</code></div>}{showLink&&<LinkConvoyModal client={client} convoys={convoys} onClose={()=>setShowLink(false)} onLinked={()=>{setShowLink(false);void qc.invalidateQueries({queryKey:['portal-clients']})}}/>}</>;
}

export function CargoClientsPanel({convoys}:{convoys:Convoy[]}):React.ReactElement {
  const [showCreate,setShowCreate]=useState(false); const qc=useQueryClient(); const {data,isLoading}=useQuery<{data:CargoClient[]}>({queryKey:['portal-clients'],queryFn:()=>api.get('/portal/clients').then(r=>r.data)}); const clients=data?.data??[];
  return <div><div className="flex items-center justify-between mb-4"><div className="flex items-center gap-2"><Users size={15} className="text-orange-400"/><p className="text-sm font-semibold text-white">Cargo Clients <span className="text-gray-600 font-normal">— V4 persistent accounts</span></p></div><button onClick={()=>setShowCreate(true)} className="flex items-center gap-1.5 rounded-lg bg-orange-600 hover:bg-orange-500 px-3 py-1.5 text-xs font-semibold text-white"><Plus size={12}/> New Client</button></div><div className="rounded-xl border border-white/[.07] overflow-hidden" style={{background:'rgba(13,20,38,.5)'}}>{isLoading&&<div className="p-6 text-center text-xs text-gray-500">Loading clients…</div>}{!isLoading&&clients.length===0&&<div className="p-8 text-center"><Users size={28} className="text-gray-700 mx-auto mb-2"/><p className="text-sm text-gray-500">No cargo clients yet</p><p className="text-xs text-gray-600 mt-1">Create a client account and configure its email delivery rules here.</p></div>}{clients.map((c,i)=><div key={c.id} className={i>0?'border-t border-white/[.05]':''}><ClientRow client={c} convoys={convoys}/></div>)}</div><div className="mt-4 rounded-lg border border-blue-700/30 bg-blue-900/10 px-4 py-3 text-xs text-blue-300/70 space-y-1"><p className="font-semibold text-blue-300">Client email routing</p><p>Use <strong>Email Delivery → Configure</strong> on each client to choose Sonalit operational alerts, Sonalit security alerts and CDS Client Pulse.</p><p>CDS Client Pulse is automatically suppressed when there are no active bookings.</p></div>{showCreate&&<CreateClientModal onClose={()=>setShowCreate(false)} onCreated={async c=>{setShowCreate(false);try{await api.post('/settings/email-recipients',{email:c.email,name:c.name,company:c.company,enabled:true,sonalit_operational:true,sonalit_security:false,cds_client_pulse:true})}finally{void qc.invalidateQueries({queryKey:['portal-clients']});void qc.invalidateQueries({queryKey:['client-email-recipients']})}}/>}</div>;
}
