import React, { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import Map, { Marker, NavigationControl, Source, Layer } from 'react-map-gl/maplibre';
import 'maplibre-gl/dist/maplibre-gl.css';
import { Activity, AlertTriangle, ArrowUpRight, Crosshair, FileText, Gauge, Layers3, Link2, Loader2, Map as MapIcon, Maximize2, Radio, RefreshCw, Search, ShieldCheck, Signal, Truck, Users, X, Zap } from 'lucide-react';
import { api } from '../lib/api.js';
import { CargoClientsPanel } from './CargoClientsPanelSafe.js';

type Convoy = { id: string; reference: string; status: string; origin: string; destination: string; estimated_arrival_at?: string | null; seal_intact?: boolean | null };
type Token = { id: string; convoy_id: string; cargo_owner_ref: string | null; issued_at: string; expires_at: string; last_used_at: string | null; revoked_at: string | null; issued_by_name: string | null };
type Session = { id: string; convoy_id?: string | null; health?: string; capability?: string; current_source?: string | null; last_location_at?: string | null; last_update_seconds?: number | null; status?: string };
type Fix = { lat: number; lng: number; accuracy_m?: number | null; speed_kph?: number | null; heading?: number | null; device_time: string; source?: string | null; buffered?: boolean; quality?: string };

type MapFix = Fix & { sessionId: string; convoyId?: string | null; convoy?: Convoy };

const fmt = (v?: string | null) => v ? new Date(v).toLocaleString('en-KE', { dateStyle: 'medium', timeStyle: 'short' }) : '—';
const age = (v?: string | null) => { if (!v) return 'NO FIX'; const sec = Math.max(0, Math.round((Date.now() - new Date(v).getTime()) / 1000)); if (sec < 60) return `${sec}s`; if (sec < 3600) return `${Math.floor(sec / 60)}m`; return `${Math.floor(sec / 3600)}h`; };
const activeStatus = (s?: string) => ['active', 'in_transit', 'moving', 'live', 'pending'].includes(String(s || '').toLowerCase());

const mapStyle = {
  version: 8,
  sources: {
    osm: { type: 'raster', tiles: ['https://tile.openstreetmap.org/{z}/{x}/{y}.png'], tileSize: 256, attribution: '© OpenStreetMap contributors' },
  },
  layers: [{ id: 'osm', type: 'raster', source: 'osm' }],
};

function Card({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <section className={`rounded-2xl border border-white/[.08] bg-[#0b121d]/90 shadow-[0_18px_60px_rgba(0,0,0,.22)] ${className}`}>{children}</section>; }
function Kpi({ label, value, note, icon: Icon, tone = 'orange' }: { label: string; value: React.ReactNode; note: string; icon: React.ElementType; tone?: 'orange' | 'green' | 'red' | 'blue' }) { const c = { orange: 'text-orange-300', green: 'text-emerald-300', red: 'text-red-300', blue: 'text-sky-300' }[tone]; return <div className="rounded-2xl border border-white/[.07] bg-white/[.025] p-4"><div className="flex items-start justify-between"><span className="text-[9px] font-semibold uppercase tracking-[.2em] text-white/30">{label}</span><Icon size={15} className={c}/></div><div className="mt-3 flex items-end gap-3"><strong className="font-mono text-3xl tracking-tight text-white">{value}</strong><span className="pb-1 text-[10px] text-white/25">{note}</span></div></div>; }
function Pill({ children, tone='neutral' }: { children: React.ReactNode; tone?: 'neutral'|'green'|'red'|'amber'|'blue' }) { const cls = { neutral:'border-white/10 bg-white/[.03] text-white/45', green:'border-emerald-400/20 bg-emerald-400/10 text-emerald-300', red:'border-red-400/20 bg-red-400/10 text-red-300', amber:'border-amber-400/20 bg-amber-400/10 text-amber-300', blue:'border-sky-400/20 bg-sky-400/10 text-sky-300' }[tone]; return <span className={`inline-flex items-center rounded-full border px-2.5 py-1 text-[9px] font-bold uppercase tracking-[.12em] ${cls}`}>{children}</span>; }

function MovementCard({ convoy, fix, selected, onSelect, onOpen, onGrant }: { convoy: Convoy; fix?: MapFix; selected: boolean; onSelect: () => void; onOpen: () => void; onGrant: () => void }) {
  const health = fix ? (fix.sessionId ? 'reporting' : 'unknown') : 'no fix';
  const attention = convoy.seal_intact === false;
  return <button type="button" onClick={onSelect} className={`w-full rounded-2xl border p-4 text-left transition ${selected ? 'border-orange-400/40 bg-orange-400/[.07]' : 'border-white/[.07] bg-white/[.018] hover:border-white/[.14]'}`}>
    <div className="flex items-start gap-3"><div className={`relative flex h-11 w-11 shrink-0 items-center justify-center rounded-xl border ${attention ? 'border-red-400/25 bg-red-400/10' : 'border-orange-400/20 bg-orange-400/10'}`}><Truck size={17} className={attention ? 'text-red-300' : 'text-orange-300'}/>{fix && <i className="absolute -right-1 -top-1 h-2.5 w-2.5 rounded-full bg-emerald-400 ring-2 ring-[#0b121d]"/>}</div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="truncate text-[13px] font-semibold text-white">{convoy.reference}</p><Pill tone={attention ? 'red' : fix ? 'green' : 'amber'}>{attention ? 'Seal alert' : fix ? 'GPS reporting' : 'No live fix'}</Pill></div><p className="mt-1 truncate text-[11px] text-white/35">{convoy.origin} <span className="text-white/15">→</span> {convoy.destination}</p></div><ArrowUpRight size={15} className="text-white/20"/></div>
    <div className="mt-4 grid grid-cols-3 gap-2"><div className="rounded-xl border border-white/[.06] bg-black/10 p-2.5"><span className="block text-[8px] uppercase tracking-[.14em] text-white/20">Position</span><strong className="mt-1 block font-mono text-[11px] text-white/60">{fix ? `${fix.lat.toFixed(4)}, ${fix.lng.toFixed(4)}` : 'Unavailable'}</strong></div><div className="rounded-xl border border-white/[.06] bg-black/10 p-2.5"><span className="block text-[8px] uppercase tracking-[.14em] text-white/20">Speed</span><strong className="mt-1 block font-mono text-[11px] text-white/60">{fix?.speed_kph != null ? `${Math.round(fix.speed_kph)} km/h` : '—'}</strong></div><div className="rounded-xl border border-white/[.06] bg-black/10 p-2.5"><span className="block text-[8px] uppercase tracking-[.14em] text-white/20">Last fix</span><strong className="mt-1 block font-mono text-[11px] text-white/60">{fix ? age(fix.device_time) : '—'}</strong></div></div>
    <div className="mt-3 flex items-center justify-between"><div className="flex items-center gap-2 text-[10px] text-white/25"><Signal size={12}/><span>{health}</span><span>•</span><span>{convoy.status.replace(/_/g,' ')}</span></div><div className="flex gap-1.5"><span role="button" tabIndex={0} onClick={e => { e.stopPropagation(); onOpen(); }} className="rounded-lg border border-white/[.07] px-2.5 py-1.5 text-[9px] font-semibold text-white/45">Shipment</span><span role="button" tabIndex={0} onClick={e => { e.stopPropagation(); onGrant(); }} className="rounded-lg bg-orange-500 px-2.5 py-1.5 text-[9px] font-semibold text-white">Access</span></div></div>
  </button>;
}

function LiveMap({ fixes, selectedId, onSelect, onFit, selectedTrack, mapFull, onFull }: { fixes: MapFix[]; selectedId: string; onSelect: (id:string)=>void; onFit: ()=>void; selectedTrack: Fix[]; mapFull: boolean; onFull: ()=>void }) {
  const center = fixes.length ? { longitude: fixes[0].lng, latitude: fixes[0].lat, zoom: 5.4 } : { longitude: 36.8219, latitude: -1.2921, zoom: 5.1 };
  const line = { type: 'Feature' as const, geometry: { type: 'LineString' as const, coordinates: selectedTrack.map(f => [f.lng, f.lat]) }, properties: {} };
  return <div className={`${mapFull ? 'fixed inset-4 z-[120]' : 'relative'} overflow-hidden rounded-2xl border border-white/[.08] bg-[#071019]`}>
    <Map initialViewState={center} mapStyle={mapStyle} style={{ width:'100%', height:'100%', minHeight: mapFull ? undefined : 600 }} attributionControl={false} interactiveLayerIds={[]}>
      <NavigationControl position="bottom-right" showCompass showZoom/>
      {selectedTrack.length > 1 && <Source id="selected-route" type="geojson" data={line}><Layer id="selected-route-line" type="line" paint={{ 'line-color':'#ff7a18', 'line-width':4, 'line-opacity':0.9, 'line-blur':0.3 }}/></Source>}
      {fixes.map((f,i)=><Marker key={`${f.sessionId}-${i}`} longitude={f.lng} latitude={f.lat} anchor="bottom"><button type="button" onClick={(e)=>{e.stopPropagation(); onSelect(f.sessionId)}} className="group relative flex h-11 w-11 items-center justify-center rounded-full border border-orange-300/60 bg-[#101b26]/95 shadow-[0_0_0_6px_rgba(249,115,22,.09),0_0_30px_rgba(249,115,22,.35)] transition hover:scale-110"><Truck size={17} className="text-orange-300"/><span className="absolute -bottom-6 whitespace-nowrap rounded bg-[#070d15]/95 px-1.5 py-1 text-[8px] font-semibold text-white/65 opacity-0 transition group-hover:opacity-100">{f.convoy?.reference || 'LIVE UNIT'}</span><i className="absolute inset-[-7px] rounded-full border border-orange-300/20 animate-ping"/></button></Marker>)}
    </Map>
    <div className="pointer-events-none absolute inset-x-0 top-0 p-3"><div className="flex items-start justify-between gap-3"><div className="rounded-xl border border-white/10 bg-[#071019]/90 px-3 py-2 backdrop-blur"><div className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-emerald-400"/><span className="text-[9px] font-bold uppercase tracking-[.18em] text-white/60">LIVE CARGO ATLAS</span><span className="text-[9px] text-white/25">{fixes.length} plotted</span></div></div><div className="pointer-events-auto flex gap-2"><button type="button" onClick={onFit} className="rounded-xl border border-white/10 bg-[#071019]/90 p-2 text-white/50 backdrop-blur hover:text-white"><Crosshair size={15}/></button><button type="button" onClick={onFull} className="rounded-xl border border-white/10 bg-[#071019]/90 p-2 text-white/50 backdrop-blur hover:text-white"><Maximize2 size={15}/></button></div></div></div>
    {fixes.length === 0 && <div className="pointer-events-none absolute inset-0 flex items-center justify-center"><div className="max-w-sm rounded-2xl border border-white/10 bg-[#071019]/92 p-6 text-center backdrop-blur-xl"><MapIcon size={24} className="mx-auto text-orange-300/70"/><p className="mt-3 text-sm font-semibold text-white">Map online · no telemetry fixes yet</p><p className="mt-2 text-[11px] leading-relaxed text-white/35">The map is live and interactive. It will plot actual Guardian / SecuriSat positions as soon as the selected movements have valid GPS observations.</p></div></div>}
    <div className="absolute bottom-3 left-3 rounded-xl border border-white/10 bg-[#071019]/90 px-3 py-2 text-[9px] text-white/35 backdrop-blur">© OpenStreetMap · Sonalit operational overlay</div>
  </div>;
}

export default function CargoPortalControlTowerSafe(): React.ReactElement {
  const qc = useQueryClient();
  const [view, setView] = useState<'overview'|'clients'|'access'>('overview');
  const [search, setSearch] = useState('');
  const [selectedConvoy, setSelectedConvoy] = useState('');
  const [selectedSession, setSelectedSession] = useState('');
  const [mapFull, setMapFull] = useState(false);
  const [issueOpen, setIssueOpen] = useState(false);

  const convoysQ = useQuery<{ data: Convoy[] }>({ queryKey:['cargo-control-convoys'], queryFn:()=>api.get('/convoys?status=active&limit=200').then(r=>r.data), refetchInterval:30000 });
  const sessionsQ = useQuery<{ data: Session[] }>({ queryKey:['cargo-control-sessions'], queryFn:()=>api.get('/tracking/sessions?active=true').then(r=>r.data), refetchInterval:15000 });
  const convoys = (convoysQ.data?.data || []).filter(c=>activeStatus(c.status));
  const sessions = sessionsQ.data?.data || [];
  const candidateSessions = sessions.filter(s=>s.convoy_id && convoys.some(c=>c.id===s.convoy_id)).slice(0,40);
  const locationsQ = useQuery({ queryKey:['cargo-control-latest-fixes', candidateSessions.map(s=>s.id).join('|')], enabled:candidateSessions.length>0, queryFn:async()=>{ const rows = await Promise.all(candidateSessions.map(async s=>{ try { const r=await api.get(`/tracking/sessions/${s.id}/locations?limit=1`); return { session:s, fix:r.data?.data?.[0] as Fix|undefined }; } catch { return {session:s,fix:undefined}; }})); return rows.filter(x=>x.fix); }, refetchInterval:15000 });
  const latest = locationsQ.data || [];
  const mapFixes: MapFix[] = latest.map((x:any)=>{ const convoy=convoys.find(c=>c.id===x.session.convoy_id); return {...x.fix, sessionId:x.session.id, convoyId:x.session.convoy_id, convoy}; }).filter((x:any)=>Number.isFinite(x.lat)&&Number.isFinite(x.lng));
  const selected = convoys.find(c=>c.id===selectedConvoy) || (mapFixes[0]?.convoy as Convoy|undefined);
  const selectedSessionObj = sessions.find(s=>s.id===selectedSession);
  const selectedMapFix = mapFixes.find(f=>f.sessionId===selectedSession || f.convoyId===selectedConvoy);
  const trackQ = useQuery<{ data: Fix[] }>({ queryKey:['cargo-control-track',selectedSessionObj?.id], queryFn:()=>api.get(`/tracking/sessions/${selectedSessionObj!.id}/locations?limit=1500`).then(r=>r.data), enabled:!!selectedSessionObj?.id && view==='overview' });
  const track = trackQ.data?.data || [];
  const filtered = useMemo(()=>convoys.filter(c=>`${c.reference} ${c.origin} ${c.destination}`.toLowerCase().includes(search.toLowerCase())),[convoys,search]);
  const attention = convoys.filter(c=>c.seal_intact===false).length;
  const noFix = convoys.filter(c=>!mapFixes.some(f=>f.convoyId===c.id)).length;
  const liveCount = mapFixes.length;
  const sources = [...new Set(mapFixes.map(f=>f.source).filter(Boolean))];
  const tokensQ = useQuery<{data:Token[]}>({queryKey:['cargo-control-tokens',selectedConvoy],queryFn:()=>api.get('/portal/tokens?convoy_id='+encodeURIComponent(selectedConvoy)).then(r=>r.data),enabled:!!selectedConvoy});
  const tokens=tokensQ.data?.data||[];
  const issue=useMutation({mutationFn:()=>api.post('/portal/tokens',{convoy_id:selectedConvoy,cargo_owner_ref:'',ttl_hours:24}),onSuccess:()=>{setIssueOpen(false);void qc.invalidateQueries({queryKey:['cargo-control-tokens',selectedConvoy]});}});

  const choose = (convoyId:string)=>{ setSelectedConvoy(convoyId); const f=mapFixes.find(x=>x.convoyId===convoyId); if(f)setSelectedSession(f.sessionId); };
  const openShipment=()=>{ if(selected?.id) window.open('/portal/convoy/'+selected.id+'/track','_blank'); };
  const refresh=()=>{ void convoysQ.refetch(); void sessionsQ.refetch(); void locationsQ.refetch(); };

  return <div className="min-h-full bg-[#050b12] text-white">
    <div className="mx-auto max-w-[1680px] space-y-4 px-4 py-5 sm:px-6 xl:px-8">
      <div className="flex flex-col gap-4 border-b border-white/[.07] pb-4 lg:flex-row lg:items-end lg:justify-between">
        <div><div className="flex items-center gap-2 text-[9px] font-bold uppercase tracking-[.24em] text-orange-300/65"><span className="h-1.5 w-1.5 rounded-full bg-orange-400"/> SONALIT / CARGO OWNER COMMAND</div><div className="mt-2 flex flex-wrap items-center gap-3"><h1 className="text-2xl font-semibold tracking-tight sm:text-3xl">Cargo Control Tower</h1><Pill tone="blue"><Radio size={10}/> {liveCount} live fixes</Pill><Pill tone={attention ? 'red':'green'}>{attention ? `${attention} security exception` : 'All visible seals nominal'}</Pill></div><p className="mt-2 max-w-3xl text-[12px] leading-relaxed text-white/35">A map-first cargo owner operating surface. Live position, movement health, custody exposure and customer access sit on the same screen.</p></div>
        <div className="flex flex-wrap gap-2"><button onClick={refresh} className="rounded-xl border border-white/10 bg-white/[.025] px-3 py-2 text-[10px] font-semibold text-white/55 hover:text-white"><RefreshCw size={12} className="mr-1.5 inline"/>Refresh telemetry</button><button onClick={()=>setView('clients')} className="rounded-xl bg-orange-500 px-3 py-2 text-[10px] font-semibold text-white"><Users size={12} className="mr-1.5 inline"/>Client 360</button></div>
      </div>

      <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Kpi label="LIVE MOVEMENTS" value={liveCount} note={`${convoys.length} active`} icon={Truck} tone="green"/><Kpi label="TELEMETRY COVERAGE" value={convoys.length?`${Math.round(liveCount/convoys.length*100)}%`:'—'} note={`${noFix} no fix`} icon={Signal} tone="blue"/><Kpi label="SEAL EXCEPTIONS" value={attention} note="requires review" icon={ShieldCheck} tone={attention?'red':'green'}/><Kpi label="PORTAL GRANTS" value={tokens.filter(t=>!t.revoked_at&&new Date(t.expires_at).getTime()>Date.now()).length} note={selected?'selected movement':'select a movement'} icon={Link2} tone="orange"/></div>

      <div className="flex flex-wrap gap-1 rounded-xl border border-white/[.07] bg-white/[.015] p-1"><button onClick={()=>setView('overview')} className={`rounded-lg px-4 py-2 text-[10px] font-bold uppercase tracking-[.13em] ${view==='overview'?'bg-orange-500 text-white':'text-white/35 hover:text-white'}`}>Control Tower</button><button onClick={()=>setView('clients')} className={`rounded-lg px-4 py-2 text-[10px] font-bold uppercase tracking-[.13em] ${view==='clients'?'bg-orange-500 text-white':'text-white/35 hover:text-white'}`}>Client 360</button><button onClick={()=>setView('access')} className={`rounded-lg px-4 py-2 text-[10px] font-bold uppercase tracking-[.13em] ${view==='access'?'bg-orange-500 text-white':'text-white/35 hover:text-white'}`}>Access Control</button></div>

      {view==='clients' && <CargoClientsPanel convoys={convoys}/>} 

      {view==='overview' && <div className="grid gap-4 xl:grid-cols-[minmax(0,1.55fr)_minmax(350px,.7fr)]">
        <Card className="overflow-hidden"><div className="flex flex-col gap-3 border-b border-white/[.07] p-4 md:flex-row md:items-center md:justify-between"><div><div className="flex items-center gap-2"><MapIcon size={15} className="text-orange-300"/><p className="text-[11px] font-bold uppercase tracking-[.16em] text-white/65">Live movement atlas</p></div><p className="mt-1 text-[10px] text-white/25">Actual tracking observations · click a unit to bind the intelligence rail</p></div><div className="relative w-full md:w-72"><Search size={13} className="absolute left-3 top-1/2 -translate-y-1/2 text-white/20"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find movement, route or reference" className="w-full rounded-xl border border-white/[.07] bg-black/15 py-2.5 pl-8 pr-3 text-[11px] text-white outline-none placeholder:text-white/20"/></div></div><div className="p-3"><LiveMap fixes={mapFixes} selectedId={selectedSession} onSelect={sid=>{setSelectedSession(sid);const f=mapFixes.find(x=>x.sessionId===sid);if(f)setSelectedConvoy(f.convoyId||'')}} onFit={()=>{ if(selectedSession) setSelectedSession(selectedSession)}} selectedTrack={track} mapFull={mapFull} onFull={()=>setMapFull(v=>!v)}/></div></Card>

        <div className="space-y-4">
          <Card><div className="border-b border-white/[.07] p-4"><div className="flex items-center justify-between"><div><p className="text-[9px] font-bold uppercase tracking-[.18em] text-orange-300/65">Selected movement</p><p className="mt-1 text-base font-semibold text-white">{selected?.reference || 'Select a live unit'}</p></div>{selected && <Pill tone={selected.seal_intact===false?'red':'green'}>{selected.seal_intact===false?'SEAL ATTENTION':'SECURE'}</Pill>}</div></div>{selected ? <div className="p-4"><div className="rounded-xl border border-white/[.06] bg-white/[.02] p-3"><div className="flex items-center gap-2 text-[11px] text-white/50"><MapPinIconPlaceholder/> {selected.origin} <span className="text-white/15">→</span> {selected.destination}</div><div className="mt-3 grid grid-cols-2 gap-2"><div className="rounded-xl border border-white/[.06] p-3"><span className="text-[8px] uppercase tracking-[.15em] text-white/20">Current position</span><strong className="mt-2 block font-mono text-[11px] text-white/65">{selectedMapFix ? `${selectedMapFix.lat.toFixed(5)}, ${selectedMapFix.lng.toFixed(5)}` : 'Awaiting fix'}</strong></div><div className="rounded-xl border border-white/[.06] p-3"><span className="text-[8px] uppercase tracking-[.15em] text-white/20">Velocity</span><strong className="mt-2 block font-mono text-[11px] text-white/65">{selectedMapFix?.speed_kph!=null ? `${Math.round(selectedMapFix.speed_kph)} km/h` : '—'}</strong></div><div className="rounded-xl border border-white/[.06] p-3"><span className="text-[8px] uppercase tracking-[.15em] text-white/20">Last observed</span><strong className="mt-2 block font-mono text-[11px] text-white/65">{selectedMapFix ? age(selectedMapFix.device_time) : '—'}</strong></div><div className="rounded-xl border border-white/[.06] p-3"><span className="text-[8px] uppercase tracking-[.15em] text-white/20">ETA</span><strong className="mt-2 block font-mono text-[11px] text-white/65">{fmt(selected.estimated_arrival_at)}</strong></div></div></div><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={openShipment} className="rounded-xl border border-white/[.08] px-3 py-2.5 text-[10px] font-semibold text-white/65 hover:text-white"><ArrowUpRight size={12} className="mr-1.5 inline"/>Open customer workspace</button><button onClick={()=>{setIssueOpen(true);setSelectedConvoy(selected.id)}} className="rounded-xl bg-orange-500 px-3 py-2.5 text-[10px] font-semibold text-white"><Link2 size={12} className="mr-1.5 inline"/>Grant access</button></div></div> : <div className="p-10 text-center text-[11px] text-white/25"><Crosshair size={22} className="mx-auto text-white/15"/><p className="mt-3">Select a vehicle on the map or movement board.</p></div>}</Card>

          <Card><div className="border-b border-white/[.07] p-4"><div className="flex items-center justify-between"><div><p className="text-[9px] font-bold uppercase tracking-[.18em] text-white/25">Telemetry health</p><p className="mt-1 text-[12px] font-semibold text-white/65">Coverage and source posture</p></div><Activity size={15} className="text-emerald-300"/></div></div><div className="grid grid-cols-2 gap-2 p-4"><div className="rounded-xl border border-white/[.06] p-3"><span className="text-[8px] uppercase tracking-[.14em] text-white/20">Reporting</span><strong className="mt-1 block font-mono text-xl text-emerald-300">{liveCount}</strong></div><div className="rounded-xl border border-white/[.06] p-3"><span className="text-[8px] uppercase tracking-[.14em] text-white/20">No fix</span><strong className="mt-1 block font-mono text-xl text-amber-300">{noFix}</strong></div><div className="rounded-xl border border-white/[.06] p-3"><span className="text-[8px] uppercase tracking-[.14em] text-white/20">Sources</span><strong className="mt-1 block font-mono text-xl text-sky-300">{sources.length}</strong></div><div className="rounded-xl border border-white/[.06] p-3"><span className="text-[8px] uppercase tracking-[.14em] text-white/20">Track points</span><strong className="mt-1 block font-mono text-xl text-white">{track.length}</strong></div></div></Card>
        </div>

        <Card className="xl:col-span-2"><div className="flex flex-col gap-3 border-b border-white/[.07] p-4 md:flex-row md:items-center md:justify-between"><div><div className="flex items-center gap-2"><Layers3 size={14} className="text-orange-300"/><p className="text-[11px] font-bold uppercase tracking-[.16em] text-white/65">Movement board</p></div><p className="mt-1 text-[10px] text-white/25">Dense operational cards · select one to drive the map and intelligence rail</p></div><div className="flex items-center gap-2 text-[9px] text-white/25"><span className="h-1.5 w-1.5 rounded-full bg-emerald-400"/> reporting <span className="mx-1">•</span><span className="h-1.5 w-1.5 rounded-full bg-amber-400"/> no fix <span className="mx-1">•</span><span className="h-1.5 w-1.5 rounded-full bg-red-400"/> security exception</div></div><div className="grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map(c=>{const f=mapFixes.find(x=>x.convoyId===c.id);return <MovementCard key={c.id} convoy={c} fix={f} selected={selectedConvoy===c.id} onSelect={()=>choose(c.id)} onOpen={()=>{setSelectedConvoy(c.id);window.open('/portal/convoy/'+c.id+'/track','_blank')}} onGrant={()=>{setSelectedConvoy(c.id);setIssueOpen(true)}}/>})}{!filtered.length&&<div className="col-span-full rounded-xl border border-dashed border-white/10 p-10 text-center text-[11px] text-white/25">No active movements match the filter.</div>}</div></Card>

        <Card className="xl:col-span-2"><div className="grid gap-4 p-4 md:grid-cols-4"><div className="rounded-xl border border-orange-400/15 bg-orange-400/[.04] p-4"><Zap size={15} className="text-orange-300"/><p className="mt-3 text-[9px] font-bold uppercase tracking-[.18em] text-white/25">Operator read</p><p className="mt-2 text-[12px] leading-relaxed text-white/60">The map reflects evidence. A missing fix stays visible as a gap instead of becoming a fake green dot.</p></div><div className="rounded-xl border border-white/[.06] p-4"><Gauge size={15} className="text-sky-300"/><p className="mt-3 text-[9px] font-bold uppercase tracking-[.18em] text-white/25">Telemetry semantics</p><p className="mt-2 text-[12px] leading-relaxed text-white/60">Health, capability, age and source are kept separate so operators can distinguish “live now” from “can keep reporting”.</p></div><div className="rounded-xl border border-white/[.06] p-4"><FileText size={15} className="text-emerald-300"/><p className="mt-3 text-[9px] font-bold uppercase tracking-[.18em] text-white/25">Customer handoff</p><p className="mt-2 text-[12px] leading-relaxed text-white/60">One click opens the customer-safe workspace for the selected shipment without exposing the command surface.</p></div><div className="rounded-xl border border-white/[.06] p-4"><ShieldCheck size={15} className="text-red-300"/><p className="mt-3 text-[9px] font-bold uppercase tracking-[.18em] text-white/25">Security posture</p><p className="mt-2 text-[12px] leading-relaxed text-white/60">Seal exceptions remain first-class operational state and are never buried beneath cosmetic KPIs.</p></div></div></Card>
      </div>}

      {view==='access' && <Card><div className="border-b border-white/[.07] p-4"><div className="flex items-center gap-2"><Link2 size={15} className="text-orange-300"/><p className="text-[11px] font-bold uppercase tracking-[.16em] text-white/65">Shipment access control</p></div><p className="mt-1 text-[10px] text-white/25">Select a movement to inspect and issue scoped customer portal access.</p></div><div className="grid gap-4 p-4 lg:grid-cols-[360px_1fr]"><div className="space-y-2">{convoys.map(c=><button type="button" key={c.id} onClick={()=>setSelectedConvoy(c.id)} className={`w-full rounded-xl border p-3 text-left ${selectedConvoy===c.id?'border-orange-400/30 bg-orange-400/[.05]':'border-white/[.06] bg-white/[.015]'}`}><div className="flex items-center justify-between"><span className="text-[11px] font-semibold text-white">{c.reference}</span><Pill tone={c.seal_intact===false?'red':'green'}>{c.seal_intact===false?'Attention':'Secure'}</Pill></div><p className="mt-1 truncate text-[10px] text-white/25">{c.origin} → {c.destination}</p></button>)}</div><div className="min-h-[320px] rounded-xl border border-white/[.06] bg-black/10 p-5">{!selectedConvoy?<div className="flex h-full min-h-[280px] items-center justify-center text-center text-[11px] text-white/25"><div><Link2 size={22} className="mx-auto text-white/10"/><p className="mt-3">Choose a movement to inspect access posture.</p></div></div>:<><div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div><p className="text-[9px] uppercase tracking-[.18em] text-orange-300/60">Scoped access</p><h2 className="mt-1 text-lg font-semibold text-white">{convoys.find(c=>c.id===selectedConvoy)?.reference}</h2><p className="mt-1 text-[10px] text-white/25">{tokens.filter(t=>!t.revoked_at&&new Date(t.expires_at).getTime()>Date.now()).length} active grant(s)</p></div><button onClick={()=>setIssueOpen(true)} className="rounded-xl bg-orange-500 px-3 py-2 text-[10px] font-semibold text-white">Issue 24h read-only access</button></div><div className="mt-4 space-y-2">{tokens.map(t=><div key={t.id} className="flex items-center justify-between rounded-xl border border-white/[.06] p-3"><div><p className="text-[11px] text-white/65">{t.cargo_owner_ref||'Unlabelled cargo owner grant'}</p><p className="mt-1 text-[9px] text-white/20">Issued {fmt(t.issued_at)} · Expires {fmt(t.expires_at)}</p></div><Pill tone={!t.revoked_at&&new Date(t.expires_at).getTime()>Date.now()?'green':'neutral'}>{!t.revoked_at&&new Date(t.expires_at).getTime()>Date.now()?'Active':t.revoked_at?'Revoked':'Expired'}</Pill></div>)}{!tokens.length&&<div className="rounded-xl border border-dashed border-white/10 p-10 text-center text-[11px] text-white/20">No grants issued for this movement.</div>}</div></>}</div></div></Card>}
    </div>

    {issueOpen && <div className="fixed inset-0 z-[130] flex items-center justify-center bg-black/75 p-4 backdrop-blur-md"><div className="w-full max-w-md rounded-2xl border border-white/10 bg-[#0a111a] shadow-2xl"><div className="flex items-start justify-between border-b border-white/[.07] p-5"><div><p className="text-[9px] uppercase tracking-[.18em] text-orange-300/65">Access provisioning</p><h3 className="mt-1 text-lg font-semibold text-white">Grant cargo owner workspace</h3><p className="mt-1 text-[10px] text-white/25">24-hour, read-only and movement-scoped.</p></div><button onClick={()=>setIssueOpen(false)} className="rounded-lg p-2 text-white/30 hover:text-white"><X size={16}/></button></div><div className="p-5"><div className="rounded-xl border border-white/[.07] bg-white/[.02] p-3"><p className="text-[9px] uppercase tracking-[.14em] text-white/20">Movement</p><p className="mt-1 text-[12px] font-semibold text-white">{convoys.find(c=>c.id===selectedConvoy)?.reference||'—'}</p></div>{issue.isError&&<p className="mt-3 rounded-xl border border-red-400/15 bg-red-400/[.06] p-3 text-[10px] text-red-300">Access provisioning failed. No partial grant was assumed.</p>}<div className="mt-5 flex justify-end gap-2"><button onClick={()=>setIssueOpen(false)} className="rounded-xl border border-white/10 px-4 py-2.5 text-[10px] font-semibold text-white/40">Cancel</button><button onClick={()=>issue.mutate()} disabled={!selectedConvoy||issue.isPending} className="rounded-xl bg-orange-500 px-4 py-2.5 text-[10px] font-semibold text-white disabled:opacity-50">{issue.isPending?<Loader2 size={14} className="inline animate-spin"/>:'Issue access'}</button></div></div></div></div>}
  </div>;
}

function MapPinIconPlaceholder(){ return <span className="inline-flex h-5 w-5 items-center justify-center rounded-full bg-orange-400/10 text-orange-300">•</span>; }
