import React, { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Activity, Bell, CalendarClock, CheckCircle2, ChevronRight, Copy, FileText, Link2, Loader2, Mail, MapPin, Plus, Search, Send, ShieldCheck, Truck, Users, X, Zap } from 'lucide-react';
import { api } from '../lib/api.js';

interface CargoClient { id:string; email:string; name:string; company:string|null; phone?:string|null; last_login_at:string|null; created_at:string; linked_convoys?:number; active_convoys?:number; completed_convoys?:number }
interface Convoy { id:string; reference:string; origin:string; destination:string; status?:string }
interface ClientLink { id:string; client_id:string; convoy_id:string; shipment_id:string|null; show_value:boolean; created_at:string; reference:string; status:string; origin:string|null; destination:string|null; eta:string|null; seal_intact:boolean|null; exception_count:number }
interface EmailRecipient { id:string; email:string; name:string|null; company:string|null; enabled:boolean; sonalit_operational:boolean; sonalit_security:boolean; cds_client_pulse:boolean }

const fmt=(v:string|null)=>v?new Date(v).toLocaleString('en-ZA',{dateStyle:'medium',timeStyle:'short'}):'Never';
function Pill({children,tone='neutral'}:{children:React.ReactNode;tone?:'green'|'orange'|'red'|'blue'|'neutral'}){const c={green:'border-emerald-500/20 bg-emerald-500/10 text-emerald-300',orange:'border-orange-500/20 bg-orange-500/10 text-orange-300',red:'border-red-500/20 bg-red-500/10 text-red-300',blue:'border-sky-500/20 bg-sky-500/10 text-sky-300',neutral:'border-white/10 bg-white/[.03] text-white/45'}[tone];return <span className={\`inline-flex items-center gap-1 rounded-full border px-2 py-1 text-[10px] font-semibold \${c}\`}>{children}</span>}

function CreateClientModal({onClose,onCreated}:{onClose:()=>void;onCreated:(c:CargoClient)=>void}) {
 const [form,setForm]=useState({email:'',name:'',company:'',phone:'',country:'Kenya'}); const [error,setError]=useState('');
 const m=useMutation({mutationFn:()=>api.post<{data:CargoClient}>('/portal/clients',form),onSuccess:r=>onCreated(r.data.data),onError:(e:unknown)=>setError((e as any).response?.data?.error??'Failed to create client')});
 return <div className="fixed inset-0 z-[80] flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm"><div className="w-full max-w-lg rounded-2xl border border-white/10 p-6 shadow-2xl" style={{background:'rgba(10,16,30,.99)'}}>
  <div className="flex items-center justify-between"><div><p className="text-[10px] uppercase tracking-[.2em] text-orange-300/60">Client provisioning</p><h2 className="mt-1 text-lg font-semibold text-white">Create cargo-owner workspace</h2></div><button onClick={onClose}><X size={18} className="text-white/30"/></button></div>
  {error&&<div className="mt-4 rounded-xl border border-red-500/20 bg-red-500/[.05] p-3 text-xs text-red-300">{error}</div>}
  <div className="mt-5 grid gap-3 sm:grid-cols-2">{([['name','Full name','text'],['company','Company','text'],['email','Email address','email'],['phone','Phone number','tel']] as const).map(([f,l,t])=><label key={f} className={f==='email'?'sm:col-span-2':''}><span className="mb-1 block text-[11px] text-white/40">{l}</span><input type={t} value={form[f]} onChange={e=>setForm(p=>({...p,[f]:e.target.value}))} className="w-full rounded-xl border border-white/[.08] bg-white/[.035] px-3 py-2.5 text-sm text-white outline-none focus:border-orange-500/35"/></label>)}</div>
  <p className="mt-3 text-[11px] leading-relaxed text-white/25">Provisioning creates an organisation-scoped customer identity. Shipment access is granted separately per convoy.</p>
  <div className="mt-5 flex justify-end gap-2"><button onClick={onClose} className="rounded-xl border border-white/10 px-4 py-2 text-sm text-white/45">Cancel</button><button onClick={()=>m.mutate()} disabled={!form.name||!form.email||m.isPending} className="flex items-center gap-2 rounded-xl bg-orange-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{m.isPending?<Loader2 size={14} className="animate-spin"/>:<Plus size={14}/>} Provision workspace</button></div>
 </div></div>
}

function LinkConvoyModal({client,convoys,onClose,onLinked}:{client:CargoClient;convoys:Convoy[];onClose:()=>void;onLinked:()=>void}){
 const [convoyId,setConvoyId]=useState(convoys[0]?.id??''); const [showValue,setShowValue]=useState(false);
 const m=useMutation({mutationFn:()=>api.post(\`/portal/clients/\${client.id}/links\`,{convoy_id:convoyId,show_value:showValue}),onSuccess:onLinked});
 return <div className="fixed inset-0 z-[90] flex items-center justify-center bg-black/70 p-4"><div className="w-full max-w-md rounded-2xl border border-white/10 p-6" style={{background:'#0b1221'}}>
  <div className="flex items-center justify-between"><h2 className="text-lg font-semibold text-white">Grant shipment visibility</h2><button onClick={onClose}><X size={18} className="text-white/30"/></button></div><p className="mt-1 text-xs text-white/35">{client.name} · {client.email}</p>
  <label className="mt-5 block text-[11px] text-white/40">Convoy</label><select value={convoyId} onChange={e=>setConvoyId(e.target.value)} className="mt-1 w-full rounded-xl border border-white/[.08] bg-white/[.035] px-3 py-2.5 text-sm text-white">{convoys.map(c=><option key={c.id} value={c.id}>{c.reference} — {c.origin} → {c.destination}</option>)}</select>
  <label className="mt-4 flex items-start gap-3 rounded-xl border border-white/[.06] bg-white/[.02] p-3 text-xs text-white/55"><input type="checkbox" checked={showValue} onChange={e=>setShowValue(e.target.checked)} className="mt-0.5"/><span><b className="text-white/75">Expose declared cargo value</b><span className="mt-0.5 block text-white/25">Commercial value remains hidden by default.</span></span></label>
  {m.isError&&<p className="mt-3 text-xs text-red-300">Could not create the visibility grant.</p>}
  <div className="mt-5 flex justify-end gap-2"><button onClick={onClose} className="rounded-xl border border-white/10 px-4 py-2 text-sm text-white/45">Cancel</button><button onClick={()=>m.mutate()} disabled={!convoyId||m.isPending} className="rounded-xl bg-orange-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{m.isPending?'Granting…':'Grant access'}</button></div>
 </div></div>
}

function EmailRules({client}:{client:CargoClient}){
 const qc=useQueryClient(); const {data}=useQuery<{data:EmailRecipient[]}>({queryKey:['client-email-recipients'],queryFn:()=>api.get('/settings/email-recipients').then(r=>r.data)});
 const existing=data?.data?.find(x=>x.email.toLowerCase()===client.email.toLowerCase()); const [open,setOpen]=useState(false);
 const [form,setForm]=useState({enabled:true,sonalit_operational:true,sonalit_security:true,cds_client_pulse:true});
 React.useEffect(()=>{if(existing)setForm({enabled:existing.enabled,sonalit_operational:existing.sonalit_operational,sonalit_security:existing.sonalit_security,cds_client_pulse:existing.cds_client_pulse})},[existing?.id]);
 const save=useMutation({mutationFn:()=>api.post('/settings/email-recipients',{email:client.email,name:client.name,company:client.company,...form}),onSuccess:()=>{setOpen(false);void qc.invalidateQueries({queryKey:['client-email-recipients']})}});
 return <div className="mt-4 rounded-xl border border-white/[.06] bg-black/10 p-3"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><Bell size={13} className="text-orange-400"/><span className="text-[10px] uppercase tracking-[.15em] text-white/40">Notification policy</span>{existing?.enabled?<Pill tone="green">ACTIVE</Pill>:<Pill>NOT CONFIGURED</Pill>}</div><button onClick={()=>setOpen(v=>!v)} className="text-[10px] text-orange-300">{open?'Close':'Configure'}</button></div>
 {open&&<div className="mt-3 grid gap-2">{([['enabled','Enable delivery'],['sonalit_operational','Operational alerts'],['sonalit_security','Security alerts'],['cds_client_pulse','CDS Client Pulse']] as const).map(([f,l])=><label key={f} className="flex items-center gap-2 text-[11px] text-white/45"><input type="checkbox" checked={form[f]} onChange={e=>setForm(p=>({...p,[f]:e.target.checked}))}/>{l}</label>)}<button onClick={()=>save.mutate()} disabled={save.isPending} className="mt-1 flex w-fit items-center gap-2 rounded-lg bg-orange-600 px-3 py-1.5 text-[11px] font-semibold text-white">{save.isPending?<Loader2 size={11} className="animate-spin"/>:<CheckCircle2 size={11}/>} Save policy</button></div>}</div>
}

function ClientDrawer({client,convoys,onClose}:{client:CargoClient;convoys:Convoy[];onClose:()=>void}){
 const qc=useQueryClient(); const [showLink,setShowLink]=useState(false); const [magicUrl,setMagicUrl]=useState<string|null>(null);
 const links=useQuery<{data:ClientLink[]}>({queryKey:['portal-client-links',client.id],queryFn:()=>api.get(\`/portal/clients/\${client.id}/links\`).then(r=>r.data)});
 const magic=useMutation({mutationFn:()=>api.post<{data:{url:string}}>(\`/portal/clients/\${client.id}/magic-link\`,{}),onSuccess:r=>setMagicUrl(r.data.data.url)});
 const resend=useMutation({mutationFn:()=>api.post('/portal/auth/request-link',{email:client.email})});
 return <aside className="fixed inset-y-0 right-0 z-[70] w-full max-w-xl overflow-y-auto border-l border-white/[.08] bg-[#09111f] shadow-2xl">
  <div className="sticky top-0 z-10 flex items-center justify-between border-b border-white/[.06] bg-[#09111f]/95 px-5 py-4 backdrop-blur-md"><div><p className="text-[10px] uppercase tracking-[.18em] text-orange-300/60">Cargo owner 360°</p><h2 className="mt-1 text-lg font-semibold text-white">{client.name}</h2><p className="text-xs text-white/35">{client.company??'Independent'} · {client.email}</p></div><button onClick={onClose}><X size={19} className="text-white/35"/></button></div>
  <div className="space-y-4 p-5">
   <div className="grid grid-cols-3 gap-2"><div className="rounded-xl border border-white/[.06] bg-white/[.02] p-3"><p className="text-[10px] text-white/25">Linked</p><p className="mono mt-1 text-xl text-white">{client.linked_convoys??links.data?.length??0}</p></div><div className="rounded-xl border border-emerald-500/15 bg-emerald-500/[.03] p-3"><p className="text-[10px] text-white/25">Active</p><p className="mono mt-1 text-xl text-emerald-300">{client.active_convoys??links.data?.filter(l=>l.status==='in_transit').length??0}</p></div><div className="rounded-xl border border-sky-500/15 bg-sky-500/[.03] p-3"><p className="text-[10px] text-white/25">Completed</p><p className="mono mt-1 text-xl text-sky-300">{client.completed_convoys??links.data?.filter(l=>l.status==='completed').length??0}</p></div></div>
   <div className="grid grid-cols-2 gap-2"><button onClick={()=>setShowLink(true)} className="flex items-center justify-center gap-2 rounded-xl border border-orange-500/20 bg-orange-500/[.07] px-3 py-2.5 text-xs font-semibold text-orange-300"><Link2 size={13}/> Grant shipment</button><button onClick={()=>magic.mutate()} disabled={magic.isPending} className="flex items-center justify-center gap-2 rounded-xl border border-white/[.07] px-3 py-2.5 text-xs font-semibold text-white/55 hover:text-white">{magic.isPending?<Loader2 size={13} className="animate-spin"/>:<Copy size={13}/>} Generate login link</button></div>
   {magicUrl&&<div className="rounded-xl border border-emerald-500/20 bg-emerald-500/[.04] p-3"><div className="flex items-center justify-between"><p className="text-[10px] uppercase tracking-[.16em] text-emerald-300/70">15-minute access link</p><button onClick={()=>navigator.clipboard.writeText(magicUrl)} className="text-[10px] text-emerald-300">Copy</button></div><code className="mt-2 block break-all text-[10px] text-white/55">{magicUrl}</code></div>}
   <div className="rounded-2xl border border-white/[.07] bg-white/[.015] p-4"><div className="flex items-center gap-2"><ShieldCheck size={15} className="text-emerald-400"/><div><p className="text-sm font-semibold text-white/80">Access posture</p><p className="text-[11px] text-white/30">Explicit tenant-scoped visibility grants</p></div></div><div className="mt-3 flex flex-wrap gap-2"><Pill tone="green">Org isolated</Pill><Pill tone="blue"><Zap size={10}/> Scoped API</Pill><Pill><Users size={10}/> External user</Pill></div></div>
   <div><div className="mb-2 flex items-center gap-2"><Truck size={14} className="text-orange-400"/><p className="text-sm font-semibold text-white/80">Linked shipment workspaces</p></div><div className="space-y-2">{links.data?.map(link=><div key={link.id} className="rounded-xl border border-white/[.06] bg-white/[.02] p-3"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold text-white">{link.reference}</p><p className="mt-0.5 text-[11px] text-white/30">{link.origin??'—'} → {link.destination??'—'}</p></div><Pill tone={link.exception_count>0?'red':link.status==='in_transit'?'green':'neutral'}>{link.exception_count>0?'ATTENTION':link.status.replace(/_/g,' ').toUpperCase()}</Pill></div><div className="mt-3 grid grid-cols-3 gap-2 text-[10px]"><div><span className="block text-white/20">ETA</span><span className="mono text-white/50">{fmt(link.eta)}</span></div><div><span className="block text-white/20">Seal</span><span className={link.seal_intact===false?'text-red-300':'text-emerald-300'}>{link.seal_intact===false?'Compromised':link.seal_intact===true?'Intact':'Unverified'}</span></div><div><span className="block text-white/20">Value</span><span className="text-white/50">{link.show_value?'Visible':'Hidden'}</span></div></div></div>)}</div>{!links.isLoading&&!links.data?.length&&<div className="rounded-xl border border-dashed border-white/[.08] p-6 text-center text-xs text-white/25">No shipment visibility grants yet.</div>}</div>
   <EmailRules client={client}/>
   <div className="rounded-xl border border-white/[.06] bg-white/[.015] p-4"><p className="text-[10px] uppercase tracking-[.18em] text-white/25">Account activity</p><div className="mt-3 flex items-center gap-3 text-xs text-white/45"><Activity size={13} className="text-sky-400"/><span>Last login</span><span className="mono ml-auto text-white/55">{fmt(client.last_login_at)}</span></div><div className="mt-2 flex items-center gap-3 text-xs text-white/45"><CalendarClock size={13} className="text-orange-400"/><span>Created</span><span className="mono ml-auto text-white/55">{fmt(client.created_at)}</span></div></div>
   <button onClick={()=>resend.mutate()} disabled={resend.isPending} className="w-full rounded-xl border border-white/[.07] px-3 py-2.5 text-xs font-semibold text-white/50 hover:text-white">{resend.isPending?'Sending…':'Send login email again'}</button>
  </div>
  {showLink&&<LinkConvoyModal client={client} convoys={convoys} onClose={()=>setShowLink(false)} onLinked={()=>{setShowLink(false);void qc.invalidateQueries({queryKey:['portal-client-links',client.id]});void qc.invalidateQueries({queryKey:['portal-clients']})}}/>}
 </aside>
}

export function CargoClientsPanel({convoys}:{convoys:Convoy[]}):React.ReactElement{
 const qc=useQueryClient(); const [showCreate,setShowCreate]=useState(false); const [selected,setSelected]=useState<CargoClient|null>(null); const [search,setSearch]=useState(''); const [segment,setSegment]=useState<'all'|'active'|'attention'>('all');
 const {data,isLoading,refetch}=useQuery<{data:CargoClient[]}>({queryKey:['portal-clients'],queryFn:()=>api.get('/portal/clients').then(r=>r.data)});
 const pulse=useMutation({mutationFn:()=>api.post('/admin/cds-client-pulse/send',{}),onSuccess:()=>void qc.invalidateQueries({queryKey:['client-email-recipients']})});
 const clients=data?.data??[]; const attention=clients.filter(c=>(c.active_convoys??0)>0&&!c.last_login_at);
 const filtered=useMemo(()=>clients.filter(c=>{const q=search.toLowerCase().trim();const hit=!q||[c.name,c.email,c.company].some(v=>(v??'').toLowerCase().includes(q));const seg=segment==='all'||(segment==='active'&&(c.active_convoys??0)>0)||(segment==='attention'&&attention.some(a=>a.id===c.id));return hit&&seg}),[clients,search,segment,attention]);
 return <div className="space-y-5">
  <section className="rounded-3xl border border-orange-500/15 p-5 sm:p-6" style={{background:'radial-gradient(circle at 88% 12%, rgba(249,115,22,.11), transparent 35%), linear-gradient(135deg,rgba(255,255,255,.035),rgba(255,255,255,.01))'}}><div className="flex flex-col xl:flex-row xl:items-end justify-between gap-5"><div><p className="text-[10px] uppercase tracking-[.22em] text-orange-300/70">Cargo owner control tower</p><h2 className="mt-2 text-2xl sm:text-3xl font-semibold tracking-tight text-white">Manage every customer workspace from one place.</h2><p className="mt-2 max-w-2xl text-sm leading-relaxed text-white/40">Provision identities, grant shipment visibility, control commercial-value exposure, manage notifications and inspect each customer's operational footprint.</p></div><div className="flex gap-2"><button onClick={()=>refetch()} className="rounded-xl border border-white/[.07] px-3 py-2 text-xs text-white/45 hover:text-white"><Activity size={13} className="mr-1 inline"/>Refresh</button><button onClick={()=>setShowCreate(true)} className="flex items-center gap-2 rounded-xl bg-orange-600 px-3.5 py-2 text-xs font-semibold text-white hover:bg-orange-500"><Plus size={13}/> New workspace</button></div></div></section>
  <section className="grid grid-cols-2 lg:grid-cols-4 gap-3"><div className="rounded-2xl border border-white/[.07] bg-white/[.018] p-4"><p className="text-[10px] uppercase tracking-[.16em] text-white/30">Cargo owners</p><p className="mono mt-2 text-2xl text-white">{clients.length}</p><p className="mt-1 text-[11px] text-white/25">Provisioned accounts</p></div><div className="rounded-2xl border border-emerald-500/15 bg-emerald-500/[.025] p-4"><p className="text-[10px] uppercase tracking-[.16em] text-white/30">Active coverage</p><p className="mono mt-2 text-2xl text-emerald-300">{clients.filter(c=>(c.active_convoys??0)>0).length}</p><p className="mt-1 text-[11px] text-white/25">Clients with live movements</p></div><div className="rounded-2xl border border-amber-500/15 bg-amber-500/[.025] p-4"><p className="text-[10px] uppercase tracking-[.16em] text-white/30">Attention</p><p className="mono mt-2 text-2xl text-amber-300">{attention.length}</p><p className="mt-1 text-[11px] text-white/25">Active but never logged in</p></div><div className="rounded-2xl border border-sky-500/15 bg-sky-500/[.025] p-4"><p className="text-[10px] uppercase tracking-[.16em] text-white/30">Linked movements</p><p className="mono mt-2 text-2xl text-sky-300">{clients.reduce((n,c)=>n+(c.linked_convoys??0),0)}</p><p className="mt-1 text-[11px] text-white/25">Visibility grants</p></div></section>
  <section className="rounded-2xl border border-white/[.07] overflow-hidden bg-white/[.012]"><div className="border-b border-white/[.06] p-4"><div className="flex flex-col lg:flex-row lg:items-center justify-between gap-3"><div><p className="text-[10px] uppercase tracking-[.18em] text-white/30">Customer registry</p><p className="mt-1 text-sm font-semibold text-white/75">{filtered.length} workspaces in view</p></div><div className="flex flex-wrap items-center gap-2"><div className="relative min-w-[220px]"><Search size={13} className="absolute left-3 top-1/2 -translate-y-1/2 text-white/25"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search client, company or email…" className="w-full rounded-xl border border-white/[.07] bg-black/10 py-2 pl-8 pr-3 text-xs text-white placeholder-white/20 outline-none focus:border-orange-500/30"/></div><div className="flex rounded-xl border border-white/[.07] overflow-hidden">{([['all','All'],['active','Active'],['attention','Attention']] as const).map(([key,label])=><button key={key} onClick={()=>setSegment(key)} className={\`px-3 py-2 text-[11px] font-semibold \${segment===key?'bg-orange-500 text-white':'text-white/35 hover:text-white/70'}\`}>{label}</button>)}</div></div></div></div>{isLoading?<div className="p-10 text-center text-xs text-white/30">Loading cargo-owner registry…</div>:<div className="divide-y divide-white/[.05]">{filtered.map(c=><button key={c.id} onClick={()=>setSelected(c)} className="w-full text-left px-4 sm:px-5 py-4 hover:bg-white/[.02] transition-colors"><div className="flex items-center gap-4"><div className="h-10 w-10 shrink-0 rounded-xl border border-orange-500/20 bg-orange-500/10 flex items-center justify-center text-sm font-bold text-orange-300">{c.name[0]?.toUpperCase()}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold text-white truncate">{c.name}</p>{(c.active_convoys??0)>0&&<Pill tone="green"><Activity size={10}/> LIVE</Pill>}{attention.some(x=>x.id===c.id)&&<Pill tone="red">LOGIN REQUIRED</Pill>}</div><p className="mt-1 text-xs text-white/35 truncate">{c.company??'No company'} · {c.email}</p><div className="mt-2 flex flex-wrap gap-2"><Pill><Truck size={10}/>{c.linked_convoys??0} linked</Pill><Pill tone="blue"><CheckCircle2 size={10}/>{c.completed_convoys??0} completed</Pill></div></div><ChevronRight size={17} className="text-white/20"/></div></button>)}{!filtered.length&&<div className="p-10 text-center text-xs text-white/30">No cargo-owner workspaces match the current view.</div>}</div>}</section>
  <section className="grid grid-cols-1 lg:grid-cols-2 gap-3"><div className="rounded-2xl border border-white/[.07] p-4 bg-white/[.012]"><div className="flex items-center gap-2"><Mail size={14} className="text-orange-400"/><p className="text-sm font-semibold text-white/75">Communication control</p></div><p className="mt-2 text-[11px] leading-relaxed text-white/30">Control operational, security and CDS Client Pulse delivery at the client level.</p><button onClick={()=>pulse.mutate()} disabled={pulse.isPending} className="mt-4 flex items-center gap-2 rounded-xl border border-orange-500/20 bg-orange-500/[.06] px-3 py-2 text-xs font-semibold text-orange-300">{pulse.isPending?<Loader2 size={12} className="animate-spin"/>:<Send size={12}/>}Send Client Pulse now</button></div><div className="rounded-2xl border border-white/[.07] p-4 bg-white/[.012]"><div className="flex items-center gap-2"><MapPin size={14} className="text-sky-400"/><p className="text-sm font-semibold text-white/75">Boundary model</p></div><p className="mt-2 text-[11px] leading-relaxed text-white/30">Admin operators manage visibility grants. External customers only see explicitly linked, sanitised cargo data.</p></div></section>
  {showCreate&&<CreateClientModal onClose={()=>setShowCreate(false)} onCreated={c=>{setShowCreate(false);void qc.invalidateQueries({queryKey:['portal-clients']})}}/>}{selected&&<><div className="fixed inset-0 z-[65] bg-black/35" onClick={()=>setSelected(null)}/><ClientDrawer client={selected} convoys={convoys} onClose={()=>setSelected(null)}/></>}
 </div>
}
