import React, { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Bell, CheckCircle2, Copy, Link, Loader2, Mail, Plus, Send, Shield, Users } from 'lucide-react';
import { api } from '../lib/api.js';

interface CargoClient { id: string; email: string; name: string; company: string | null; last_login_at: string | null; created_at: string }
interface Convoy { id: string; reference: string; origin: string; destination: string }
interface EmailRecipient { id: string; email: string; name: string | null; company: string | null; enabled: boolean; sonalit_operational: boolean; sonalit_security: boolean; cds_client_pulse: boolean }

const fmt = (value: string | null) => value ? new Date(value).toLocaleString('en-ZA', { dateStyle: 'medium', timeStyle: 'short' }) : 'Never';

function CreateClientModal({ onClose, onCreated }: { onClose: () => void; onCreated: (client: CargoClient) => void }) {
  const [form, setForm] = useState({ email: '', name: '', company: '' }); const [error, setError] = useState('');
  const mutation = useMutation({ mutationFn: () => api.post<{ data: CargoClient }>('/portal/clients', form), onSuccess: response => onCreated(response.data.data), onError: (error: unknown) => setError((error as any).response?.data?.error ?? 'Failed') });
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm"><div className="w-full max-w-md rounded-xl border border-white/10 p-6" style={{ background: 'rgba(13,20,38,.98)' }}><h2 className="mb-4 flex items-center gap-2 text-lg font-bold text-white"><Plus size={16} className="text-orange-400" /> New Cargo Client</h2>{error && <div className="mb-3 rounded border border-red-700 bg-red-900/30 px-3 py-2 text-xs text-red-400">{error}</div>}<div className="space-y-3">{(['email', 'name', 'company'] as const).map(field => <div key={field}><label className="mb-1 block text-xs capitalize text-gray-400">{field}{field === 'company' ? ' (optional)' : ''}</label><input type={field === 'email' ? 'email' : 'text'} value={form[field]} onChange={e => setForm(previous => ({ ...previous, [field]: e.target.value }))} className="w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm text-white" /></div>)}</div><div className="mt-3 rounded-lg border border-white/10 bg-white/[.03] p-3 text-xs text-gray-400">After creation, configure exactly which Sonalit and CDS emails this client receives.</div><div className="mt-5 flex gap-3"><button onClick={onClose} className="flex-1 rounded-lg border border-white/10 py-2 text-sm text-gray-400">Cancel</button><button onClick={() => mutation.mutate()} disabled={!form.email || !form.name || mutation.isPending} className="flex flex-1 items-center justify-center gap-2 rounded-lg bg-orange-600 py-2 text-sm font-semibold text-white disabled:opacity-50">{mutation.isPending ? <Loader2 size={13} className="animate-spin" /> : <Plus size={13} />} Create</button></div></div></div>;
}

function LinkConvoyModal({ client, convoys, onClose, onLinked }: { client: CargoClient; convoys: Convoy[]; onClose: () => void; onLinked: () => void }) {
  const [convoyId, setConvoyId] = useState(convoys[0]?.id ?? ''); const [showValue, setShowValue] = useState(false);
  const mutation = useMutation({ mutationFn: () => api.post(`/portal/clients/${client.id}/links`, { convoy_id: convoyId, show_value: showValue }), onSuccess: onLinked });
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70"><div className="w-full max-w-md rounded-xl border border-white/10 p-6" style={{ background: 'rgba(13,20,38,.98)' }}><h2 className="mb-4 text-lg font-bold text-white">Link Convoy</h2><select value={convoyId} onChange={e => setConvoyId(e.target.value)} className="w-full rounded-lg bg-white/5 px-3 py-2 text-sm text-white">{convoys.map(convoy => <option key={convoy.id} value={convoy.id}>{convoy.reference} — {convoy.origin} → {convoy.destination}</option>)}</select><label className="mt-3 flex items-center gap-2 text-xs text-gray-400"><input type="checkbox" checked={showValue} onChange={e => setShowValue(e.target.checked)} /> Show declared cargo value</label><div className="mt-5 flex gap-3"><button onClick={onClose} className="flex-1 rounded-lg border border-white/10 py-2 text-sm text-gray-400">Cancel</button><button onClick={() => mutation.mutate()} disabled={!convoyId || mutation.isPending} className="flex-1 rounded-lg bg-orange-600 py-2 text-sm font-semibold text-white">{mutation.isPending ? 'Linking…' : 'Link'}</button></div></div></div>;
}

function EmailControls({ client }: { client: CargoClient }) {
  const queryClient = useQueryClient(); const { data } = useQuery<{ data: EmailRecipient[] }>({ queryKey: ['client-email-recipients'], queryFn: () => api.get('/settings/email-recipients').then(response => response.data) }); const existing = data?.data?.find(recipient => recipient.email.toLowerCase() === client.email.toLowerCase()); const [editing, setEditing] = useState(false); const [form, setForm] = useState({ enabled: true, sonalit_operational: true, sonalit_security: false, cds_client_pulse: true });
  useEffect(() => { if (existing) setForm({ enabled: existing.enabled, sonalit_operational: existing.sonalit_operational, sonalit_security: existing.sonalit_security, cds_client_pulse: existing.cds_client_pulse }); }, [existing?.id]);
  const save = useMutation({ mutationFn: () => api.post('/settings/email-recipients', { email: client.email, name: client.name, company: client.company, ...form }), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['client-email-recipients'] }); setEditing(false); } });
  return <div className="mt-3 rounded-lg border border-white/[.07] bg-black/10 p-3"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><Bell size={12} className="text-orange-400" /><span className="text-[11px] font-semibold text-gray-300">EMAIL DELIVERY</span>{existing?.enabled ? <span className="text-[10px] text-green-400">ACTIVE</span> : <span className="text-[10px] text-gray-600">NOT CONFIGURED</span>}</div><button onClick={() => setEditing(value => !value)} className="text-[10px] text-orange-400">{editing ? 'Close' : 'Configure'}</button></div>{editing && <div className="mt-3 grid gap-2">{([['enabled', 'Enable email delivery'], ['sonalit_operational', 'Sonalit operational alerts'], ['sonalit_security', 'Sonalit security alerts'], ['cds_client_pulse', 'CDS Client Pulse manifest']] as const).map(([field, label]) => <label key={field} className="flex items-center gap-2 text-[11px] text-gray-400"><input type="checkbox" checked={form[field]} onChange={e => setForm(previous => ({ ...previous, [field]: e.target.checked }))} /> {label}</label>)}<button onClick={() => save.mutate()} disabled={save.isPending} className="mt-1 rounded-lg bg-orange-600 px-3 py-1.5 text-[11px] font-semibold text-white">{save.isPending ? 'Saving…' : 'Save Email Rules'}</button></div>}{!editing && existing && <div className="mt-2 flex flex-wrap gap-1">{existing.sonalit_operational && <span className="rounded bg-blue-500/10 px-2 py-1 text-[9px] text-blue-300">OPS</span>}{existing.sonalit_security && <span className="rounded bg-red-500/10 px-2 py-1 text-[9px] text-red-300">SECURITY</span>}{existing.cds_client_pulse && <span className="rounded bg-orange-500/10 px-2 py-1 text-[9px] text-orange-300">CDS PULSE</span>}</div>}</div>;
}

function ClientRow({ client, convoys }: { client: CargoClient; convoys: Convoy[] }) {
  const [showLink, setShowLink] = useState(false); const [linkSent, setLinkSent] = useState(false); const [linkCopied, setLinkCopied] = useState(false); const [linkUrl, setLinkUrl] = useState<string | null>(null); const queryClient = useQueryClient();
  const sendLink = useMutation({ mutationFn: () => api.post('/portal/auth/request-link', { email: client.email }), onSuccess: () => { setLinkSent(true); setTimeout(() => setLinkSent(false), 5000); } }); const copyLink = useMutation({ mutationFn: () => api.post<{ data: { url: string } }>(`/portal/clients/${client.id}/magic-link`, {}), onSuccess: response => { const url = response.data.data.url; setLinkUrl(url); navigator.clipboard.writeText(url).then(() => { setLinkCopied(true); setTimeout(() => setLinkCopied(false), 4000); }); } });
  return <><div className="flex items-start gap-4 px-5 py-4"><div className="mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-full border border-orange-500/20 bg-orange-500/10"><span className="text-xs font-bold text-orange-400">{client.name[0]?.toUpperCase()}</span></div><div className="min-w-0 flex-1"><p className="text-sm font-semibold text-white">{client.name}</p><p className="text-xs text-gray-500">{client.email}{client.company ? ` · ${client.company}` : ''}</p><p className="mt-0.5 text-xs text-gray-600">Last login: {fmt(client.last_login_at)}</p><EmailControls client={client} /></div><div className="flex shrink-0 flex-col items-end gap-1.5"><div className="flex items-center gap-1.5"><button onClick={() => setShowLink(true)} className="flex items-center gap-1 rounded-lg border border-white/10 px-2 py-1 text-xs text-gray-400 hover:text-orange-400"><Shield size={11} /> Link Convoy</button><button onClick={() => sendLink.mutate()} disabled={sendLink.isPending || linkSent} className="flex items-center gap-1 rounded-lg border border-white/10 px-2 py-1 text-xs text-gray-400 hover:text-blue-400 disabled:opacity-50"><Mail size={11} />{linkSent ? 'Sent' : 'Email'}</button></div><button onClick={() => copyLink.mutate()} disabled={copyLink.isPending} className="flex w-full items-center justify-center gap-1 rounded-lg border px-2 py-1 text-xs" style={linkCopied ? { borderColor: 'rgba(34,197,94,.4)', color: '#4ade80' } : { borderColor: 'rgba(249,115,22,.3)', color: '#fb923c' }}>{copyLink.isPending ? <Loader2 size={11} className="animate-spin" /> : linkCopied ? <CheckCircle2 size={11} /> : <Copy size={11} />} {linkCopied ? 'Copied!' : 'Copy Login Link'}</button></div></div>{linkUrl && linkCopied && <div className="mx-5 mb-3 flex items-center gap-2 rounded-lg border border-orange-500/20 bg-orange-500/05 px-3 py-2"><Link size={11} className="text-orange-400" /><code className="flex-1 break-all text-[10px] text-orange-200">{linkUrl}</code></div>}{showLink && <LinkConvoyModal client={client} convoys={convoys} onClose={() => setShowLink(false)} onLinked={() => { setShowLink(false); void queryClient.invalidateQueries({ queryKey: ['portal-clients'] }); }} />}</>;
}

export function CargoClientsPanel({ convoys }: { convoys: Convoy[] }): React.ReactElement {
  const [showCreate, setShowCreate] = useState(false); const [pulseMessage, setPulseMessage] = useState<string | null>(null); const queryClient = useQueryClient();
  const { data, isLoading } = useQuery<{ data: CargoClient[] }>({ queryKey: ['portal-clients'], queryFn: () => api.get('/portal/clients').then(response => response.data) });
  const pulse = useMutation({ mutationFn: () => api.post<{ data: { queued?: number; global?: { queued?: number; skipped?: boolean; reason?: string }; customers?: Array<{ queued?: number; skipped?: boolean; reason?: string }> } }>('/admin/cds-client-pulse/send', {}), onSuccess: response => { const data = response.data?.data ?? {}; const queued = Number(data.queued ?? 0); const globalQueued = Number(data.global?.queued ?? 0); const customers = Array.isArray(data.customers) ? data.customers : []; setPulseMessage(`Client Pulse dispatched: ${queued} email job(s) queued — Super Admin: ${globalQueued}; customer scopes: ${customers.length}.`); void queryClient.invalidateQueries({ queryKey: ['client-email-recipients'] }); }, onError: (error: unknown) => setPulseMessage((error as any)?.response?.data?.error ?? 'Client Pulse dispatch failed.') });
  const clients = data?.data ?? [];
  return <div><div className="mb-4 flex items-center justify-between"><div className="flex items-center gap-2"><Users size={15} className="text-orange-400" /><p className="text-sm font-semibold text-white">Cargo Clients <span className="font-normal text-gray-600">— V4 persistent accounts</span></p></div><div className="flex gap-2"><button onClick={() => { setPulseMessage(null); pulse.mutate(); }} disabled={pulse.isPending} title="Send CDS Client Pulse now" className="flex items-center gap-1.5 rounded-lg border border-orange-500/30 bg-orange-500/10 px-3 py-1.5 text-xs font-semibold text-orange-300 hover:bg-orange-500/20 disabled:opacity-50"><Send size={12} />{pulse.isPending ? 'Dispatching…' : 'Send Client Pulse'}</button><button onClick={() => setShowCreate(true)} className="flex items-center gap-1.5 rounded-lg bg-orange-600 px-3 py-1.5 text-xs font-semibold text-white hover:bg-orange-500"><Plus size={12} /> New Client</button></div></div>{pulseMessage && <div className="mb-4 rounded-lg border border-orange-500/20 bg-orange-500/5 px-3 py-2 text-xs text-orange-200">{pulseMessage}</div>}
    <div className="overflow-hidden rounded-xl border border-white/[.07]" style={{ background: 'rgba(13,20,38,.5)' }}>{isLoading && <div className="p-6 text-center text-xs text-gray-500">Loading clients…</div>}{!isLoading && clients.length === 0 && <div className="p-8 text-center"><Users size={28} className="mx-auto mb-2 text-gray-700" /><p className="text-sm text-gray-500">No cargo clients yet</p><p className="mt-1 text-xs text-gray-600">Create a client account and configure its email delivery rules here.</p></div>}{clients.map((client, index) => <div key={client.id} className={index > 0 ? 'border-t border-white/[.05]' : ''}><ClientRow client={client} convoys={convoys} /></div>)}</div>
    <div className="mt-4 space-y-1 rounded-lg border border-blue-700/30 bg-blue-900/10 px-4 py-3 text-xs text-blue-300/70"><p className="font-semibold text-blue-300">Client email routing</p><p>Configure each client's Sonalit operational, Sonalit security and CDS Client Pulse subscriptions.</p><p>CDS Client Pulse runs six times daily — 00:00, 04:00, 08:00, 12:00, 16:00 and 20:00 EAT — and is sent only when active bookings exist.</p><p>The <strong>Send Client Pulse</strong> button performs an immediate manual send using the current Booking Manifest through the authoritative dispatcher.</p></div>
    {showCreate && <CreateClientModal onClose={() => setShowCreate(false)} onCreated={async client => { setShowCreate(false); try { await api.post('/settings/email-recipients', { email: client.email, name: client.name, company: client.company, enabled: true, sonalit_operational: true, sonalit_security: false, cds_client_pulse: true }); } finally { void queryClient.invalidateQueries({ queryKey: ['portal-clients'] }); void queryClient.invalidateQueries({ queryKey: ['client-email-recipients'] }); } }} />}
  </div>;
}
