import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Activity, AlertTriangle, CheckCircle2, Clock3, Mail, RefreshCw, Send, Shield, Users, X, Zap } from 'lucide-react';
import { api } from '../lib/api.js';

type Subscription={event_type:string;channel:string;enabled:boolean};
type Enrollment={id:string;domain:string;cds_customer_id:string|null;contact_role:string|null;status:string;subscriptions?:Subscription[]};
type Recipient={id:string;email:string;name:string|null;company:string|null;enabled:boolean;enrollments?:Enrollment[]};
type Customer={id:string;company_name:string;contact_name:string|null;email:string|null;status:string|null};
type Delivery={id:string;created_at:string;email?:string|null;event_type:string;channel:string;status:string;error_message?:string|null;provider_message_id?:string|null};
const PULSE='cds.client_pulse';
const active=(s:string)=>['active','verified'].includes(s);

export default function CommunicationsCommandDeckV2(){
 const qc=useQueryClient();
 const [tab,setTab]=useState<'command'|'identities'|'customers'|'delivery'>('command');
 const [confirm,setConfirm]=useState(false); const [notice,setNotice]=useState<string|null>(null);
 const recipientsQ=useQuery<{data:Recipient[]}>({queryKey:['communications-control'],queryFn:()=>api.get('/communications/recipients').then(r=>r.data),refetchInterval:30000});
 const customersQ=useQuery<{data:Customer[]}>({queryKey:['communications-customers'],queryFn:()=>api.get('/communications/customers').then(r=>r.data),refetchInterval:30000});
 const deliveryQ=useQuery<{data:Delivery[]}>({queryKey:['communications-delivery'],queryFn:()=>api.get('/communications/delivery?limit=120').then(r=>r.data),enabled:tab==='delivery',refetchInterval:tab==='delivery'?15000:false});
 const recipients=recipientsQ.data?.data??[]; const customers=customersQ.data?.data??[];
 const enrollments=recipients.flatMap(r=>r.enrollments??[]); const cds=enrollments.filter(e=>e.domain==='cds');
 const pulse=cds.filter(e=>active(e.status)&&e.subscriptions?.some(s=>s.event_type===PULSE&&s.channel==='email'&&s.enabled));
 const attention=recipients.filter(r=>!r.enabled||!r.enrollments?.length||r.enrollments.some(e=>e.status==='pending_verification')).length;
 const readyCustomers=new Set(pulse.map(e=>e.cds_customer_id).filter(Boolean));
 const refresh=()=>{void recipientsQ.refetch();void customersQ.refetch();if(tab==='delivery')void deliveryQ.refetch()};
 const invalidate=()=>{void qc.invalidateQueries({queryKey:['communications-control']});void qc.invalidateQueries({queryKey:['communications-customers']});void qc.invalidateQueries({queryKey:['communications-delivery']});};
 const dispatch=useMutation({mutationFn:()=>api.post('/admin/cds-client-pulse/send',{}),onSuccess:r=>{const d=r.data?.data??{};const queued=Number(d.queued??0);const globalQueued=Number(d.global?.queued??0);setConfirm(false);setNotice(`Dispatch accepted. ${queued} delivery job${queued===1?'':'s'} queued${globalQueued?` (${globalQueued} global Super Admin)`:''}.`);invalidate();},onError:(e:any)=>setNotice(e?.response?.data?.error??'Client Pulse dispatch failed. No delivery was confirmed.')});
 const health=attention===0;
 const routesByCustomer=useMemo(()=>new Map(customers.map(c=>[c.id,enrollments.filter(e=>e.domain==='cds'&&e.cds_customer_id===c.id)])),[customers,enrollments]);
 return <div className="min-h-full max-w-[1740px] space-y-5 pb-12 text-slate-200">
  <header className="relative overflow-hidden rounded-[30px] border border-white/[.08] bg-slate-950 p-5 shadow-2xl shadow-black/30 sm:p-7 lg:p-8">
   <div className="pointer-events-none absolute -right-32 -top-40 h-[30rem] w-[30rem] rounded-full bg-orange-500/[.10] blur-3xl"/><div className="pointer-events-none absolute bottom-[-18rem] left-[35%] h-[30rem] w-[30rem] rounded-full bg-sky-500/[.07] blur-3xl"/>
   <div className="relative flex flex-col gap-7 xl:flex-row xl:items-end xl:justify-between"><div><div className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[.28em] text-orange-300"><span className={`h-1.5 w-1.5 rounded-full ${health?'bg-emerald-400':'bg-amber-400'} shadow-[0_0_14px_currentColor]`}/> ADMIN · COMMUNICATIONS CONTROL PLANE</div><h1 className="mt-2 text-3xl font-semibold tracking-[-.04em] text-white sm:text-5xl">Communications Centre</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-400">A single command surface for communication identity, customer authority, dispatch policy and delivery truth.</p></div><div className="flex flex-wrap gap-2"><button onClick={refresh} className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/[.035] px-4 py-2.5 text-xs font-semibold text-slate-300 hover:bg-white/[.07]"><RefreshCw size={14} className={recipientsQ.isFetching?'animate-spin':''}/> Refresh intelligence</button><button onClick={()=>setConfirm(true)} disabled={dispatch.isPending} className="inline-flex items-center gap-2 rounded-xl bg-orange-500 px-4 py-2.5 text-xs font-bold text-white shadow-xl shadow-orange-950/30 hover:bg-orange-400 disabled:cursor-not-allowed disabled:bg-slate-800 disabled:text-slate-500"><Send size={14}/>{dispatch.isPending?'Preparing…':'Dispatch Client Pulse'}</button></div></div>
   <div className="relative mt-7 grid grid-cols-2 gap-2 md:grid-cols-4 xl:grid-cols-6"><Metric label="Identities" value={recipients.length} detail={`${recipients.filter(r=>r.enabled).length} enabled`} icon={Users}/><Metric label="Active routes" value={enrollments.filter(e=>active(e.status)).length} detail={`${enrollments.length} total`} icon={Zap}/><Metric label="CDS routes" value={cds.length} detail={`${customers.length} customers`} icon={Shield}/><Metric label="Pulse ready" value={pulse.length} detail={`${readyCustomers.size} customer scopes`} icon={Send}/><Metric label="Attention" value={attention} detail={attention?'review required':'all clear'} icon={AlertTriangle} warn={attention>0}/><Metric label="Control status" value={health?'READY':'REVIEW'} detail="live policy posture" icon={Activity} warn={!health}/></div>
  </header>
  {notice&&<div role="status" className="flex items-start gap-3 rounded-2xl border border-emerald-400/20 bg-emerald-400/[.05] px-4 py-3 text-xs text-emerald-200"><CheckCircle2 size={15} className="mt-0.5"/><span className="flex-1 leading-5">{notice}</span><button onClick={()=>setNotice(null)}><X size={15}/></button></div>}
  <nav className="sticky top-2 z-30 grid grid-cols-2 gap-1 rounded-2xl border border-white/[.08] bg-slate-950/90 p-1.5 shadow-xl backdrop-blur-xl md:grid-cols-4">{([['command','Command deck'],['identities','Identity registry'],['customers','Customer authority'],['delivery','Delivery assurance']] as const).map(([k,l])=><button key={k} onClick={()=>setTab(k)} className={`rounded-xl px-3 py-3 text-xs font-semibold transition ${tab===k?'bg-white/[.09] text-white shadow-inner':'text-slate-500 hover:text-slate-200'}`}>{l}</button>)}</nav>
  {tab==='command'&&<Command pulse={pulse.length} customers={customers.length} attention={attention} onCustomers={()=>setTab('customers')} onDelivery={()=>setTab('delivery')}/>} 
  {tab==='identities'&&<IdentityView recipients={recipients}/>} 
  {tab==='customers'&&<CustomerView customers={customers} routesByCustomer={routesByCustomer}/>} 
  {tab==='delivery'&&<DeliveryView rows={deliveryQ.data?.data??[]} loading={deliveryQ.isFetching}/>} 
  {confirm&&<Confirm eligible={pulse.length} customers={customers.length} busy={dispatch.isPending} onClose={()=>setConfirm(false)} onConfirm={()=>dispatch.mutate()}/>} 
 </div>;
}
function Command({pulse,customers,attention,onCustomers,onDelivery}:{pulse:number;customers:number;attention:number;onCustomers:()=>void;onDelivery:()=>void}){return <div className="space-y-5"><section className="grid gap-5 xl:grid-cols-[1.3fr_.7fr]"><Panel title="Client Pulse" eyebrow="DISPATCH ORCHESTRATION" icon={Send}><div className="text-2xl font-semibold tracking-tight text-white">Customer manifests. Precisely scoped.</div><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">Manual dispatch always includes the protected global Super Admin Client Pulse. Any eligible customer-bound CDS routes are added automatically and remain isolated.</p><div className="mt-4 flex flex-wrap gap-2"><Pill>Super Admin global</Pill><Pill>Customer-bound</Pill><Pill>Email</Pill><Pill>{pulse} customer-ready routes</Pill></div><div className="mt-5 rounded-2xl border border-sky-400/10 bg-sky-400/[.025] p-4 text-xs leading-5 text-slate-500">Customer Pulse readiness and dispatch authorization are intentionally separate. A missing customer route must not disable the global Super Admin dispatch.</div></Panel><Panel title="Live posture" eyebrow="CONTROL HEALTH" icon={Activity}><Health label="Recipient authority" ok={!attention} value={attention?`${attention} require review`:'Clear'}/><Health label="Customer routes" ok={pulse>0} value={pulse?'Operational':'Needs setup'}/><Health label="Scope isolation" ok value="Enforced"/><Health label="Delivery evidence" ok value="Auditable"/></Panel></section><section className="grid gap-4 md:grid-cols-2"><Action title="Customer authority" text="See which CDS customers have active Client Pulse routes." icon={Shield} on={onCustomers}/><Action title="Delivery assurance" text="Trace queue, provider and delivery evidence." icon={Clock3} on={onDelivery}/></section></div>}
function IdentityView({recipients}:{recipients:Recipient[]}){return <section className="overflow-hidden rounded-[26px] border border-white/[.08] bg-slate-950/70"><div className="border-b border-white/[.07] p-5"><h2 className="text-xl font-semibold text-white">Recipients & authority</h2><p className="mt-1 text-xs text-slate-500">Identity and delivery authority remain separate.</p></div><div className="divide-y divide-white/[.05]">{recipients.map(r=><article key={r.id} className="p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="text-sm font-semibold text-white">{r.name||'Unnamed recipient'}</div><div className="text-xs text-slate-500">{r.email}{r.company?` · ${r.company}`:''}</div></div><span className={r.enabled?'text-emerald-300':'text-slate-500'}>{r.enabled?'Enabled':'Disabled'}</span></div><div className="mt-3 text-[10px] text-slate-600">{r.enrollments?.length??0} communication enrollment(s)</div></article>)}</div></section>}
function CustomerView({customers,routesByCustomer}:{customers:Customer[];routesByCustomer:Map<string,Enrollment[]>}){return <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{customers.map(c=>{const routes=routesByCustomer.get(c.id)||[];const ready=routes.filter(e=>active(e.status)&&e.subscriptions?.some(s=>s.event_type===PULSE&&s.channel==='email'&&s.enabled)).length;return <article key={c.id} className="rounded-[24px] border border-white/[.07] bg-slate-950/70 p-5"><div className="flex items-start justify-between gap-3"><div><div className="text-base font-semibold text-white">{c.company_name}</div><div className="mt-1 text-xs text-slate-500">{c.contact_name||'No named contact'}</div></div><span className={ready?'text-emerald-300':'text-amber-300'}>{ready?'Pulse ready':'Setup needed'}</span></div><div className="mt-5 grid grid-cols-3 gap-2"><Mini label="Routes" value={routes.length}/><Mini label="Pulse" value={ready}/><Mini label="Status" value={c.status||'—'}/></div></article>})}{!customers.length&&<Empty text="No CDS customers available."/>}</section>}
function DeliveryView({rows,loading}:{rows:Delivery[];loading:boolean}){return <section className="overflow-hidden rounded-[26px] border border-white/[.08] bg-slate-950/70"><div className="border-b border-white/[.07] p-5"><h2 className="text-xl font-semibold text-white">Communication ledger</h2><p className="mt-1 text-xs text-slate-500">Recent communication events and provider evidence.</p></div>{loading&&!rows.length?<div className="p-10 text-center text-xs text-slate-500"><RefreshCw size={18} className="mx-auto mb-3 animate-spin"/>Loading…</div>:rows.length?<div className="divide-y divide-white/[.05]">{rows.map(r=><div key={r.id} className="grid gap-2 p-4 sm:grid-cols-[1.2fr_.8fr_.7fr_1fr] sm:items-center"><div><div className="text-xs font-semibold text-slate-200">{r.email||'Unknown recipient'}</div><div className="mt-1 text-[10px] text-slate-600">{r.event_type} · {new Date(r.created_at).toLocaleString()}</div></div><div className="text-[10px] uppercase text-slate-500">{r.channel}</div><div className="text-[10px] uppercase text-slate-400">{r.status}</div><div className="truncate text-[10px] text-slate-600">{r.error_message||r.provider_message_id||'Awaiting provider evidence'}</div></div>)}</div>:<Empty text="No delivery events in the current window."/>}</section>}
function Confirm({eligible,customers,busy,onClose,onConfirm}:{eligible:number;customers:number;busy:boolean;onClose:()=>void;onConfirm:()=>void}){return <div className="fixed inset-0 z-[80] grid place-items-center bg-black/70 p-4 backdrop-blur-md"><div className="w-full max-w-lg rounded-[28px] border border-white/10 bg-slate-950 p-6 shadow-2xl sm:p-7"><div className="flex items-start justify-between"><div><div className="text-[10px] font-semibold uppercase tracking-[.2em] text-orange-300">DISPATCH AUTHORIZATION</div><h2 className="mt-1 text-xl font-semibold text-white">Authorize Client Pulse dispatch?</h2></div><button onClick={onClose} className="rounded-xl p-2 text-slate-500 hover:bg-white/5 hover:text-white"><X size={17}/></button></div><p className="mt-4 text-sm leading-6 text-slate-400">This manual dispatch always includes the global Super Admin Client Pulse. Eligible customer-bound routes are added separately. Queued does not mean delivered.</p><div className="mt-5 grid grid-cols-3 gap-2"><Mini label="Customer routes" value={eligible}/><Mini label="Customers" value={customers}/><Mini label="Global" value="Super Admin"/></div><div className="mt-6 flex gap-2"><button onClick={onClose} disabled={busy} className="flex-1 rounded-xl border border-white/10 px-4 py-3 text-xs font-semibold text-slate-400 hover:bg-white/5">Cancel</button><button onClick={onConfirm} disabled={busy} className="flex-1 rounded-xl bg-orange-500 px-4 py-3 text-xs font-bold text-white hover:bg-orange-400 disabled:bg-slate-800">{busy?'Authorizing…':'Authorize dispatch'}</button></div></div></div>}
function Panel({eyebrow,title,icon:Icon,children}:{eyebrow:string;title:string;icon:any;children:any}){return <section className="rounded-[26px] border border-white/[.07] bg-slate-950/70 p-5 sm:p-7"><div className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[.2em] text-orange-300"><Icon size={13}/>{eyebrow}</div><h2 className="mt-1 text-xl font-semibold text-white">{title}</h2><div className="mt-6">{children}</div></section>}
function Action({title,text,icon:Icon,on}:{title:string;text:string;icon:any;on:()=>void}){return <button onClick={on} className="group rounded-[24px] border border-white/[.07] bg-slate-950/60 p-5 text-left transition hover:-translate-y-0.5 hover:border-orange-500/20"><div className="flex items-center justify-between"><div className="grid h-10 w-10 place-items-center rounded-xl border border-white/10 bg-white/[.04] text-orange-300"><Icon size={17}/></div><span className="text-slate-700">→</span></div><div className="mt-5 text-sm font-semibold text-white">{title}</div><p className="mt-1 text-xs leading-5 text-slate-500">{text}</p></button>}
function Health({label,value,ok}:{label:string;value:string;ok:boolean}){return <div className="flex items-center justify-between rounded-xl border border-white/[.06] bg-black/10 px-3 py-3"><span className="text-xs text-slate-400">{label}</span><span className={`text-[10px] font-semibold ${ok?'text-emerald-300':'text-amber-300'}`}>● {value}</span></div>}
function Metric({label,value,detail,icon:Icon,warn=false}:{label:string;value:any;detail:string;icon:any;warn?:boolean}){return <div className="rounded-2xl border border-white/[.06] bg-black/15 p-3 sm:p-4"><div className="flex items-center justify-between"><span className="text-[10px] uppercase tracking-wider text-slate-600">{label}</span><Icon size={14} className={warn?'text-amber-300':'text-slate-600'}/></div><div className={`mt-2 text-xl font-semibold ${warn?'text-amber-200':'text-white'}`}>{value}</div><div className="mt-1 text-[10px] text-slate-600">{detail}</div></div>}
function Mini({label,value}:{label:string;value:any}){return <div className="rounded-xl border border-white/[.06] bg-white/[.02] p-3"><div className="text-[9px] uppercase tracking-wider text-slate-600">{label}</div><div className="mt-1 text-xs font-semibold text-slate-300">{value}</div></div>}
function Pill({children}:{children:any}){return <span className="rounded-full border border-white/10 bg-white/[.03] px-2.5 py-1 text-[10px] font-semibold text-slate-400">{children}</span>}
function Empty({text}:{text:string}){return <div className="p-10 text-center text-xs text-slate-600">{text}</div>}
