import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Activity, AlertTriangle, ArrowRight, CheckCircle2, Clock3, Mail, RefreshCw, Search, Send, Shield, Sparkles, Users, X, Zap } from 'lucide-react';
import { api } from '../lib/api.js';

type Recipient={id:string;email:string;name:string|null;company:string|null;enabled:boolean;enrollments?:Enrollment[]};
type Enrollment={id:string;domain:'platform'|'fleet'|'cds';cds_customer_id:string|null;contact_role:string|null;status:string;subscriptions?:Subscription[]};
type Subscription={id:string;event_type:string;channel:string;enabled:boolean;delivery_mode:string;critical_override:boolean};
type Customer={id:string;company_name:string;contact_name:string|null;email:string|null;phone:string|null;status:string|null};
type Delivery={id:string;created_at:string;email?:string|null;domain?:string|null;event_type:string;channel:string;status:string;error_code?:string|null;error_message?:string|null;provider_message_id?:string|null};
type Notice={kind:'ok'|'warn'|'error';text:string};
const PULSE='cds.client_pulse';
const active=(s:string)=>['active','verified'].includes(s);

export default function CommunicationsCommandDeck(){
 const qc=useQueryClient();
 const [view,setView]=useState<'overview'|'identities'|'customers'|'delivery'>('overview');
 const [search,setSearch]=useState(''); const [notice,setNotice]=useState<Notice|null>(null); const [confirm,setConfirm]=useState(false);
 const recipientsQ=useQuery<{data:Recipient[]}>({queryKey:['communications-control'],queryFn:()=>api.get('/communications/recipients').then(r=>r.data),refetchInterval:30000});
 const customersQ=useQuery<{data:Customer[]}>({queryKey:['communications-customers'],queryFn:()=>api.get('/communications/customers').then(r=>r.data),refetchInterval:30000});
 const deliveryQ=useQuery<{data:Delivery[]}>({queryKey:['communications-delivery'],queryFn:()=>api.get('/communications/delivery?limit=120').then(r=>r.data),enabled:view==='delivery',refetchInterval:view==='delivery'?15000:false});
 const recipients=recipientsQ.data?.data??[]; const customers=customersQ.data?.data??[];
 const enrollments=recipients.flatMap(r=>r.enrollments??[]); const cds=enrollments.filter(e=>e.domain==='cds');
 const pulse=cds.filter(e=>active(e.status)&&e.subscriptions?.some(s=>s.event_type===PULSE&&s.channel==='email'&&s.enabled));
 const attention=recipients.filter(r=>!r.enabled||!r.enrollments?.length||r.enrollments.some(e=>e.status==='pending_verification')).length;
 const readyCustomers=new Set(pulse.map(e=>e.cds_customer_id).filter(Boolean));
 const refresh=()=>{void recipientsQ.refetch();void customersQ.refetch();if(view==='delivery')void deliveryQ.refetch()};
 const dispatch=useMutation({mutationFn:()=>api.post('/admin/cds-client-pulse/send',{}),onSuccess:r=>{const d=r.data?.data??{};const queued=Number(d.queued??0);const failed=Number(d.failures??0);setConfirm(false);setNotice({kind:failed?'warn':'ok',text:failed?`Dispatch accepted with ${failed} route failure${failed===1?'':'s'}. ${queued} job${queued===1?'':'s'} queued.`:`Dispatch accepted. ${queued} delivery job${queued===1?'':'s'} queued.`});invalidate();},onError:(e:any)=>setNotice({kind:'error',text:e?.response?.data?.error??'Dispatch failed. No delivery was confirmed.'})});
 const invalidate=()=>{void qc.invalidateQueries({queryKey:['communications-control']});void qc.invalidateQueries({queryKey:['communications-customers']});void qc.invalidateQueries({queryKey:['communications-delivery']});};
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();if(!q)return recipients;return recipients.filter(r=>[r.email,r.name,r.company,...(r.enrollments??[]).map(e=>e.cds_customer_id)].filter(Boolean).some(v=>String(v).toLowerCase().includes(q)))},[recipients,search]);
 const health=attention===0&&pulse.length>0;
 return <div className="min-h-full max-w-[1740px] space-y-5 pb-12 text-slate-200">
  <header className="relative overflow-hidden rounded-[30px] border border-white/[.08] bg-slate-950 p-5 shadow-2xl shadow-black/30 sm:p-7 lg:p-8">
   <div className="pointer-events-none absolute -right-32 -top-40 h-[30rem] w-[30rem] rounded-full bg-orange-500/[.10] blur-3xl"/><div className="pointer-events-none absolute bottom-[-18rem] left-[35%] h-[30rem] w-[30rem] rounded-full bg-sky-500/[.07] blur-3xl"/>
   <div className="relative flex flex-col gap-7 xl:flex-row xl:items-end xl:justify-between">
    <div><div className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[.28em] text-orange-300"><span className={`h-1.5 w-1.5 rounded-full ${health?'bg-emerald-400':'bg-amber-400'} shadow-[0_0_14px_currentColor]`}/> ADMIN · COMMUNICATIONS CONTROL PLANE</div><h1 className="mt-2 text-3xl font-semibold tracking-[-.04em] text-white sm:text-5xl">Communications Centre</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-400">A single command surface for communication identity, customer authority, dispatch policy and delivery truth.</p></div>
    <div className="flex flex-wrap gap-2"><button onClick={refresh} className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/[.035] px-4 py-2.5 text-xs font-semibold text-slate-300 hover:bg-white/[.07]"><RefreshCw size={14} className={recipientsQ.isFetching?'animate-spin':''}/> Refresh intelligence</button><button onClick={()=>setConfirm(true)} disabled={!pulse.length||dispatch.isPending} className="inline-flex items-center gap-2 rounded-xl bg-orange-500 px-4 py-2.5 text-xs font-bold text-white shadow-xl shadow-orange-950/30 hover:bg-orange-400 disabled:cursor-not-allowed disabled:bg-slate-800 disabled:text-slate-500"><Send size={14}/>{dispatch.isPending?'Preparing…':'Dispatch Client Pulse'}</button></div>
   </div>
   <div className="relative mt-7 grid grid-cols-2 gap-2 md:grid-cols-4 xl:grid-cols-6"><Metric label="Identities" value={recipients.length} detail={`${recipients.filter(r=>r.enabled).length} enabled`} icon={Users}/><Metric label="Active routes" value={enrollments.filter(e=>active(e.status)).length} detail={`${enrollments.length} total`} icon={Zap}/><Metric label="CDS routes" value={cds.length} detail={`${customers.length} customers`} icon={Shield}/><Metric label="Pulse ready" value={pulse.length} detail={`${readyCustomers.size} customer scopes`} icon={Send}/><Metric label="Attention" value={attention} detail={attention?'review required':'all clear'} icon={AlertTriangle} warn={attention>0}/><Metric label="Control status" value={health?'READY':'REVIEW'} detail="live policy posture" icon={Activity} warn={!health}/></div>
  </header>
  {notice&&<div role="status" className={`flex items-start gap-3 rounded-2xl border px-4 py-3 text-xs ${notice.kind==='error'?'border-red-400/20 bg-red-400/[.05] text-red-200':notice.kind==='warn'?'border-amber-400/20 bg-amber-400/[.05] text-amber-200':'border-emerald-400/20 bg-emerald-400/[.05] text-emerald-200'}`}><CheckCircle2 size={15} className="mt-0.5"/><span className="flex-1 leading-5">{notice.text}</span><button onClick={()=>setNotice(null)}><X size={15}/></button></div>}
  <nav className="sticky top-2 z-30 grid grid-cols-2 gap-1 rounded-2xl border border-white/[.08] bg-slate-950/90 p-1.5 shadow-xl backdrop-blur-xl md:grid-cols-4">{([['overview','Command deck',Activity],['identities','Identity registry',Users],['customers','Customer authority',Shield],['delivery','Delivery assurance',Clock3]] as const).map(([k,l,I])=><button key={k} onClick={()=>setView(k)} className={`rounded-xl px-3 py-3 text-xs font-semibold transition ${view===k?'bg-white/[.09] text-white shadow-inner':'text-slate-500 hover:text-slate-200'}`}><I size={14} className="mr-2 inline"/>{l}</button>)}</nav>
  {view==='overview'&&<Overview pulse={pulse.length} customers={customers.length} attention={attention} on={setView} />}
  {view==='identities'&&<section className="overflow-hidden rounded-[26px] border border-white/[.08] bg-slate-950/70"><div className="flex flex-col gap-4 border-b border-white/[.07] p-5 sm:flex-row sm:items-center sm:justify-between"><div><Eyebrow>IDENTITY REGISTRY</Eyebrow><h2 className="mt-1 text-xl font-semibold text-white">Recipients & authority</h2><p className="mt-1 text-xs text-slate-500">An identity is never authorization. Customer scope and subscriptions remain explicit.</p></div><div className="relative w-full sm:max-w-sm"><Search size={14} className="absolute left-3 top-3 text-slate-600"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search identity, company, customer…" className="w-full rounded-xl border border-white/10 bg-black/20 py-2.5 pl-9 pr-3 text-xs text-white outline-none focus:border-orange-500/30"/></div></div><div className="divide-y divide-white/[.05]">{filtered.map(r=><Identity key={r.id} r={r}/>)}</div>{!filtered.length&&<Empty text="No identities match the current search."/>}</section>}
  {view==='customers'&&<CustomerGrid customers={customers} enrollments={enrollments}/>} 
  {view==='delivery'&&<DeliveryGrid rows={deliveryQ.data?.data??[]} loading={deliveryQ.isFetching}/>} 
  {confirm&&<Confirm eligible={pulse.length} busy={dispatch.isPending} onClose={()=>setConfirm(false)} onConfirm={()=>dispatch.mutate()}/>} 
 </div>;
}
function Overview({pulse,customers,attention,on}:{pulse:number;customers:number;attention:number;on:(v:'overview'|'identities'|'customers'|'delivery')=>void}){return <div className="space-y-5"><section className="grid gap-5 xl:grid-cols-[1.3fr_.7fr]"><Panel eyebrow="DISPATCH ORCHESTRATION" title="Client Pulse" icon={Send}><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><div className="text-2xl font-semibold tracking-tight text-white">Customer manifests. Precisely scoped.</div><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">Every route resolves against an enabled recipient, an active CDS customer enrollment and an enabled Client Pulse subscription. No blind broadcast.</p><div className="mt-4 flex flex-wrap gap-2"><Pill>Customer-bound</Pill><Pill>Email</Pill><Pill>{pulse} eligible routes</Pill><Pill>Admin authority</Pill></div></div><div className="rounded-2xl border border-orange-400/15 bg-orange-400/[.04] p-4 lg:min-w-[220px]"><div className="text-[10px] uppercase tracking-[.18em] text-orange-300">Readiness</div><div className="mt-1 text-lg font-semibold text-white">{pulse?'Dispatchable':'Awaiting setup'}</div><div className="mt-1 text-xs text-slate-500">{customers} registered CDS customers</div></div></div></Panel><Panel eyebrow="LIVE POSTURE" title="Control health" icon={Activity}><Health label="Recipient authority" ok={attention===0} value={attention?`${attention} require review`:'Clear'}/><Health label="CDS routing" ok={pulse>0} value={pulse?'Operational':'Not ready'}/><Health label="Scope isolation" ok value="Enforced"/><Health label="Delivery evidence" ok value="Auditable"/></Panel></section><section className="grid gap-4 md:grid-cols-3"><Action title="Identity registry" text="Inspect recipient state, customer bindings and route authority." icon={Users} on={()=>on('identities')}/><Action title="Customer authority" text="See exactly which clients can receive which communications." icon={Shield} on={()=>on('customers')}/><Action title="Delivery assurance" text="Trace dispatches from queue state through provider evidence." icon={Clock3} on={()=>on('delivery')}/></section><section className="rounded-[26px] border border-white/[.07] bg-gradient-to-r from-slate-950 to-slate-900/70 p-5 sm:p-7"><div className="flex items-start gap-4"><div className="rounded-2xl border border-orange-400/15 bg-orange-400/[.06] p-3"><Sparkles size={19} className="text-orange-300"/></div><div><Eyebrow>OPERATIONS PRINCIPLE</Eyebrow><h3 className="mt-1 text-lg font-semibold text-white">The Centre reports truth, not optimism.</h3><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">Queued is not delivered. A healthy identity is not a healthy route. A generated workbook is not a successful communication. The delivery ledger is the source of operational truth.</p></div></div></section></div>}
function Identity({r}:{r:Recipient}){return <article className="p-5 transition hover:bg-white/[.015] sm:p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><div className="flex items-center gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-white/10 bg-white/[.04] text-sm font-bold text-slate-300">{(r.name||r.email).slice(0,1).toUpperCase()}</div><div className="min-w-0"><div className="truncate text-sm font-semibold text-white">{r.name||'Unnamed recipient'}</div><div className="truncate text-xs text-slate-500">{r.email}{r.company?` · ${r.company}`:''}</div></div><span className={`rounded-full border px-2 py-1 text-[9px] font-semibold uppercase tracking-wider ${r.enabled?'border-emerald-400/20 bg-emerald-400/[.04] text-emerald-300':'border-slate-400/10 bg-white/[.03] text-slate-500'}`}>{r.enabled?'Enabled':'Disabled'}</span></div></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4 lg:min-w-[520px]">{(r.enrollments??[]).map(e=><div key={e.id} className="rounded-xl border border-white/[.06] bg-black/10 p-3"><div className="text-[9px] uppercase tracking-wider text-slate-600">{e.domain}</div><div className="mt-1 text-xs font-semibold text-slate-300">{e.status}</div><div className="mt-1 text-[10px] text-slate-600">{e.subscriptions?.filter(s=>s.enabled).length??0} active subscriptions</div></div>)}</div></div></article>}
function CustomerGrid({customers,enrollments}:{customers:Customer[];enrollments:Enrollment[]}){return <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{customers.map(c=>{const routes=enrollments.filter(e=>e.domain==='cds'&&e.cds_customer_id===c.id);const eligible=routes.filter(e=>active(e.status)&&e.subscriptions?.some(s=>s.event_type===PULSE&&s.channel==='email'&&s.enabled)).length;return <article key={c.id} className="group rounded-[24px] border border-white/[.07] bg-slate-950/70 p-5 transition hover:-translate-y-0.5 hover:border-orange-500/20"><div className="flex items-start justify-between gap-3"><div><div className="text-base font-semibold text-white">{c.company_name}</div><div className="mt-1 text-xs text-slate-500">{c.contact_name||'No named contact'}</div></div><span className={`rounded-full border px-2.5 py-1 text-[10px] font-semibold ${eligible?'border-emerald-400/20 bg-emerald-400/[.04] text-emerald-300':'border-amber-400/20 bg-amber-400/[.04] text-amber-300'}`}>{eligible?'Pulse ready':'Setup needed'}</span></div><div className="mt-6 grid grid-cols-3 gap-2"><Mini label="Routes" value={routes.length}/><Mini label="Enabled" value={routes.reduce((n,e)=>n+(e.subscriptions?.filter(s=>s.enabled).length??0),0)}/><Mini label="Pulse" value={eligible}/></div></article>})}{!customers.length&&<Empty text="No CDS customers available."/>}</section>}
function DeliveryGrid({rows,loading}:{rows:Delivery[];loading:boolean}){return <section className="overflow-hidden rounded-[26px] border border-white/[.08] bg-slate-950/70"><div className="border-b border-white/[.07] p-5"><Eyebrow>DELIVERY ASSURANCE</Eyebrow><div className="mt-1 flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-semibold text-white">Communication ledger</h2><p className="mt-1 text-xs text-slate-500">Recent communication events and provider evidence.</p></div>{loading&&<RefreshCw size={14} className="animate-spin text-slate-500"/>}</div></div><div className="divide-y divide-white/[.05]">{rows.map(r=><div key={r.id} className="grid gap-3 p-4 sm:grid-cols-[1.2fr_.8fr_.7fr_.8fr] sm:items-center"><div><div className="text-xs font-semibold text-slate-200">{r.email||'Unknown recipient'}</div><div className="mt-1 text-[10px] text-slate-600">{r.event_type} · {new Date(r.created_at).toLocaleString()}</div></div><div className="text-[10px] uppercase tracking-wider text-slate-500">{r.channel}</div><div><span className={`rounded-full border px-2 py-1 text-[9px] font-semibold uppercase ${r.status==='sent'||r.status==='delivered'?'border-emerald-400/20 text-emerald-300':r.status==='failed'||r.status==='bounced'?'border-red-400/20 text-red-300':'border-amber-400/20 text-amber-300'}`}>{r.status}</span></div><div className="truncate text-[10px] text-slate-600">{r.error_message||r.provider_message_id||'Awaiting provider evidence'}</div></div>)}{!rows.length&&<Empty text="No delivery events in the current window."/>}</div></section>}
function Confirm({eligible,busy,onClose,onConfirm}:{eligible:number;busy:boolean;onClose:()=>void;onConfirm:()=>void}){return <div className="fixed inset-0 z-[80] grid place-items-center bg-black/70 p-4 backdrop-blur-md"><div className="w-full max-w-lg rounded-[28px] border border-white/10 bg-slate-950 p-6 shadow-2xl sm:p-7"><div className="flex items-start justify-between"><div><Eyebrow>DISPATCH AUTHORIZATION</Eyebrow><h2 className="mt-1 text-xl font-semibold text-white">Authorize Client Pulse dispatch?</h2></div><button onClick={onClose} className="rounded-xl p-2 text-slate-500 hover:bg-white/5 hover:text-white"><X size={17}/></button></div><p className="mt-4 text-sm leading-6 text-slate-400">Sonalit will resolve eligible customer-bound routes and create delivery jobs. This action does not guarantee provider delivery.</p><div className="mt-5 grid grid-cols-3 gap-2"><Mini label="Eligible routes" value={eligible}/><Mini label="Scope" value="CDS"/><Mini label="Authority" value="Admin"/></div><div className="mt-6 flex gap-2"><button onClick={onClose} className="flex-1 rounded-xl border border-white/10 px-4 py-3 text-xs font-semibold text-slate-400 hover:bg-white/5">Cancel</button><button onClick={onConfirm} disabled={busy} className="flex-1 rounded-xl bg-orange-500 px-4 py-3 text-xs font-bold text-white hover:bg-orange-400 disabled:bg-slate-800">{busy?'Authorizing…':'Authorize dispatch'}</button></div></div></div>}
function Panel({eyebrow,title,icon:Icon,children}:{eyebrow:string;title:string;icon:any;children:any}){return <section className="rounded-[26px] border border-white/[.07] bg-slate-950/70 p-5 sm:p-7"><div className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[.2em] text-orange-300"><Icon size={13}/>{eyebrow}</div><h2 className="mt-1 text-xl font-semibold text-white">{title}</h2><div className="mt-6">{children}</div></section>}
function Action({title,text,icon:Icon,on}:{title:string;text:string;icon:any;on:()=>void}){return <button onClick={on} className="group rounded-[24px] border border-white/[.07] bg-slate-950/60 p-5 text-left transition hover:-translate-y-0.5 hover:border-orange-500/20"><div className="flex items-center justify-between"><div className="grid h-10 w-10 place-items-center rounded-xl border border-white/10 bg-white/[.04] text-orange-300"><Icon size={17}/></div><ArrowRight size={15} className="text-slate-700 transition group-hover:translate-x-1 group-hover:text-orange-300"/></div><div className="mt-5 text-sm font-semibold text-white">{title}</div><p className="mt-1 text-xs leading-5 text-slate-500">{text}</p></button>}
function Health({label,value,ok,warn=false}:{label:string;value:string;ok:boolean;warn?:boolean}){return <div className="flex items-center justify-between rounded-xl border border-white/[.06] bg-black/10 px-3 py-3"><span className="text-xs text-slate-400">{label}</span><span className={`text-[10px] font-semibold ${warn?'text-amber-300':ok?'text-emerald-300':'text-red-300'}`}>{ok?'● ':warn?'● ':'● '}{value}</span></div>}
function Metric({label,value,detail,icon:Icon,warn=false}:{label:string;value:any;detail:string;icon:any;warn?:boolean}){return <div className="rounded-2xl border border-white/[.06] bg-black/15 p-3 sm:p-4"><div className="flex items-center justify-between"><span className="text-[10px] uppercase tracking-wider text-slate-600">{label}</span><Icon size={14} className={warn?'text-amber-300':'text-slate-600'}/></div><div className={`mt-2 text-xl font-semibold ${warn?'text-amber-200':'text-white'}`}>{value}</div><div className="mt-1 text-[10px] text-slate-600">{detail}</div></div>}
function Mini({label,value}:{label:string;value:any}){return <div className="rounded-xl border border-white/[.06] bg-white/[.02] p-3"><div className="text-[9px] uppercase tracking-wider text-slate-600">{label}</div><div className="mt-1 text-xs font-semibold text-slate-300">{value}</div></div>}
function Pill({children}:{children:any}){return <span className="rounded-full border border-white/10 bg-white/[.03] px-2.5 py-1 text-[10px] font-semibold text-slate-400">{children}</span>}
function Eyebrow({children}:{children:any}){return <div className="text-[10px] font-semibold uppercase tracking-[.2em] text-orange-300">{children}</div>}
function Empty({text}:{text:string}){return <div className="p-10 text-center text-xs text-slate-600">{text}</div>}
