import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Activity, CheckCircle2, ChevronDown, Clock3, Plus, Radio, RefreshCw, Search, Send, Shield, Users, XCircle } from 'lucide-react';
import { api } from '../lib/api.js';

type Subscription = { id:string; event_type:string; channel:string; delivery_mode:string; enabled:boolean; critical_override:boolean };
type Enrollment = { id:string; domain:'platform'|'fleet'|'cds'; cds_customer_id:string|null; contact_role:string|null; locale:string|null; timezone:string|null; status:string; subscriptions:Subscription[] };
type Recipient = { id:string; email:string; name:string|null; company:string|null; enabled:boolean; enrollments:Enrollment[] };
type Customer = { id:string; company_name:string; contact_name:string|null; email:string|null; phone:string|null; status:string|null };

const CATALOG = [
  ['fleet','fleet.operational','Operational events'], ['fleet','fleet.security','Security incidents'],
  ['cds','cds.booking_created','Booking created'], ['cds','cds.booking_approved','Booking approved'], ['cds','cds.dispatch','Dispatch / trip start'],
  ['cds','cds.trip_delayed','Trip delay / exception'], ['cds','cds.at_port','At port'], ['cds','cds.delivery','Delivery'],
  ['cds','cds.elock_tamper','E-lock tamper / security'], ['cds','cds.client_pulse','Client Pulse / manifest digest'],
] as const;

export default function CommunicationsControlPlane() {
  const qc=useQueryClient();
  const [tab,setTab]=useState<'overview'|'recipients'|'cds'|'delivery'>('overview');
  const [search,setSearch]=useState(''); const [showAdd,setShowAdd]=useState(false); const [notice,setNotice]=useState<string|null>(null);
  const [form,setForm]=useState({email:'',name:'',company:''});
  const recipientsQ=useQuery<{data:Recipient[]}>({queryKey:['communications-control'],queryFn:()=>api.get('/communications/recipients').then(r=>r.data)});
  const customersQ=useQuery<{data:Customer[]}>({queryKey:['communications-customers'],queryFn:()=>api.get('/communications/customers').then(r=>r.data),enabled:tab==='cds'||tab==='overview'});
  const deliveryQ=useQuery({queryKey:['communications-delivery'],queryFn:()=>api.get('/communications/delivery?limit=80').then(r=>r.data),enabled:tab==='delivery'});
  const rows=recipientsQ.data?.data??[]; const customers=customersQ.data?.data??[];
  const active=rows.filter(r=>r.enabled).length; const enrollments=rows.flatMap(r=>r.enrollments); const activeEnrollments=enrollments.filter(e=>['verified','active'].includes(e.status)).length;
  const cdsEnrollments=enrollments.filter(e=>e.domain==='cds'); const pulse=cdsEnrollments.filter(e=>e.subscriptions.some(s=>s.event_type==='cds.client_pulse'&&s.channel==='email'&&s.enabled)).length;
  const filtered=useMemo(()=>rows.filter(r=>{const q=search.toLowerCase().trim();return !q||[r.email,r.name,r.company,...r.enrollments.map(e=>e.cds_customer_id)].filter(Boolean).some(v=>String(v).toLowerCase().includes(q));}),[rows,search]);
  const add=useMutation({mutationFn:()=>api.post('/communications/recipients',{email:form.email.trim().toLowerCase(),name:form.name.trim()||null,company:form.company.trim()||null,enabled:true}),onSuccess:()=>{setShowAdd(false);setForm({email:'',name:'',company:''});setNotice('Recipient created. Create a domain enrollment before delivery is enabled.');void qc.invalidateQueries({queryKey:['communications-control']});},onError:(e:any)=>setNotice(e?.response?.data?.error??'Recipient creation failed.')});
  const pulseSend=useMutation({mutationFn:()=>api.post('/settings/cds-client-pulse/send',{}),onSuccess:(r)=>setNotice(`Scoped Client Pulse dispatch completed: ${r.data?.data?.queued??0} queued.`),onError:(e:any)=>setNotice(e?.response?.data?.error??'Client Pulse dispatch failed.')});
  const enroll=useMutation({mutationFn:(body:any)=>api.post('/communications/enrollments',body),onSuccess:()=>{setNotice('Enrollment saved. Delivery is now governed by its explicit event subscriptions.');void qc.invalidateQueries({queryKey:['communications-control']});},onError:(e:any)=>setNotice(e?.response?.data?.error??'Enrollment failed.')});
  const status=useMutation({mutationFn:({id,status}:{id:string;status:string})=>api.patch(`/communications/enrollments/${id}`,{status}),onSuccess:()=>void qc.invalidateQueries({queryKey:['communications-control']})});
  const subscription=useMutation({mutationFn:({id,event_type,enabled}:{id:string;event_type:string;enabled:boolean})=>api.put(`/communications/enrollments/${id}/subscriptions`,{subscriptions:[{event_type,channel:'email',delivery_mode:'immediate',critical_override:true,enabled}]}),onSuccess:()=>void qc.invalidateQueries({queryKey:['communications-control']})});
  return <div className="min-h-full max-w-[1600px] space-y-5">
    <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2 text-[10px] font-mono uppercase tracking-[.2em] text-orange-400"><Radio size={12}/> Communications Control Plane</div><h1 className="mt-2 text-2xl font-semibold text-white">Domain-aware communication orchestration.</h1><p className="mt-1 max-w-4xl text-xs leading-5 text-slate-400">Recipients are identities. Enrollments are authoritative relationships. Subscriptions decide exactly what can be delivered. CDS is customer-bound and never falls back to an organization-wide recipient list.</p></div><div className="flex gap-2"><button onClick={()=>void recipientsQ.refetch()} className="flex items-center gap-2 rounded-lg border border-white/10 px-3 py-2 text-xs text-slate-300"><RefreshCw size={13} className={recipientsQ.isFetching?'animate-spin':''}/> Refresh</button><button onClick={()=>setShowAdd(true)} className="flex items-center gap-2 rounded-lg bg-orange-600 px-3 py-2 text-xs font-semibold text-white"><Plus size={13}/> Add recipient</button></div></header>
    {notice&&<div className="flex items-center gap-2 rounded-lg border border-blue-500/20 bg-blue-500/5 px-3 py-2 text-xs text-blue-200"><CheckCircle2 size={13}/>{notice}<button className="ml-auto" onClick={()=>setNotice(null)}><XCircle size={13}/></button></div>}
    <div className="grid grid-cols-2 gap-3 xl:grid-cols-5"><Metric icon={Users} label="Identities" value={rows.length} detail={`${active} enabled`}/><Metric icon={Activity} label="Enrollments" value={enrollments.length} detail={`${activeEnrollments} active / verified`}/><Metric icon={Radio} label="CDS enrollments" value={cdsEnrollments.length} detail={`${customers.length} CDS customers`}/><Metric icon={Send} label="Client Pulse" value={pulse} detail="customer-bound email routes"/><Metric icon={Shield} label="Delivery posture" value="Explicit" detail="no legacy broadcast authority"/></div>
    <nav className="flex gap-1 overflow-x-auto rounded-xl border border-white/[.07] bg-slate-900/40 p-1">{([['overview','Overview'],['recipients','Recipients & enrollment'],['cds','CDS communications'],['delivery','Delivery audit']] as const).map(([k,l])=><button key={k} onClick={()=>setTab(k)} className={`rounded-lg px-4 py-2 text-xs font-semibold ${tab===k?'bg-white/10 text-white':'text-slate-500 hover:text-slate-300'}`}>{l}</button>)}</nav>
    {tab==='overview'&&<section className="grid gap-4 lg:grid-cols-2"><Panel title="Communication architecture" icon={Radio}><div className="space-y-3">{[['Identity','Recipient record — no portal access'],['Domain enrollment','Platform / Fleet / specific CDS customer'],['Subscription','Event + channel + delivery mode'],['Policy','Quiet hours + critical override'],['Audit','Every delivery and policy change traceable']].map(([a,b])=><div key={a} className="flex items-center justify-between rounded-lg border border-white/[.06] bg-black/20 p-3"><span className="text-xs font-semibold text-white">{a}</span><span className="text-[10px] text-slate-500">{b}</span></div>)}</div></Panel><Panel title="Operational safeguards" icon={Shield}><ul className="space-y-3 text-xs leading-5 text-slate-400"><li>• CDS Client Pulse is scoped by <b className="text-white">org + cds_customer_id</b>.</li><li>• A CDS recipient must have an active/verified CDS enrollment and an enabled <b className="text-white">cds.client_pulse</b> subscription.</li><li>• Fleet security/operational mail requires explicit Fleet subscriptions for external recipients.</li><li>• Portal login membership is never inferred from communication enrollment.</li><li>• Delivery audit stores correlation metadata and payload hashes, not raw sensitive payloads.</li></ul></Panel></section>}
    {tab==='recipients'&&<section className="rounded-xl border border-white/[.07] bg-slate-900/40"><div className="border-b border-white/[.07] p-4"><div className="relative"><Search size={14} className="absolute left-3 top-2.5 text-slate-600"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search recipient, company or CDS customer…" className="w-full rounded-lg border border-white/10 bg-black/20 py-2 pl-9 pr-3 text-xs text-white outline-none"/></div></div><div className="divide-y divide-white/[.05]">{filtered.map(r=><RecipientCard key={r.id} row={r} customers={customers} onEnroll={(body:any)=>enroll.mutate(body)} onStatus={(id,s)=>status.mutate({id,status:s})} onSubscription={(id,event_type,enabled)=>subscription.mutate({id,event_type,enabled})}/>)}</div>{!filtered.length&&<div className="p-12 text-center text-xs text-slate-500">No recipients found.</div>}</section>}
    {tab==='cds'&&<section className="grid gap-4 xl:grid-cols-[1fr_360px]"><Panel title="CDS customer communications" icon={Radio}><div className="space-y-2">{customers.map(c=>{const routes=enrollments.filter(e=>e.domain==='cds'&&e.cds_customer_id===c.id);const routeCount=routes.reduce((n,e)=>n+e.subscriptions.filter(s=>s.enabled).length,0);return <div key={c.id} className="rounded-xl border border-orange-500/10 bg-orange-500/[.025] p-4"><div className="flex items-center justify-between"><div><div className="text-sm font-semibold text-white">{c.company_name}</div><div className="mt-1 text-[10px] text-slate-500">{c.contact_name??'No named contact'} · {c.email??'No email'}</div></div><span className="rounded-full border border-white/10 px-2 py-1 text-[10px] text-slate-400">{routes.length} enrollments</span></div><div className="mt-3 text-[10px] text-slate-500">{routeCount} enabled subscriptions · booking data remains customer-scoped</div></div>})}</div></Panel><Panel title="Client Pulse" icon={Send}><p className="text-xs leading-5 text-slate-400">Manual dispatch runs per enrolled CDS customer. A customer receives only its own active booking manifest.</p><button onClick={()=>pulseSend.mutate()} disabled={pulseSend.isPending||pulse===0} className="mt-4 flex w-full items-center justify-center gap-2 rounded-lg bg-orange-600 py-2.5 text-xs font-semibold text-white disabled:opacity-40">{pulseSend.isPending?<RefreshCw size={13} className="animate-spin"/>:<Send size={13}/>} {pulseSend.isPending?'Dispatching…':'Send scoped Client Pulse'}</button><div className="mt-3 text-[10px] text-slate-600">{pulse} customer-bound email subscriptions currently eligible.</div></Panel></section>}
    {tab==='delivery'&&<Panel title="Delivery & audit" icon={Clock3}>{(deliveryQ.data?.data??[]).length?<div className="overflow-auto"><table className="w-full text-left text-xs"><thead><tr className="border-b border-white/[.06] text-[10px] uppercase tracking-wider text-slate-600"><th className="p-3">Time</th><th>Recipient</th><th>Domain</th><th>Event</th><th>Channel</th><th>Status</th></tr></thead><tbody>{(deliveryQ.data?.data??[]).map((d:any)=><tr key={d.id} className="border-b border-white/[.04] text-slate-400"><td className="p-3 whitespace-nowrap">{new Date(d.created_at).toLocaleString()}</td><td>{d.email??'—'}</td><td>{d.domain??'—'}</td><td>{d.event_type}</td><td>{d.channel}</td><td><span className="rounded-full border border-white/10 px-2 py-1 text-[10px]">{d.status}</span></td></tr>)}</tbody></table></div>:<div className="p-8 text-center text-xs text-slate-500">No delivery events yet.</div>}</Panel>}
    {showAdd&&<div className="fixed inset-0 z-[500] flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm"><div className="w-full max-w-lg rounded-2xl border border-white/10 bg-slate-950 p-6"><div className="flex justify-between"><div><div className="text-[10px] font-mono uppercase tracking-[.18em] text-orange-400">Identity registry</div><h2 className="mt-1 text-lg font-semibold text-white">Add recipient</h2></div><button onClick={()=>setShowAdd(false)}><XCircle size={16} className="text-slate-500"/></button></div><div className="mt-5 grid gap-3">{(['email','name','company'] as const).map(k=><input key={k} type={k==='email'?'email':'text'} placeholder={k==='email'?'client@example.com':k==='name'?'Contact name':'Company'} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} className="rounded-lg border border-white/10 bg-white/[.04] px-3 py-2.5 text-xs text-white outline-none"/>)}</div><p className="mt-3 text-[10px] leading-4 text-slate-500">Creating an identity does not authorize any delivery. Enrollment and subscriptions are separate steps.</p><div className="mt-5 flex justify-end gap-2"><button onClick={()=>setShowAdd(false)} className="rounded-lg border border-white/10 px-4 py-2 text-xs text-slate-400">Cancel</button><button onClick={()=>add.mutate()} disabled={!form.email||add.isPending} className="rounded-lg bg-orange-600 px-4 py-2 text-xs font-semibold text-white disabled:opacity-40">{add.isPending?'Creating…':'Create identity'}</button></div></div></div>}
  </div>;
}
function Metric({icon:Icon,label,value,detail}:{icon:any;label:string;value:string|number;detail:string}){return <div className="rounded-xl border border-white/[.07] bg-slate-900/60 p-4"><div className="flex items-center justify-between text-[10px] uppercase tracking-[.15em] text-slate-500"><span>{label}</span><Icon size={14}/></div><div className="mt-2 text-2xl font-semibold text-white">{value}</div><div className="mt-1 text-[10px] text-slate-500">{detail}</div></div>}
function Panel({title,icon:Icon,children}:{title:string;icon:any;children:any}){return <div className="rounded-xl border border-white/[.07] bg-slate-900/40 p-5"><div className="mb-4 flex items-center gap-2 text-xs font-semibold text-white"><Icon size={14} className="text-orange-300"/>{title}</div>{children}</div>}
function RecipientCard({row,customers,onEnroll,onStatus,onSubscription}:{row:Recipient;customers:Customer[];onEnroll:(b:any)=>void;onStatus:(id:string,s:string)=>void;onSubscription:(id:string,e:string,v:boolean)=>void}){const [open,setOpen]=useState(false);const initials=(row.name?.trim()||row.email).charAt(0).toUpperCase();return <div className="p-4"><button onClick={()=>setOpen(!open)} className="flex w-full items-center gap-3 text-left"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full border border-orange-500/20 bg-orange-500/10 text-xs font-bold text-orange-300">{initials}</div><div className="min-w-0 flex-1"><div className="text-xs font-semibold text-white">{row.name??row.email}</div><div className="text-[10px] text-slate-500">{row.email} {row.company?`· ${row.company}`:''}</div></div><span className="text-[10px] text-slate-500">{row.enrollments.length} enrollments</span><ChevronDown size={14} className={`text-slate-600 transition-transform ${open?'rotate-180':''}`}/></button>{open&&<div className="mt-4 space-y-3 pl-12">{row.enrollments.map(e=><div key={e.id} className="rounded-lg border border-white/[.06] bg-black/20 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><span className="text-[10px] font-mono uppercase tracking-wider text-orange-300">{e.domain}</span>{e.cds_customer_id&&<span className="ml-2 text-[10px] text-slate-600">CDS customer {customers.find(c=>c.id===e.cds_customer_id)?.company_name??e.cds_customer_id}</span>}</div><select value={e.status} onChange={x=>onStatus(e.id,x.target.value)} className="rounded-md border border-white/10 bg-slate-900 px-2 py-1 text-[10px] text-slate-300"><option>pending_verification</option><option>verified</option><option>active</option><option>suspended</option><option>revoked</option></select></div><div className="mt-3 grid gap-2 sm:grid-cols-2">{CATALOG.filter(([d])=>d===e.domain).map(([,event,label])=>{const s=e.subscriptions.find(x=>x.event_type===event&&x.channel==='email');return <label key={event} className="flex items-center justify-between rounded-md border border-white/[.05] px-3 py-2"><span className="text-[10px] text-slate-400">{label}</span><input type="checkbox" checked={!!s?.enabled} onChange={x=>onSubscription(e.id,event,x.target.checked)}/></label>})}</div></div>)}{!row.enrollments.length&&<EnrollmentCreator row={row} customers={customers} onEnroll={onEnroll}/>}</div>}</div>}
function EnrollmentCreator({row,customers,onEnroll}:{row:Recipient;customers:Customer[];onEnroll:(b:any)=>void}){const [domain,setDomain]=useState<'fleet'|'cds'>('fleet');const [customer,setCustomer]=useState('');const [role,setRole]=useState('client');return <div className="rounded-lg border border-dashed border-white/10 p-3"><div className="text-[10px] uppercase tracking-wider text-slate-600">Create enrollment</div><div className="mt-2 flex gap-2"><select value={domain} onChange={e=>setDomain(e.target.value as 'fleet'|'cds')} className="rounded-md border border-white/10 bg-slate-900 px-2 py-1.5 text-[10px] text-slate-300"><option value="fleet">Fleet</option><option value="cds">CDS customer</option></select>{domain==='cds'&&<select value={customer} onChange={e=>setCustomer(e.target.value)} className="min-w-0 flex-1 rounded-md border border-white/10 bg-slate-900 px-2 py-1.5 text-[10px] text-slate-300"><option value="">Select CDS customer…</option>{customers.map(c=><option key={c.id} value={c.id}>{c.company_name}</option>)}</select>}<input value={role} onChange={e=>setRole(e.target.value)} className="w-24 rounded-md border border-white/10 bg-slate-900 px-2 py-1.5 text-[10px] text-slate-300" placeholder="Role"/><button disabled={domain==='cds'&&!customer} onClick={()=>onEnroll({recipient_id:row.id,domain,cds_customer_id:domain==='cds'?customer:null,contact_role:role,status:'pending_verification'})} className="rounded-md bg-orange-600 px-3 py-1.5 text-[10px] font-semibold text-white disabled:opacity-40">Enroll</button></div></div>}
