import { useMemo, useState } from 'react'
import { useAuthStore } from '../stores/auth.js'
import { useRiskZones } from '../features/risk-intel/hooks/useRiskZones.js'
import RiskIntelPage from '../features/risk-intel/RiskIntelPage.js'
import { Activity, ArrowUpRight, BrainCircuit, ChevronRight, Crosshair, FileText, Globe2, Layers3, Radar, ShieldAlert, Sparkles, Target, TrendingUp, Waypoints } from 'lucide-react'

type View = 'overview' | 'global' | 'events' | 'countries' | 'operations' | 'reports'
const NAV: Array<{ id: View; label: string; icon: typeof Globe2; hint: string }> = [
  { id: 'overview', label: 'Global Picture', icon: Globe2, hint: 'Executive situational awareness' },
  { id: 'global', label: 'Threat Radar', icon: Radar, hint: 'Live risk geography' },
  { id: 'events', label: 'Fresh Events', icon: Activity, hint: 'Evidence-backed event stream' },
  { id: 'countries', label: 'Country Intelligence', icon: Target, hint: 'Persistent country assessments' },
  { id: 'operations', label: 'Operational Exposure', icon: Waypoints, hint: 'Threat → operation linkage' },
  { id: 'reports', label: 'Reports & Publications', icon: FileText, hint: 'Briefs, advisories and assessments' },
]
const ROLE_DEPTH: Record<string, { label: string; note: string; views: View[] }> = {
  admin: { label: 'FULL INTELLIGENCE', note: 'All intelligence workspaces and governance actions', views: NAV.map(n => n.id) },
  manager: { label: 'OPERATIONAL INTELLIGENCE', note: 'Operational exposure, events, country picture and radar', views: ['overview','global','events','countries','operations'] },
  analyst: { label: 'ANALYST WORKSPACE', note: 'Events, radar, country intelligence and operational context', views: ['overview','global','events','countries','operations'] },
  operator: { label: 'OPERATIONAL VIEW', note: 'Intelligence relevant to active operations', views: ['overview','global','events','operations'] },
  viewer: { label: 'INTELLIGENCE VIEWER', note: 'Read-only intelligence picture', views: ['overview','global','events','countries'] },
}
function Metric({ label, value, detail, icon: Icon, tone = 'cyan' }: { label:string; value:string; detail:string; icon:typeof Activity; tone?:'cyan'|'amber'|'red'|'green' }) { const tones={cyan:['#54d9ff','rgba(84,217,255,.08)','rgba(84,217,255,.16)'],amber:['#f7b955','rgba(247,185,85,.08)','rgba(247,185,85,.16)'],red:['#ff667d','rgba(255,102,125,.08)','rgba(255,102,125,.16)'],green:['#48e0b0','rgba(72,224,176,.08)','rgba(72,224,176,.16)']}[tone]; return <div style={{border:`1px solid ${tones[2]}`,background:'linear-gradient(145deg,rgba(13,28,47,.94),rgba(8,18,31,.94))',borderRadius:18,padding:18}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><span style={{fontSize:10,letterSpacing:'.14em',textTransform:'uppercase',color:'var(--d-t3)',fontFamily:'IBM Plex Mono,monospace'}}>{label}</span><span style={{width:30,height:30,borderRadius:9,display:'grid',placeItems:'center',color:tones[0],background:tones[1]}}><Icon size={15}/></span></div><div style={{marginTop:13,fontSize:28,lineHeight:1,fontWeight:700,color:'var(--d-t1)',letterSpacing:'-.03em'}}>{value}</div><div style={{marginTop:8,fontSize:11,color:tones[0]}}>{detail}</div></div> }
export default function IntelligenceCentre(){
  const user=useAuthStore(s=>s.user); const role=String(user?.role??'viewer').toLowerCase(); const profile=ROLE_DEPTH[role]??ROLE_DEPTH.viewer; const available=NAV.filter(n=>profile.views.includes(n.id)); const [view,setView]=useState<View>(available[0]?.id??'overview'); const {data,isLoading}=useRiskZones('global','all'); const counts=data?.counts??{high:0,medium:0,low:0,total:0}; const zones=data?.zones??[]; const highZones=useMemo(()=>zones.filter((z:any)=>z.level==='high').slice(0,5),[zones]);
  return <div style={{minHeight:'100%',background:'radial-gradient(circle at 80% 0%,rgba(40,110,170,.12),transparent 32%),#07111e',color:'#e8edf4',fontFamily:'Inter,system-ui,sans-serif',padding:'22px 24px 36px'}}>
    <header style={{maxWidth:1500,margin:'0 auto'}}><div style={{display:'flex',justifyContent:'space-between',gap:20,alignItems:'flex-start',flexWrap:'wrap'}}><div><div style={{display:'flex',alignItems:'center',gap:9,color:'#54d9ff',fontFamily:'IBM Plex Mono,monospace',fontSize:10,letterSpacing:'.2em',fontWeight:700}}><span style={{width:7,height:7,borderRadius:99,background:'#48e0b0',boxShadow:'0 0 12px #48e0b0'}}/>INTELLIGENCE SYSTEM · {profile.label}</div><h1 style={{margin:'9px 0 5px',fontSize:'clamp(28px,3vw,42px)',lineHeight:1,letterSpacing:'-.045em'}}>Intelligence Centre</h1><p style={{margin:0,maxWidth:720,color:'#7f91a6',fontSize:13,lineHeight:1.65}}>Evidence-backed situational awareness for security operations, convoy protection, client risk and operational decision-making.</p></div><div style={{display:'flex',gap:8,alignItems:'center',padding:'8px 11px',borderRadius:12,border:'1px solid rgba(72,224,176,.14)',background:'rgba(72,224,176,.05)',color:'#48e0b0',fontFamily:'IBM Plex Mono,monospace',fontSize:9,letterSpacing:'.08em'}}><Sparkles size={13}/> {profile.note.toUpperCase()}</div></div>
      <div style={{display:'flex',gap:4,overflowX:'auto',padding:'20px 0 14px',borderBottom:'1px solid rgba(255,255,255,.07)'}}>{available.map(item=>{const Icon=item.icon;const active=view===item.id;return <button key={item.id} onClick={()=>setView(item.id)} title={item.hint} style={{flex:'0 0 auto',display:'flex',alignItems:'center',gap:8,border:`1px solid ${active?'rgba(84,217,255,.25)':'transparent'}`,background:active?'rgba(84,217,255,.08)':'transparent',color:active?'#54d9ff':'#7f91a6',borderRadius:10,padding:'9px 12px',cursor:'pointer',fontSize:11,fontWeight:600,whiteSpace:'nowrap'}}><Icon size={14}/>{item.label}</button>})}</div>
    </header>
    <main style={{maxWidth:1500,margin:'0 auto',paddingTop:18}}>
      {view==='overview'&&<><section style={{display:'grid',gridTemplateColumns:'repeat(4,minmax(0,1fr))',gap:12}}><Metric label="Active risk zones" value={isLoading?'—':String(counts.total)} detail="Current global picture" icon={Globe2}/><Metric label="High severity" value={isLoading?'—':String(counts.high)} detail="Requires analyst attention" icon={ShieldAlert} tone="red"/><Metric label="Medium severity" value={isLoading?'—':String(counts.medium)} detail="Under active monitoring" icon={TrendingUp} tone="amber"/><Metric label="Intelligence posture" value="LIVE" detail="Collection + realtime connected" icon={BrainCircuit} tone="green"/></section>
        <section style={{display:'grid',gridTemplateColumns:'minmax(0,1.45fr) minmax(320px,.55fr)',gap:14,marginTop:14}}><div style={{minHeight:310,border:'1px solid rgba(255,255,255,.08)',borderRadius:20,overflow:'hidden',background:'rgba(8,19,32,.78)'}}><div style={{padding:'16px 18px',borderBottom:'1px solid rgba(255,255,255,.06)',display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><div style={{fontSize:11,fontWeight:700,letterSpacing:'.12em',textTransform:'uppercase'}}>Decision picture</div><div style={{marginTop:4,fontSize:11,color:'#6f8298'}}>What changed, where, and what does it expose?</div></div><button onClick={()=>setView('global')} style={{border:0,background:'transparent',color:'#54d9ff',fontSize:11,cursor:'pointer',display:'flex',alignItems:'center',gap:4}}>Open radar <ArrowUpRight size={13}/></button></div><div style={{padding:18,display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:10}}>{highZones.length?highZones.map((zone:any)=><button key={zone.id} onClick={()=>setView('global')} style={{textAlign:'left',border:'1px solid rgba(255,102,125,.14)',background:'rgba(255,102,125,.045)',borderRadius:14,padding:13,color:'#e8edf4',cursor:'pointer'}}><div style={{color:'#ff667d',fontSize:9,fontFamily:'IBM Plex Mono,monospace',letterSpacing:'.12em'}}>HIGH</div><div style={{marginTop:8,fontSize:13,fontWeight:700}}>{zone.name||zone.zone_code||'Risk zone'}</div><div style={{marginTop:6,color:'#71849a',fontSize:10}}>{zone.country_code||'Global'} · live monitoring</div></button>):<div style={{gridColumn:'1/-1',padding:30,textAlign:'center',color:'#687b91'}}>No high-severity zones currently returned by the intelligence feed.</div>}</div></div><div style={{border:'1px solid rgba(255,255,255,.08)',borderRadius:20,background:'rgba(8,19,32,.78)',padding:18}}><div style={{display:'flex',alignItems:'center',gap:8,color:'#54d9ff',fontSize:11,fontWeight:700,letterSpacing:'.12em',textTransform:'uppercase'}}><Crosshair size={14}/> Intelligence loop</div><div style={{marginTop:20,display:'grid',gap:11}}>{['Collect','Corroborate','Fuse','Assess','Forecast','Expose'].map((step,i)=><div key={step} style={{display:'flex',alignItems:'center',gap:11}}><span style={{width:24,height:24,display:'grid',placeItems:'center',borderRadius:8,background:'rgba(84,217,255,.07)',color:'#54d9ff',fontFamily:'IBM Plex Mono,monospace',fontSize:9}}>{String(i+1).padStart(2,'0')}</span><span style={{fontSize:12}}>{step}</span>{i<5&&<ChevronRight size={12} color="#3e5268"/>}</div>)}</div></div></section></>}
      {view==='global'&&<div style={{margin:'-4px -8px 0',minHeight:650,borderRadius:18,overflow:'hidden',border:'1px solid rgba(255,255,255,.07)'}}><RiskIntelPage/></div>}
      {view!=='overview'&&view!=='global'&&<div style={{minHeight:540,border:'1px solid rgba(255,255,255,.08)',borderRadius:22,background:'radial-gradient(circle at 80% 0%,rgba(84,217,255,.07),transparent 35%),rgba(8,19,32,.86)',display:'grid',placeItems:'center',padding:30}}><div style={{maxWidth:620,textAlign:'center'}}><div style={{width:58,height:58,margin:'0 auto 18px',borderRadius:18,display:'grid',placeItems:'center',background:'rgba(84,217,255,.08)',color:'#54d9ff'}}>{(()=>{const I=available.find(n=>n.id===view)?.icon??BrainCircuit;return <I size={27}/>})()}</div><div style={{fontSize:23,fontWeight:700}}>{available.find(n=>n.id===view)?.label}</div><p style={{color:'#74879c',fontSize:12,lineHeight:1.75,margin:'10px auto 22px'}}>{available.find(n=>n.id===view)?.hint}. This surface is available at the depth appropriate to the current role.</p><div style={{display:'inline-flex',alignItems:'center',gap:7,padding:'8px 12px',borderRadius:10,background:'rgba(72,224,176,.06)',border:'1px solid rgba(72,224,176,.13)',color:'#48e0b0',fontSize:10,fontFamily:'IBM Plex Mono,monospace',letterSpacing:'.08em'}}><Activity size={13}/> ROLE-AWARE WORKSPACE</div></div></div>}
    </main>
  </div>
}
