import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Activity, AlertTriangle, ArrowUpRight, BookOpen, ChevronRight, CircleDot, Clock3, Crosshair, DatabaseZap, ExternalLink, FileText, Gauge, Globe2, Layers3, Map as MapIcon, Network, Radar, RefreshCw, Search, ShieldCheck, Signal, Target, TicketCheck, Truck, Users, X, Zap } from 'lucide-react';
import Map, { Marker, NavigationControl } from 'react-map-gl/maplibre';
import 'maplibre-gl/dist/maplibre-gl.css';
import '../styles/intelligence-centre-deep.css';
import { api } from '../lib/api.js';

type Row=Record<string,any>;
type View='situation'|'signals'|'operations'|'atlas'|'countries'|'investigations'|'forecasts'|'publications'|'watchlists'|'sources';
type Scope={type:'global'|'continent'|'region'|'country';key:string;label:string};
type Selection={type:string;id:string;data:Row};

const NAV:[View,string,any,string][]=[
 ['situation','OPERATING PICTURE',Target,'01'],['signals','SIGNALS',Signal,'02'],['operations','OPERATIONS',Truck,'03'],['atlas','SPATIAL THEATRE',MapIcon,'04'],['countries','COUNTRIES',Globe2,'05'],['investigations','INVESTIGATIONS',Radar,'06'],['forecasts','FORECASTS',Activity,'07'],['publications','PUBLICATIONS',FileText,'08'],['watchlists','WATCHLISTS',CircleDot,'09'],['sources','SOURCES',BookOpen,'10']
];
const REGIONS:Record<string,string[]>={'east-africa':['BI','DJ','ER','ET','KE','KM','MG','MU','MW','MZ','RW','SC','SO','SS','TZ','UG','ZM','ZW'],'west-africa':['BJ','BF','CV','CI','GM','GH','GN','GW','LR','ML','MR','NE','NG','SH','SL','SN','TG'],'central-africa':['AO','CF','CG','CD','CM','GA','GQ','ST','TD'],'north-africa':['DZ','EG','LY','MA','SD','TN'],'southern-africa':['BW','LS','NA','SZ','ZA']};
const AFRICA=[...new Set(Object.values(REGIONS).flat())];
const ENDPOINTS={events:'/risk/intelligence/events',storylines:'/risk/intelligence/storylines',gaps:'/risk/intelligence/gaps',forecasts:'/risk/intelligence/forecasts',assessments:'/risk/intelligence/assessments',publications:'/risk/intelligence/publications',warnings:'/risk/intelligence/early-warnings',watchlists:'/risk/intelligence/watchlists',entities:'/risk/intelligence/entities',sources:'/risk/intelligence/sources',observations:'/risk/intelligence/observations',quality:'/risk/intelligence/quality'};
const EAST_AFRICA_CODES=['BI','DJ','ER','ET','KE','KM','MG','MU','MW','MZ','RW','SC','SO','SS','TZ','UG','ZM','ZW'];
const MAP_STYLE:any={version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'}},layers:[{id:'osm',type:'raster',source:'osm'}]};

function list(data:any,key:string):Row[]{if(Array.isArray(data))return data;if(Array.isArray(data?.[key]))return data[key];if(Array.isArray(data?.items))return data.items;return[]}
function titleOf(x:Row){return x.title||x.headline||x.name||x.reference||x.scenario||'INTELLIGENCE OBJECT'}
function textOf(x:Row){return x.summary||x.description||x.judgement||x.assessment||x.headline||x.status||'No analytical synopsis supplied.'}
function age(v?:string){if(!v)return'—';const m=Math.max(0,Math.floor((Date.now()-new Date(v).getTime())/60000));if(m<1)return'NOW';if(m<60)return`${m}M`;if(m<1440)return`${Math.floor(m/60)}H`;return`${Math.floor(m/1440)}D`}
function sev(v:any){const k=String(v||'informational').toLowerCase();return <span className={`icd-sev ${k}`}><i/>{k.toUpperCase()}</span>}
function scopeMatches(x:Row,s:Scope){if(s.type==='global')return true;const c=String(x.country_code||x.country||x.countryCode||'').toUpperCase();if(s.type==='country')return c===s.key;if(s.type==='region')return Boolean(REGIONS[s.key]?.includes(c))||String(x.scope_key||'').toLowerCase()===s.key;return AFRICA.includes(c)||String(x.scope_key||'').toLowerCase()===s.key}
function Kpi({label,value,sub,accent}:{label:string;value:any;sub:string;accent?:boolean}){return <div className={`icd-kpi ${accent?'accent':''}`}><span>{label}</span><strong>{value}</strong><small>{sub}</small></div>}
function Panel({title,kicker,meta,children,wide=false}:{title:string;kicker?:string;meta?:string;children:any;wide?:boolean}){return <section className={`icd-panel ${wide?'wide':''}`}><header><div><span>{kicker||'SONALIT / INTELLIGENCE'}</span><b>{title}</b></div>{meta&&<small>{meta}</small>}</header>{children}</section>}
function Rows({items,onSelect,empty='No records returned for the active scope.'}:{items:Row[];onSelect:(x:Row)=>void;empty?:string}){return items.length?<div className="icd-rows">{items.slice(0,100).map((x,i)=><button key={x.id||`${i}-${titleOf(x)}`} className="icd-row" onClick={()=>onSelect(x)}><span className="index">{String(i+1).padStart(2,'0')}</span><div><b>{titleOf(x)}</b><span>{textOf(x)}</span></div><aside>{x.country_code&&<em>{String(x.country_code).toUpperCase()}</em>}{x.severity&&sev(x.severity)}<small>{age(x.last_seen_at||x.updated_at||x.observed_at||x.created_at)}</small></aside><ChevronRight size={14}/></button>)}</div>:<div className="icd-empty"><Layers3 size={18}/><b>NO SIGNAL</b><span>{empty}</span></div>}

export default function IntelligenceCentreDeep(){
 const [view,setView]=useState<View>('situation');
 const [scope,setScope]=useState<Scope>({type:'global',key:'global',label:'GLOBAL'});
 const [query,setQuery]=useState('');
 const [severity,setSeverity]=useState('all');
 const [status,setStatus]=useState('all');
 const [windowHours,setWindowHours]=useState(24);
 const [selected,setSelected]=useState<Selection|null>(null);
 const [country,setCountry]=useState('');
 const params=scope.type==='global'?{scope_type:'global',scope_key:'global'}:{scope_type:scope.type,scope_key:scope.key,...(scope.type==='country'?{country_code:scope.key}:{})};
 const useIntel=(path:string,extra:Row={})=>useQuery({queryKey:['icd',path,params,extra],queryFn:async()=>{const r=await api.get(path,{params:{...params,...extra}});return r.data},staleTime:15_000,refetchInterval:30_000,retry:1});
 const eventsQ=useIntel(ENDPOINTS.events,{limit:500});
 const storiesQ=useIntel(ENDPOINTS.storylines);
 const gapsQ=useIntel(ENDPOINTS.gaps);
 const forecastsQ=useIntel(ENDPOINTS.forecasts);
 const assessmentsQ=useIntel(ENDPOINTS.assessments);
 const publicationsQ=useIntel(ENDPOINTS.publications);
 const warningsQ=useIntel(ENDPOINTS.warnings);
 const watchQ=useIntel(ENDPOINTS.watchlists);
 const entitiesQ=useIntel(ENDPOINTS.entities);
 const sourcesQ=useIntel(ENDPOINTS.sources);
 const observationsQ=useIntel(ENDPOINTS.observations,{limit:500});
 const qualityQ=useIntel(ENDPOINTS.quality);
 const trajectoriesQ=useIntel('/risk/intelligence/trajectories',{scope_type:scope.type==='country'?'country':'country',scope_key:scope.type==='country'?scope.key:undefined,limit:30});
 const exposuresQ=useIntel('/risk/intelligence/exposures',scope.type==='country'?{country_code:scope.key}:{});
 const linksQ=useIntel('/risk/intelligence/event-links');
 const requirementsQ=useIntel('/risk/intelligence/requirements');
 const collectionQ=useIntel('/risk/intelligence/collection/status');
 const countriesQ=useQuery({queryKey:['icd-countries'],queryFn:async()=>{const r=await api.get('/risk/intelligence/countries');return r.data},staleTime:30_000,refetchInterval:60_000,retry:1});
 const filtered=(xs:Row[])=>xs.filter(x=>{const t=new Date(x.last_seen_at||x.updated_at||x.observed_at||x.created_at||0).getTime();const recent=!t||Date.now()-t<=windowHours*3600000;const sevOk=severity==='all'||String(x.severity||'').toLowerCase()===severity;const statusOk=status==='all'||String(x.status||'').toLowerCase()===status;const q=!query.trim()||JSON.stringify(x).toLowerCase().includes(query.trim().toLowerCase());return recent&&sevOk&&statusOk&&q});
 const events=filtered(list(eventsQ.data,'events').filter(x=>scopeMatches(x,scope)));
 const stories=filtered(list(storiesQ.data,'storylines').filter(x=>scopeMatches(x,scope)));
 const gaps=filtered(list(gapsQ.data,'gaps').filter(x=>scopeMatches(x,scope)));
 const forecasts=filtered(list(forecastsQ.data,'forecasts').filter(x=>scopeMatches(x,scope)));
 const assessments=filtered(list(assessmentsQ.data,'assessments').filter(x=>scopeMatches(x,scope)));
 const publications=filtered(list(publicationsQ.data,'publications').filter(x=>scopeMatches(x,scope)));
 const warnings=filtered(list(warningsQ.data,'warnings').filter(x=>scopeMatches(x,scope)));
 const watch=filtered(list(watchQ.data,'watchlists').filter(x=>scopeMatches(x,scope)));
 const entities=filtered(list(entitiesQ.data,'entities').filter(x=>scopeMatches(x,scope)));
 const observations=filtered(list(observationsQ.data,'observations').filter(x=>scopeMatches(x,scope)));
 const sources=list(sourcesQ.data,'sources').filter(x=>scope.type==='global'||observations.some(o=>String(o.source_id)===String(x.id)));
 const countries=list(countriesQ.data,'countries').filter(x=>scopeMatches(x,scope));
 const trajectories=list(trajectoriesQ.data,'trajectories');
 const exposures=list(exposuresQ.data,'exposures');
 const links=list(linksQ.data,'links').filter(x=>scope.type==='global'||scopeMatches(x,scope));
 const requirements=list(requirementsQ.data,'requirements');
 const collection=list(collectionQ.data?.collection?.sources,'sources');
 const qd=qualityQ.data?.quality||{};
 const selectedEvent=useQuery({queryKey:['icd-event',selected?.id,params],enabled:selected?.type==='event'&&Boolean(selected.id),queryFn:async()=>{const r=await api.get(`/risk/intelligence/events/${selected!.id}`,{params});return r.data?.event},staleTime:30_000});
 const selectedWarning=useQuery({queryKey:['icd-warning',selected?.id],enabled:selected?.type==='warning'&&Boolean(selected.id),queryFn:async()=>{const r=await api.get(`/risk/intelligence/early-warnings/${selected!.id}/actions`);return r.data},staleTime:30_000});
 const countryAssessment=useQuery({queryKey:['icd-country-assessment',country],enabled:Boolean(country),queryFn:async()=>{const r=await api.get(`/risk/intelligence/countries/${country}/assessment`);return r.data},staleTime:30_000});
 const gps=events.filter(x=>Number.isFinite(Number(x.latitude))&&Number.isFinite(Number(x.longitude)));
 const mapCenter=gps.length?{longitude:Number(gps[0].longitude),latitude:Number(gps[0].latitude),zoom:4.5}:{longitude:37,latitude:-2,zoom:3.7};
 const priority=events.filter(x=>['critical','high'].includes(String(x.severity||'').toLowerCase())).length;
 const sourceHealthy=collection.filter(s=>s.active!==false&&['success','partial'].includes(String(s.health?.status||'success'))).length;
 const select=(type:string,x:Row)=>setSelected({type,id:String(x.id||x.event_id||x.warning_id||x.source_id||x.country_code),data:x});
 const scopeValue=scope.type==='global'?'global':`${scope.type}:${scope.key}`;
 const setScopeValue=(v:string)=>{if(v==='global'){setCountry('');setScope({type:'global',key:'global',label:'GLOBAL'});return}const [type,key]=v.split(':') as ['continent'|'region',string];setCountry('');setScope({type,key,label:key.replaceAll('-',' ').toUpperCase()})};
 const currentData={events,stories,gaps,forecasts,assessments,publications,warnings,watch,entities,observations,sources,countries,trajectories,exposures,links,requirements};
 const refresh=()=>[eventsQ,storiesQ,gapsQ,forecastsQ,assessmentsQ,publicationsQ,warningsQ,watchQ,entitiesQ,sourcesQ,observationsQ,qualityQ,trajectoriesQ,exposuresQ,linksQ,requirementsQ,countriesQ].forEach(q=>q.refetch());
 return <div className="icd-root">
  <header className="icd-top"><div><span className="icd-eyebrow">SONALIT / SECURITY INTELLIGENCE</span><h1>INTELLIGENCE CENTRE <em>DEEP</em></h1><p>Collection · fusion · analysis · warning · decision support</p></div><div className="icd-top-readout"><span><i/>FABRIC</span><b>LIVE</b><small>30S</small><button onClick={refresh}><RefreshCw size={14}/> REFRESH</button></div></header>
  <section className="icd-theatre"><div className="icd-theatre-id"><span>ACTIVE THEATRE</span><strong>{scope.label}</strong><small>Every query is scoped server-side; empty geography stays empty.</small></div><label><span>THEATRE</span><select value={scopeValue} onChange={e=>setScopeValue(e.target.value)}><option value="global">GLOBAL</option><option value="continent:africa">AFRICA</option>{Object.keys(REGIONS).map(k=><option key={k} value={`region:${k}`}>{k.replaceAll('-',' ').toUpperCase()}</option>)}</select></label><label><span>COUNTRY</span><select value={country} onChange={e=>{setCountry(e.target.value);if(e.target.value)setScope({type:'country',key:e.target.value,label:e.target.value})}}><option value="">ALL COUNTRIES</option>{[...new Set(EAST_AFRICA_CODES.concat(countries.map(c=>String(c.country_code||'').toUpperCase())))].filter(Boolean).map(c=><option key={c} value={c}>{c}</option>)}</select></label><label><span>WINDOW</span><select value={windowHours} onChange={e=>setWindowHours(Number(e.target.value))}><option value={1}>1H</option><option value={6}>6H</option><option value={24}>24H</option><option value={72}>72H</option><option value={168}>7D</option></select></label><div className="icd-query"><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="SEARCH THE ACTIVE INTELLIGENCE SPACE"/><kbd>/</kbd></div></section>
  <nav className="icd-nav">{NAV.map(([id,label,Icon,n])=><button key={id} className={view===id?'active':''} onClick={()=>setView(id)}><span>{n}</span><Icon size={14}/><b>{label}</b></button>)}</nav>
  <section className="icd-filterbar"><span>FILTER</span><select value={severity} onChange={e=>setSeverity(e.target.value)}><option value="all">ALL SEVERITIES</option><option value="critical">CRITICAL</option><option value="high">HIGH</option><option value="moderate">MODERATE</option><option value="low">LOW</option></select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">ALL STATUS</option><option value="discovered">DISCOVERED</option><option value="validating">VALIDATING</option><option value="fused">FUSED</option><option value="assessed">ASSESSED</option><option value="open">OPEN</option><option value="monitoring">MONITORING</option></select><span className="scope-chip"><ShieldCheck size={12}/> {scope.label}</span><span className="scope-chip">{events.length} EVENTS · {observations.length} OBSERVATIONS · {sources.length} SOURCES</span></section>

  {view==='situation'&&<main className="icd-main"><section className="icd-hero"><div><span className="icd-kicker">01 / COMMAND PICTURE</span><h2>{scope.label}<br/><em>operating picture</em></h2><p>A unified decision surface connecting live events, collection health, warnings, trajectories, analytical storylines and operational exposure.</p><div className="icd-hero-pills"><span><Crosshair size={12}/> {priority} PRIORITY</span><span><DatabaseZap size={12}/> {sources.length} SOURCES</span><span><Clock3 size={12}/> LATEST {age(events[0]?.last_seen_at)}</span></div></div><div className="icd-orbit"><div/><div/><div/><strong>{events.length}</strong><small>EVENT OBJECTS</small></div></section><div className="icd-kpis"><Kpi label="EVENTS" value={events.length} sub={`${windowHours}H scoped`} accent/><Kpi label="PRIORITY" value={priority} sub="high / critical"/><Kpi label="WARNINGS" value={warnings.length} sub="active indicators"/><Kpi label="TRAJECTORIES" value={trajectories.length} sub="risk paths"/><Kpi label="EXPOSURES" value={exposures.length} sub="warning-linked"/><Kpi label="COLLECTION" value={`${sourceHealthy}/${collection.length||sources.length}`} sub="healthy sources"/></div><div className="icd-grid"><Panel title="LIVE EVENT STREAM" kicker="COLLECTION → FUSION" meta={`${events.length} objects`} wide><Rows items={events} onSelect={x=>select('event',x)} empty="No scoped events. Collection may be quiet or degraded."/></Panel><Panel title="WARNING BOARD" kicker="DETECTION → WARNING" meta={`${warnings.length} open`}><Rows items={warnings} onSelect={x=>select('warning',x)}/></Panel><Panel title="RISK TRAJECTORY" kicker="FORWARD STATE" meta={`${trajectories.length} snapshots`}><Rows items={trajectories} onSelect={x=>select('trajectory',x)}/></Panel><Panel title="OPERATIONAL EXPOSURE" kicker="INTELLIGENCE → OPERATIONS" meta={`${exposures.length} links`}><Rows items={exposures} onSelect={x=>select('exposure',x)}/></Panel></div></main>}

  {view==='signals'&&<main className="icd-main"><div className="icd-viewhead"><div><span className="icd-kicker">02 / SIGNALS</span><h2>Event ledger</h2><p>Detected activity with severity, status, geography, source count and direct evidence drill-down.</p></div><strong>{events.length} MATCHES</strong></div><Panel title="EVENT LEDGER" meta="server-scoped + local analytical filters"><Rows items={events} onSelect={x=>select('event',x)}/></Panel></main>}

  {view==='operations'&&<main className="icd-main"><div className="icd-viewhead"><div><span className="icd-kicker">03 / OPERATIONS</span><h2>Risk → movement exposure</h2><p>Warnings are translated into affected operational objects without replacing Fleet Command data.</p></div></div><div className="icd-kpis"><Kpi label="EXPOSURES" value={exposures.length} sub="active links" accent/><Kpi label="OPEN WARNINGS" value={warnings.length} sub="detected"/><Kpi label="HIGH PRIORITY" value={exposures.filter(x=>['high','critical'].includes(String(x.severity||'').toLowerCase())).length} sub="exposure risk"/><Kpi label="MOVEMENT LINKS" value={exposures.filter(x=>x.convoy_id||x.movement_id).length} sub="explicit movement refs"/></div><Panel title="EXPOSURE MATRIX" meta="warning · geography · score"><Rows items={exposures} onSelect={x=>select('exposure',x)} empty="No warning exposure records are currently linked to the active theatre."/></Panel></main>}

  {view==='atlas'&&<main className="icd-main"><div className="icd-viewhead"><div><span className="icd-kicker">04 / SPATIAL THEATRE</span><h2>Geographic intelligence theatre</h2><p>Only observations carrying defensible latitude/longitude are plotted; unresolved events remain in the ledger.</p></div><strong>{gps.length} GEOLOCATED</strong></div><div className="icd-map-shell"><Map initialViewState={mapCenter} mapStyle={MAP_STYLE} style={{width:'100%',height:'100%'}} attributionControl={false}><NavigationControl position="top-right" showCompass={false}/>{gps.slice(0,250).map((x,i)=><Marker key={x.id||i} longitude={Number(x.longitude)} latitude={Number(x.latitude)} anchor="center" onClick={()=>select('event',x)}><button className={`icd-marker ${String(x.severity||'low').toLowerCase()}`} aria-label={titleOf(x)}><i/></button></Marker>)}</Map><div className="icd-map-overlay"><span>SPATIAL OBJECTS</span><b>{gps.length}</b><small>unresolved {events.length-gps.length}</small></div></div><Panel title="SPATIAL EVENT QUEUE" meta="map-linked"><Rows items={gps.slice(0,100)} onSelect={x=>select('event',x)}/></Panel></main>}

  {view==='countries'&&<main className="icd-main"><div className="icd-viewhead"><div><span className="icd-kicker">05 / COUNTRIES</span><h2>Country intelligence</h2><p>Country posture combines the actual event ledger with first-class country assessments and publication records.</p></div></div><div className="icd-country-grid">{countries.map(x=><button className="icd-country" key={x.country_code} onClick={()=>{setCountry(x.country_code);setScope({type:'country',key:x.country_code,label:x.country_code})}}><div><Globe2 size={14}/><b>{x.country_code}</b><span>{x.severity_rank>=3?'ELEVATED':'MONITOR'}</span></div><strong>{x.events_24h}</strong><small>24H EVENTS · {x.confidence??'—'}% CONF</small><em>Latest {age(x.last_seen_at)}</em></button>)}</div>{country&&<div className="icd-country-detail"><Panel title={`${country} ASSESSMENT`} meta="country-level analytical contract"><Rows items={list(countryAssessment.data?.assessment,'key').length?[]:(countryAssessment.data?.assessment?[countryAssessment.data.assessment]:[])} onSelect={x=>select('assessment',x)} empty="No current assessment narrative returned."/></Panel><Panel title={`${country} EVENT EVIDENCE`} meta={`${events.filter(e=>String(e.country_code).toUpperCase()===country).length} events`}><Rows items={events.filter(e=>String(e.country_code).toUpperCase()===country)} onSelect={x=>select('event',x)}/></Panel></div>}</main>}

  {view==='investigations'&&<main className="icd-main"><div className="icd-viewhead"><div><span className="icd-kicker">06 / INVESTIGATIONS</span><h2>Analytical graph</h2><p>Move from isolated alerts to storylines, collection gaps, intelligence requirements and event-to-event relationships.</p></div><span>{links.length} EVENT LINKS</span></div><div className="icd-grid"><Panel title="STORYLINES" meta={`${stories.length} active`}><Rows items={stories} onSelect={x=>select('storyline',x)}/></Panel><Panel title="COLLECTION GAPS" meta={`${gaps.length} outstanding`}><Rows items={gaps} onSelect={x=>select('gap',x)}/></Panel><Panel title="INTELLIGENCE REQUIREMENTS" meta={`${requirements.length} tasked`}><Rows items={requirements} onSelect={x=>select('requirement',x)}/></Panel><Panel title="EVENT RELATIONSHIPS" meta={`${links.length} links`}><Rows items={links} onSelect={x=>select('link',x)}/></Panel></div></main>}

  {view==='forecasts'&&<main className="icd-main"><div className="icd-viewhead"><div><span className="icd-kicker">07 / FORECASTS</span><h2>Forward state</h2><p>Probability, confidence, validity, assumptions, indicators, invalidation triggers and observed trajectory are kept separate.</p></div></div><div className="icd-grid"><Panel title="FORECASTS" meta={`${forecasts.length} active`} wide><Rows items={forecasts} onSelect={x=>select('forecast',x)}/></Panel><Panel title="ASSESSMENTS" meta={`${assessments.length} current`}><Rows items={assessments} onSelect={x=>select('assessment',x)}/></Panel><Panel title="TRAJECTORIES" meta={`${trajectories.length} snapshots`}><Rows items={trajectories} onSelect={x=>select('trajectory',x)}/></Panel></div></main>}

  {view==='publications'&&<main className="icd-main"><div className="icd-viewhead"><div><span className="icd-kicker">08 / PUBLICATIONS</span><h2>Dissemination control room</h2><p>Publication register with governance state and review count—separate from raw observation flow.</p></div></div><Panel title="PUBLICATION REGISTER" meta={`${publications.length} scoped products`}><Rows items={publications} onSelect={x=>select('publication',x)}/></Panel></main>}

  {view==='watchlists'&&<main className="icd-main"><div className="icd-viewhead"><div><span className="icd-kicker">09 / WATCHLISTS</span><h2>Continuous monitoring</h2><p>Persistent collection targets, early-warning conditions, action history and warning-linked exposure.</p></div></div><div className="icd-grid"><Panel title="WATCHLISTS" meta={`${watch.length} active`}><Rows items={watch} onSelect={x=>select('watchlist',x)}/></Panel><Panel title="EARLY WARNINGS" meta={`${warnings.length} active`}><Rows items={warnings} onSelect={x=>select('warning',x)}/></Panel><Panel title="WARNING EXPOSURE" meta={`${exposures.length} linked`}><Rows items={exposures} onSelect={x=>select('exposure',x)}/></Panel></div></main>}

  {view==='sources'&&<main className="icd-main"><div className="icd-viewhead"><div><span className="icd-kicker">10 / SOURCES</span><h2>Provenance, evidence & collection health</h2><p>Inspect source reliability, observation volume, manipulation flags and the health of the collection fabric.</p></div></div><div className="icd-kpis"><Kpi label="OBS / 30D" value={qd.observations_30d??'—'} sub="evidence volume"/><Kpi label="SOURCES / 30D" value={qd.sources_30d??'—'} sub="distinct sources"/><Kpi label="CREDIBILITY" value={qd.avg_credibility!=null?`${qd.avg_credibility}%`:'—'} sub="mean source score"/><Kpi label="MANIPULATION" value={qd.manipulation_flags??'—'} sub="flagged observations" accent/><Kpi label="OPEN GAPS" value={qd.open_gaps??'—'} sub="collection / analysis gaps"/></div><div className="icd-grid"><Panel title="SOURCE REGISTER" meta={`${sources.length} in scope`} wide><Rows items={sources} onSelect={x=>select('source',x)}/></Panel><Panel title="RECENT OBSERVATIONS" meta={`${observations.length} returned`}><Rows items={observations} onSelect={x=>select('observation',x)}/></Panel><Panel title="COLLECTION HEALTH" meta="provider-isolated"><Rows items={collection} onSelect={x=>select('collection',x)}/></Panel></div></main>}

  {selected&&<div className="icd-overlay" onClick={()=>setSelected(null)}><aside className="icd-drawer" onClick={e=>e.stopPropagation()}><header><div><span>INTELLIGENCE OBJECT · {selected.type.toUpperCase()}</span><h3>{titleOf(selectedEvent.data||selected.data)}</h3></div><button onClick={()=>setSelected(null)}><X size={16}/></button></header><div className="icd-drawer-meta">{selected.data.severity&&sev(selected.data.severity)}<span>{selected.data.country_code||selected.data.scope_key||scope.label}</span><span>{age(selected.data.last_seen_at||selected.data.updated_at||selected.data.observed_at||selected.data.created_at)}</span></div>{selected.type==='event'&&selectedEvent.data?.evidence&&<section className="icd-evidence"><b>EVIDENCE CHAIN</b><Rows items={selectedEvent.data.evidence} onSelect={x=>select('observation',x)} empty="No linked observations returned."/></section>}{selected.type==='warning'&&<section className="icd-evidence"><b>WARNING ACTIONS</b><Rows items={list(selectedWarning.data,'actions')} onSelect={x=>select('action',x)} empty="No action record returned."/></section>}{selected.type==='country'&&countryAssessment.data?.assessment&&<section className="icd-evidence"><b>COUNTRY ASSESSMENT</b><pre>{JSON.stringify(countryAssessment.data.assessment,null,2)}</pre></section>}<section className="icd-field-grid">{Object.entries(selected.data).filter(([k])=>!['body','metadata'].includes(k)).slice(0,50).map(([k,v])=><div key={k}><small>{k.replace(/_/g,' ')}</small><span>{typeof v==='object'?JSON.stringify(v,null,2):String(v??'—')}</span></div>)}</section>{selected.data.url&&<a className="icd-open" href={selected.data.url} target="_blank" rel="noreferrer"><ExternalLink size={13}/> OPEN ORIGINAL SOURCE</a>}{selected.data.source_url&&<a className="icd-open" href={selected.data.source_url} target="_blank" rel="noreferrer"><ExternalLink size={13}/> OPEN SOURCE EVIDENCE</a>}<footer><ShieldCheck size={13}/> Provenance retained · automated/public signal status remains visible.</footer></aside></div>}
 </div>;
}
