import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Activity, AlertTriangle, BookOpen, ChevronRight, CircleDot, Crosshair, FileText, Globe2, Layers3, Map as MapIcon, Radar, RefreshCw, Search, Signal, Target, Truck, X, Gauge, ShieldCheck, Eye, Clock3, Network, BarChart3, DatabaseZap, ArrowUpRight } from 'lucide-react';
import Map, { Marker, NavigationControl } from 'react-map-gl/maplibre';
import 'maplibre-gl/dist/maplibre-gl.css';
import { api } from '../lib/api.js';

type Row = Record<string, any>;
type View = 'situation'|'signals'|'operations'|'atlas'|'countries'|'investigations'|'forecasts'|'publications'|'watchlists'|'sources';
type Scope = { kind:'global'|'continent'|'region'|'country'; key:string; label:string };

const NAV:[View,string,any,string][] = [
  ['situation','OPERATING PICTURE',Target,'01'],['signals','SIGNALS',Signal,'02'],['operations','OPERATIONS',Truck,'03'],['atlas','SPATIAL THEATRE',MapIcon,'04'],['countries','COUNTRIES',Globe2,'05'],['investigations','INVESTIGATIONS',Radar,'06'],['forecasts','FORECASTS',Activity,'07'],['publications','PUBLICATIONS',FileText,'08'],['watchlists','WATCHLISTS',CircleDot,'09'],['sources','SOURCES',BookOpen,'10'],
];
const REGIONS:Record<string,string[]> = {'east-africa':['BI','DJ','ER','ET','KE','KM','MG','MU','MW','MZ','RW','SC','SO','SS','TZ','UG','ZM','ZW'],'west-africa':['BJ','BF','CV','CI','GM','GH','GN','GW','LR','ML','MR','NE','NG','SH','SL','SN','TG'],'central-africa':['AO','CF','CG','CD','CM','GA','GQ','ST','TD'],'north-africa':['DZ','EG','LY','MA','SD','TN'],'southern-africa':['BW','LS','NA','SZ','ZA']};
const AFRICA:string[]=[...new Set(Object.values(REGIONS).flat())];
const ENDPOINTS={events:'/risk/intelligence/events',storylines:'/risk/intelligence/storylines',gaps:'/risk/intelligence/gaps',forecasts:'/risk/intelligence/forecasts',assessments:'/risk/intelligence/assessments',publications:'/risk/intelligence/publications',warnings:'/risk/intelligence/early-warnings',watchlists:'/risk/intelligence/watchlists',entities:'/risk/intelligence/entities',sources:'/risk/intelligence/sources',observations:'/risk/intelligence/observations',quality:'/risk/intelligence/quality'};
const OSM_STYLE:any={version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'}},layers:[{id:'osm',type:'raster',source:'osm'}]};
function list(data:any,key:string):Row[]{if(Array.isArray(data))return data;if(Array.isArray(data?.[key]))return data[key];if(Array.isArray(data?.items))return data.items;return[]}
function code(x:Row){return String(x.country_code||x.country||x.countryCode||'').toUpperCase()}
function scopeMatch(x:Row,s:Scope){if(s.kind==='global')return true;const c=code(x);if(s.kind==='country')return c===s.key;const key=String(x.scope_key||x.scope?.scope_key||'').toLowerCase();return s.kind==='region'?(REGIONS[s.key]?.includes(c)||key===s.key):(AFRICA.includes(c)||key===s.key)}
function age(v?:string){if(!v)return'—';const m=Math.max(0,Math.floor((Date.now()-new Date(v).getTime())/60000));if(m<1)return'NOW';if(m<60)return`${m}M`;if(m<1440)return`${Math.floor(m/60)}H`;return`${Math.floor(m/1440)}D`}
function severity(v:any){const k=String(v||'informational').toLowerCase();return <span className={`icx-sev ${k}`}><i/>{k.toUpperCase()}</span>}
function titleOf(x:Row){return x.title||x.headline||x.name||x.reference||x.scenario||'INTELLIGENCE OBJECT'}
function subtitleOf(x:Row){return x.summary||x.description||x.judgement||x.assessment||x.scope_key||x.status||'Verified intelligence object'}
function Panel({title,meta,kicker,icon:Icon,children,className='' }:{title:string;meta?:string;kicker?:string;icon?:any;children:any;className?:string}){return <section className={`icx-panel ${className}`}><header className="icx-panel-head"><div className="icx-panel-title"><span className="icx-kicker">{kicker||'SONALIT / INTELLIGENCE'}</span><div>{Icon&&<Icon size={15}/>}<b>{title}</b></div></div>{meta&&<span className="icx-panel-meta">{meta}</span>}</header>{children}</section>}
function Rows({items,onSelect}:{items:Row[];onSelect:(x:Row)=>void}){if(!items.length)return <div className="icx-empty"><Layers3 size={18}/><b>NO VERIFIED OBJECTS IN THIS SCOPE</b><span>Unattributed or out-of-scope material is withheld by design.</span></div>;return <div className="icx-rows">{items.slice(0,100).map((x,i)=><button className="icx-row" key={x.id||i} onClick={()=>onSelect(x)}><span className="icx-row-index">{String(i+1).padStart(2,'0')}</span><div className="icx-row-main"><b>{titleOf(x)}</b><span>{subtitleOf(x)}</span></div><div className="icx-row-tags">{x.country_code&&<span>{String(x.country_code).toUpperCase()}</span>}{x.severity&&severity(x.severity)}</div><small className="icx-row-age">{age(x.last_seen_at||x.updated_at||x.observed_at||x.created_at)}</small><ChevronRight size={15}/></button>)}</div>}
function SignalRow({x,onSelect}:{x:Row;onSelect:(x:Row)=>void}){return <button className="icx-signal-row" onClick={()=>onSelect(x)}><span className="icx-signal-dot"/><div><b>{titleOf(x)}</b><span>{subtitleOf(x)}</span></div><aside>{x.severity&&severity(x.severity)}<small>{age(x.last_seen_at||x.updated_at||x.created_at)}</small></aside></button>}
function Drawer({x,onClose}:{x:Row;onClose:()=>void}){return <div className="icx-backdrop" onClick={onClose}><aside className="icx-drawer" onClick={e=>e.stopPropagation()}><header className="icx-drawer-head"><div><span className="icx-kicker">SCOPED INTELLIGENCE OBJECT</span><h3>{titleOf(x)}</h3></div><button onClick={onClose} aria-label="Close"><X size={17}/></button></header><div className="icx-drawer-status"><ShieldCheck size={15}/><span>OBJECT RETAINED · SCOPE CHECK PASSED</span></div><div className="icx-fields">{Object.entries(x).filter(([k])=>!['body','metadata'].includes(k)).slice(0,40).map(([k,v])=><div key={k}><small>{k.replace(/_/g,' ')}</small><span>{typeof v==='object'?JSON.stringify(v,null,2):String(v??'—')}</span></div>)}</div><div className="icx-drawer-foot"><Eye size={14}/> Provenance and original fields remain attached to the object.</div></aside></div>}

export default function IntelligenceCentreScoped(){
 const [view,setView]=useState<View>('situation');const [scope,setScope]=useState<Scope>({kind:'global',key:'global',label:'GLOBAL'});const [country,setCountry]=useState('');const [search,setSearch]=useState('');const [selected,setSelected]=useState<Row|null>(null);
 const params=scope.kind==='global'?{scope_type:'global',scope_key:'global'}:{scope_type:scope.kind,scope_key:scope.key,...(scope.kind==='country'?{country_code:scope.key}:{})};
 const useIntel=(path:string)=>useQuery({queryKey:['intel-centre',path,params],queryFn:async()=>{const r=await api.get(path,{params});return r.data},staleTime:15000,refetchInterval:30000,retry:1});
 const [eventsQ,storiesQ,gapsQ,forecastsQ,assessmentsQ,publicationsQ,warningsQ,watchQ,entitiesQ,sourcesQ,observationsQ,qualityQ]=[useIntel(ENDPOINTS.events),useIntel(ENDPOINTS.storylines),useIntel(ENDPOINTS.gaps),useIntel(ENDPOINTS.forecasts),useIntel(ENDPOINTS.assessments),useIntel(ENDPOINTS.publications),useIntel(ENDPOINTS.warnings),useIntel(ENDPOINTS.watchlists),useIntel(ENDPOINTS.entities),useIntel(ENDPOINTS.sources),useIntel(ENDPOINTS.observations),useIntel(ENDPOINTS.quality)];
 const allQs=[eventsQ,storiesQ,gapsQ,forecastsQ,assessmentsQ,publicationsQ,warningsQ,watchQ,entitiesQ,sourcesQ,observationsQ,qualityQ];const events=list(eventsQ.data,'events').filter(x=>scopeMatch(x,scope));const stories=list(storiesQ.data,'storylines').filter(x=>scopeMatch(x,scope));const gaps=list(gapsQ.data,'gaps').filter(x=>scopeMatch(x,scope));const forecasts=list(forecastsQ.data,'forecasts').filter(x=>scopeMatch(x,scope));const assessments=list(assessmentsQ.data,'assessments').filter(x=>scopeMatch(x,scope));const publications=list(publicationsQ.data,'publications').filter(x=>scopeMatch(x,scope));const warnings=list(warningsQ.data,'warnings').filter(x=>scopeMatch(x,scope));const watch=list(watchQ.data,'watchlists').filter(x=>scopeMatch(x,scope));const entities=list(entitiesQ.data,'entities').filter(x=>scopeMatch(x,scope));const observations=list(observationsQ.data,'observations').filter(x=>scopeMatch(x,scope));const sources=list(sourcesQ.data,'sources').filter(x=>scope.kind==='global'||observations.some(o=>String(o.source_id)===String(x.id)));
 const countryCodes=[...new Set(events.map(code).filter(Boolean))].sort();const query=search.trim().toLowerCase();const visible=(xs:Row[])=>query?xs.filter(x=>JSON.stringify(x).toLowerCase().includes(query)):xs;const loading=allQs.some(q=>q.isLoading);const errors=allQs.filter(q=>q.isError);const refresh=()=>allQs.forEach(q=>q.refetch());
 const setScopeValue=(v:string)=>{if(v==='global'){setCountry('');setScope({kind:'global',key:'global',label:'GLOBAL'});return}const [kind,key]=v.split(':') as ['continent'|'region',string];setCountry('');setScope({kind,key,label:key.replaceAll('-',' ').toUpperCase()})};const applyCountry=(v:string)=>{setCountry(v);if(v)setScope({kind:'country',key:v,label:v})};const gpsEvents=events.filter(x=>Number.isFinite(Number(x.latitude))&&Number.isFinite(Number(x.longitude)));const initial=gpsEvents.length?{longitude:Number(gpsEvents[0].longitude),latitude:Number(gpsEvents[0].latitude),zoom:4.4}:{longitude:25,latitude:-3,zoom:3.2};const countryRows=countryCodes.map(c=>({country_code:c,title:c,summary:`${events.filter(e=>code(e)===c).length} event objects detected`,severity:events.filter(e=>code(e)===c).some(e=>['critical','high'].includes(String(e.severity).toLowerCase()))?'high':'moderate'}));const priority=events.filter(e=>['critical','high'].includes(String(e.severity||'').toLowerCase())).length;const latestEvents=visible(events).slice(0,8);const topStories=visible(stories).slice(0,5);
 return <div className="icx-root"><div className="icx-noise"/>
  <header className="icx-top"><div className="icx-top-brand"><div className="icx-eyebrow">SONALIT / SECURITY INTELLIGENCE</div><div className="icx-brand">INTELLIGENCE <span>CENTRE</span></div><div className="icx-top-status"><i/> LIVE FABRIC <span>·</span> ORG-ISOLATED <span>·</span> GEO-ENFORCED <span>·</span> FAIL-CLOSED</div></div><div className="icx-top-actions"><div className="icx-system-readout"><span>INGEST</span><b>{loading?'SYNC':'LIVE'}</b><span>30s</span></div><button className="icx-refresh" onClick={refresh}><RefreshCw size={15}/> REFRESH</button></div></header>
  <section className="icx-scope"><div className="icx-scope-identity"><span className="icx-kicker">ACTIVE THEATRE</span><strong>{scope.label}</strong><span>{scope.kind==='global'?'Organisation-wide verified intelligence':'Only intelligence attributable to the selected geography'}</span></div><label><span>SCOPE</span><select value={scope.kind==='global'?'global':`${scope.kind}:${scope.key}`} onChange={e=>setScopeValue(e.target.value)}><option value="global">GLOBAL</option><option value="continent:africa">AFRICA</option>{Object.keys(REGIONS).map(k=><option key={k} value={`region:${k}`}>{k.replaceAll('-',' ').toUpperCase()}</option>)}</select></label><label><span>COUNTRY</span><select value={country} onChange={e=>applyCountry(e.target.value)}><option value="">ALL COUNTRIES</option>{countryCodes.map(c=><option key={c} value={c}>{c}</option>)}</select></label><div className="icx-search"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="QUERY THE ACTIVE INTELLIGENCE SPACE"/><kbd>/</kbd></div></section>
  <nav className="icx-nav" aria-label="Intelligence Centre views">{NAV.map(([id,label,Icon,no])=><button key={id} className={view===id?'active':''} onClick={()=>setView(id)}><span>{no}</span><Icon size={14}/><b>{label}</b></button>)}</nav>
  {errors.length>0&&<div className="icx-warning"><AlertTriangle size={16}/><div><b>PARTIAL FABRIC DEGRADATION</b><span>{errors.length} intelligence surface(s) are unavailable. No failed surface is substituted with unscoped data.</span></div><button onClick={refresh}>RETRY</button></div>}
  {view==='situation'&&<main className="icx-main"><section className="icx-command-hero"><div className="icx-hero-copy"><span className="icx-kicker">01 / COMMAND PICTURE</span><h1>{scope.label}<br/><em>operating picture.</em></h1><p>One spatially scoped environment for signals, risk events, emerging storylines and evidence. Every surface inherits the active geographic boundary.</p><div className="icx-hero-pills"><span><ShieldCheck size={13}/> SCOPE LOCKED</span><span><Crosshair size={13}/> {priority} PRIORITY OBJECTS</span><span><Clock3 size={13}/> {latestEvents.length?`LATEST ${age(latestEvents[0]?.last_seen_at||latestEvents[0]?.updated_at)}`:'NO RECENT OBJECT'}</span></div></div><div className="icx-command-orbit"><div className="orbit-ring r1"/><div className="orbit-ring r2"/><div className="orbit-ring r3"/><div className="orbit-core"><span>VERIFIED</span><b>{events.length}</b><small>EVENT OBJECTS</small></div></div></section>
   <section className="icx-metric-rail"><div><span>EVENTS</span><b>{events.length}</b><small>SCOPED OBJECTS</small></div><div><span>PRIORITY</span><b>{priority}</b><small>HIGH / CRITICAL</small></div><div><span>STORYLINES</span><b>{stories.length}</b><small>EMERGING NARRATIVES</small></div><div><span>WARNINGS</span><b>{warnings.length}</b><small>EARLY INDICATORS</small></div><div><span>FORECASTS</span><b>{forecasts.length}</b><small>ACTIVE OUTLOOKS</small></div><div><span>SOURCES</span><b>{sources.length}</b><small>SCOPED PROVENANCE</small></div></section>
   <section className="icx-command-grid"><Panel title="LIVE SIGNAL PICTURE" kicker="02 / COLLECTION → FUSION" icon={Signal} meta={`${latestEvents.length} latest`} className="wide"><div className="icx-live-list">{latestEvents.length?latestEvents.map((x,i)=><SignalRow key={x.id||i} x={x} onSelect={setSelected}/>):<div className="icx-empty"><Signal size={18}/><b>NO LIVE SIGNALS</b><span>The active scope currently contains no verified event objects.</span></div>}</div></Panel><Panel title="SPATIAL THEATRE" kicker="03 / GEOGRAPHY" icon={Globe2} meta={`${gpsEvents.length} mapped`} className="theatre"><div className="icx-theatre"><Map initialViewState={initial} mapStyle={OSM_STYLE} attributionControl={false}><NavigationControl position="top-right" showCompass={false} showZoom={false}/>{gpsEvents.slice(0,80).map((e,i)=><Marker key={e.id||i} longitude={Number(e.longitude)} latitude={Number(e.latitude)} anchor="center"><button className={`icx-map-pin ${String(e.severity||'').toLowerCase()}`} title={titleOf(e)} onClick={()=>setSelected(e)}><span/></button></Marker>)}</Map><div className="icx-map-hud"><span>LIVE EVENTS</span><b>{gpsEvents.length}</b><small>{scope.label}</small></div><div className="icx-map-grid"/></div></Panel><Panel title="EMERGING STORYLINES" kicker="04 / ANALYSIS" icon={Network} meta={`${stories.length} tracked`}><Rows items={topStories} onSelect={setSelected}/></Panel><Panel title="EARLY WARNING / WATCH" kicker="05 / PRIORITY" icon={Gauge} meta={`${warnings.length+watch.length} objects`}><Rows items={visible([...warnings,...watch]).slice(0,8)} onSelect={setSelected}/></Panel></section>
   <section className="icx-bottom-grid"><Panel title="COUNTRY COVERAGE" kicker="06 / OPERATING THEATRE" icon={Globe2} meta={`${countryRows.length} countries`}><Rows items={visible(countryRows).slice(0,10)} onSelect={x=>applyCountry(x.country_code)}/></Panel><Panel title="COLLECTION QUALITY" kicker="07 / EVIDENCE HEALTH" icon={DatabaseZap} meta="LIVE QUALITY MODEL"><div className="icx-quality-grid"><div><small>OBSERVATIONS</small><b>{observations.length}</b><span>persisted</span></div><div><small>AVG CREDIBILITY</small><b>{qualityQ.data?.quality?.avg_credibility??'—'}{qualityQ.data?.quality?.avg_credibility!=null?'%':''}</b><span>source model</span></div><div><small>OPEN GAPS</small><b>{gaps.length}</b><span>collection</span></div><div><small>ENTITIES</small><b>{entities.length}</b><span>resolved</span></div></div><div className="icx-quality-note"><ShieldCheck size={14}/><span>Evidence is retained independently from analytic judgement. Empty collection states remain empty.</span></div></Panel></section>
  </main>}
  {view==='signals'&&<main className="icx-main"><div className="icx-view-head"><div><span className="icx-kicker">02 / SIGNALS</span><h2>Event ledger</h2><p>Verified event objects inside the active theatre.</p></div><span className="icx-head-counter">{visible(events).length} VISIBLE</span></div><Panel title="SCOPED EVENT LEDGER" icon={Signal} meta={`${visible(events).length} objects`}><Rows items={visible(events)} onSelect={setSelected}/></Panel></main>}
  {view==='operations'&&<main className="icx-main"><div className="icx-view-head"><div><span className="icx-kicker">03 / OPERATIONS</span><h2>Operational risk picture</h2><p>Event material that can alter movement, route, exposure or response posture.</p></div><span className="icx-head-counter">{priority} PRIORITY</span></div><div className="icx-command-grid"><Panel title="OPERATIONAL RISK" icon={Truck} meta={`${visible(events).length} events`} className="wide"><Rows items={visible(events)} onSelect={setSelected}/></Panel><Panel title="CURRENT WATCH" icon={Crosshair} meta={`${watch.length} lists`}><Rows items={visible(watch)} onSelect={setSelected}/></Panel></div></main>}
  {view==='atlas'&&<main className="icx-main"><div className="icx-view-head"><div><span className="icx-kicker">04 / SPATIAL THEATRE</span><h2>Geographic intelligence theatre</h2><p>Spatially resolved event objects are plotted against the active scope.</p></div><span className="icx-head-counter">{gpsEvents.length} MAPPED</span></div><Panel title="THEATRE MAP" icon={MapIcon} meta={`${gpsEvents.length} plotted`}><div className="icx-full-map"><Map initialViewState={initial} mapStyle={OSM_STYLE}><NavigationControl position="top-right"/>{gpsEvents.map((e,i)=><Marker key={e.id||i} longitude={Number(e.longitude)} latitude={Number(e.latitude)}><button className={`icx-map-pin ${String(e.severity||'').toLowerCase()}`} onClick={()=>setSelected(e)}><span/></button></Marker>)}</Map><div className="icx-map-hud large"><span>THEATRE</span><b>{scope.label}</b><small>{gpsEvents.length} spatial objects</small></div></div></Panel><div className="icx-atlas-grid">{Object.entries(REGIONS).map(([k,c])=><button key={k} onClick={()=>setScope({kind:'region',key:k,label:k.replaceAll('-',' ').toUpperCase()})}><span>{k.slice(0,2).toUpperCase()}</span><b>{k.replaceAll('-',' ').toUpperCase()}</b><small>{c.length} country nodes</small><ArrowUpRight size={14}/></button>)}</div></main>}
  {view==='countries'&&<main className="icx-main"><div className="icx-view-head"><div><span className="icx-kicker">05 / COUNTRIES</span><h2>Country intelligence</h2><p>Coverage derived from the active event ledger.</p></div><span className="icx-head-counter">{countryRows.length} NODES</span></div><Panel title="COUNTRY REGISTER" icon={Globe2}><Rows items={visible(countryRows)} onSelect={x=>applyCountry(x.country_code)}/></Panel></main>}
  {view==='investigations'&&<main className="icx-main"><div className="icx-view-head"><div><span className="icx-kicker">06 / INVESTIGATIONS</span><h2>Storylines & collection gaps</h2><p>Analysis objects and missing evidence in the current theatre.</p></div></div><div className="icx-command-grid"><Panel title="STORYLINES" icon={Network} meta={`${stories.length}`}><Rows items={visible(stories)} onSelect={setSelected}/></Panel><Panel title="COLLECTION GAPS" icon={Layers3} meta={`${gaps.length}`}><Rows items={visible(gaps)} onSelect={setSelected}/></Panel></div></main>}
  {view==='forecasts'&&<main className="icx-main"><div className="icx-view-head"><div><span className="icx-kicker">07 / FORECASTS</span><h2>Outlook & assessment</h2><p>Forward-looking analytic objects remain separate from source observations.</p></div></div><div className="icx-command-grid"><Panel title="FORECASTS" icon={Activity} meta={`${forecasts.length}`}><Rows items={visible(forecasts)} onSelect={setSelected}/></Panel><Panel title="ASSESSMENTS" icon={BarChart3} meta={`${assessments.length}`}><Rows items={visible(assessments)} onSelect={setSelected}/></Panel></div></main>}
  {view==='publications'&&<main className="icx-main"><div className="icx-view-head"><div><span className="icx-kicker">08 / PUBLICATIONS</span><h2>Publication register</h2><p>Structured analytic outputs retained with their provenance.</p></div></div><Panel title="PUBLICATIONS" icon={FileText} meta={`${publications.length}`}><Rows items={visible(publications)} onSelect={setSelected}/></Panel></main>}
  {view==='watchlists'&&<main className="icx-main"><div className="icx-view-head"><div><span className="icx-kicker">09 / WATCHLISTS</span><h2>Watch & warning system</h2><p>Persistent watch objects alongside time-sensitive early warnings.</p></div></div><div className="icx-command-grid"><Panel title="WATCHLISTS" icon={CircleDot} meta={`${watch.length}`}><Rows items={visible(watch)} onSelect={setSelected}/></Panel><Panel title="EARLY WARNINGS" icon={AlertTriangle} meta={`${warnings.length}`}><Rows items={visible(warnings)} onSelect={setSelected}/></Panel></div></main>}
  {view==='sources'&&<main className="icx-main"><div className="icx-view-head"><div><span className="icx-kicker">10 / SOURCES</span><h2>Evidence & provenance</h2><p>Source coverage, observations, entities and collection health.</p></div></div><div className="icx-quality-grid standalone"><div><small>OBSERVATIONS</small><b>{observations.length}</b><span>persisted</span></div><div><small>SOURCES IN SCOPE</small><b>{sources.length}</b><span>provenance</span></div><div><small>AVG CREDIBILITY</small><b>{qualityQ.data?.quality?.avg_credibility??'—'}{qualityQ.data?.quality?.avg_credibility!=null?'%':''}</b><span>quality</span></div><div><small>OPEN GAPS</small><b>{gaps.length}</b><span>collection</span></div></div><div className="icx-command-grid"><Panel title="SOURCE REGISTER" icon={BookOpen} meta={`${sources.length}`}><Rows items={sources} onSelect={setSelected}/></Panel><Panel title="ENTITY GRAPH NODES" icon={Network} meta={`${entities.length}`}><Rows items={entities} onSelect={setSelected}/></Panel></div></main>}
  {selected&&<Drawer x={selected} onClose={()=>setSelected(null)}/>} 
 </div>;
}
