apiVersion: v1
kind: Namespace
metadata:
  name: sonalit-prod
  labels:
    app.kubernetes.io/managed-by: argocd
    environment: production
    team: platform
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: sonalit-prod-quota
  namespace: sonalit-prod
spec:
  hard:
    requests.cpu: "200"
    requests.memory: 400Gi
    limits.cpu: "400"
    limits.memory: 800Gi
    pods: "500"
    services: "100"
    services.loadbalancers: "5"
    services.nodeports: "0"
    persistentvolumeclaims: "100"
    requests.storage: 20Ti
    count/deployments.apps: "50"
    count/statefulsets.apps: "20"
    count/cronjobs.batch: "20"
    count/jobs.batch: "100"
    count/secrets: "200"
    count/configmaps: "200"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: sonalit-prod-limits
  namespace: sonalit-prod
spec:
  limits:
    - type: Container
      default:
        cpu: "1"
        memory: 512Mi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      max:
        cpu: "16"
        memory: 32Gi
      min:
        cpu: 10m
        memory: 16Mi
    - type: Pod
      max:
        cpu: "32"
        memory: 64Gi
      min:
        cpu: 10m
        memory: 16Mi
    - type: PersistentVolumeClaim
      max:
        storage: 2Ti
      min:
        storage: 1Gi
